package dev.openrune.impl

import dev.openrune.definition.dbtables.dbTable
import dev.openrune.definition.util.VarType

public const val Z_BIT_COUNT: Int = 14
public const val X_BIT_COUNT: Int = 14

public const val Z_BIT_OFFSET: Int = 0
public const val X_BIT_OFFSET: Int = Z_BIT_OFFSET + Z_BIT_COUNT

public const val Z_BIT_MASK: Int = (1 shl Z_BIT_COUNT) - 1
public const val X_BIT_MASK: Int = (1 shl X_BIT_COUNT) - 1
public const val LENGTH: Int = 64

fun packVertex(mx: Int, mz: Int, lx: Int, lz: Int): Int {
    require(mx in 0..X_BIT_MASK)
    require(mz in 0..Z_BIT_MASK)
    require(lx in 0..X_BIT_MASK)
    require(lz in 0..Z_BIT_MASK)

    val x = mx * LENGTH + lx
    val z = mz * LENGTH + lz

    require(x in 0..X_BIT_MASK)
    require(z in 0..Z_BIT_MASK)

    return ((x and X_BIT_MASK) shl X_BIT_OFFSET) or ((z and Z_BIT_MASK) shl Z_BIT_OFFSET)
}

object Music {

    /**
     * A music area and the tracks that shuffle inside it. [area] is the bare area gameval name
     * (`area.<area>` must exist in `.data/gamevals/area.rscm` and have a polygon under
     * `.data/raw-cache/map/area`), and [tracks] are `dbrow.music_*` rows from the cache.
     */
    private data class ModernArea(val row: String, val area: String, val tracks: List<String>)

    private fun modern(area: String, vararg tracks: String) =
        ModernArea("dbrow.music_modern_$area", area, tracks.map { "dbrow.music_$it" })

    /** Track lists follow the OSRS wiki "Music" section of each location. */
    private val MODERN_AREAS =
        listOf(
            modern("lumbridge", "autumn_voyage", "book_of_spells", "dream", "flute_salad", "harmony", "yesteryear"),
            modern("draynor_village", "start", "unknown_land", "wander"),
            modern("draynor_manor", "spooky"),
            modern("wizards_tower", "vision"),
            modern("zanaris", "faerie", "crystal_cave"),
            modern(
                "varrock",
                "adventure",
                "garden",
                "medieval",
                "spirit",
                "looking_back",
                "doorways",
                "expanse",
                "greatness",
                "still_night",
            ),
            // The Grand Exchange plays its own track; its footprint is carved out of the Varrock
            // polygon so the two areas never overlap.
            modern("grand_exchange", "the_trade_parade"),
            modern("barbarian_village", "barbarianism"),
            modern("edgeville", "forever"),
            // The Wilderness gameplay area already has an onArea script, and an area may only have
            // one, so its music lives on a twin area with the same polygon.
            modern(
                "wilderness_music",
                "army_of_darkness",
                "close_quarters",
                "dangerous",
                "everlasting_fire",
                "faithless",
                "forbidden",
                "inspiration",
                "moody",
                "pirates_of_peril",
                "regal",
                "scape_sad",
                "scape_wild",
                "shining",
                "troubled",
                "undercurrent",
                "underground",
                "wild_isle",
                "wild_side",
                "wilderness",
                "wilderness2",
                "wilderness3",
                "witching",
                "wonder",
                "crystal_sword",
                "dark",
                "dead_can_dance",
                "deep_wildy",
                "venomous",
                "wildwood",
            ),
            modern("falador", "arrival", "fanfare", "workshop"),
            modern("falador_south", "long_way_home", "miles_away", "nightfall", "wander"),
            modern("falador_north", "lightness", "scape_soft"),
            modern("taverley", "horizon", "splendour"),
            modern("rimmington", "attention", "emperor", "long_way_home"),
            modern("burthorpe", "principality", "kingdom"),
            modern("goblin_village", "goblin_village", "too_many_cooks"),
            modern("ice_mountain", "alone"),
            modern("asgarnian_ice_dungeon", "starlight", "woe_of_the_wyvern"),
            modern("taverley_dungeon", "arabique", "courage", "dunjun", "royale", "underground"),
            modern("catherby", "fishing", "lightwalk"),
            modern("seers_village", "overture", "prime_time", "twilight", "talking_forest"),
            modern("camelot", "camelot"),
            modern("rellekka", "rellekka"),
            modern("brineratcavern", "rising_damp"),
            modern("barbarian_outpost", "legion"),
            modern("al_kharid", "al_kharid", "arabian", "arabian2"),
            modern("port_sarim", "sea_shanty2"),
            modern("mudskipper_point", "mudskipper_melody"),
            modern("fishing_guild", "mellow", "voyage", "waterfall"),
            modern("east_ardougne", "baroque", "knightly", "the_tower"),
            modern("west_ardougne", "sad_meadow"),
            modern("ardougne_sewers", "the_cellar_dwellers"),
            modern("south_ardougne", "ballad_of_enchantment", "upcoming"),
            modern("legends_guild", "trinity"),
            modern("mourner_tunnels", "fight_or_flight"),
            modern("emirs_arena_music", "duelarena"),
            modern("mage_training_arena", "shine"),
            // Since the February 2026 music rework the three stronghold tracks shuffle everywhere
            // inside the walls, while Gnomeball is confined to the ball field, which is carved out
            // of the stronghold polygon.
            modern("tree_gnome_stronghold", "gnome_king", "gnome_village", "gnome_village2"),
            modern("gnome_ball_field", "gnomeball"),
            modern("yanille", "big_chords", "magic_dance"),
            modern("yanille_chain", "long_ago"),
            modern("yanille_agility_dungeon", "cavern"),
            // "Castle Wars" plays in the lobby and the arena; "Ready for Battle" in the waiting
            // rooms and the tunnels underneath.
            modern("castle_wars", "castlewars"),
            modern("castle_wars_underground", "ready_for_battle"),
            // Everything below was traced from the OSRS wiki music map (Map:Music tracks);
            // the area polygons live in .data/raw-cache/map/area as rectangles generated from
            // that map. Areas are named after the wiki polygon: a location where several tracks
            // shuffle, otherwise the single track that plays there.
            modern("a_dangerous_game", "revenant_slayer_cave"),
            modern("a_desolate_past", "mokhaiotl"),
            modern("a_forgotten_religion", "forthos_dungeon"),
            modern("a_mothers_curse", "toa_boss_kephri"),
            modern("a_taste_of_hope", "ranisduel"),
            modern("a_walk_in_the_woods", "woodland_walk"),
            modern("aldarin", "aldarin", "aldarin_2"),
            modern("alls_fairy_in_love_and_war", "alls_fairy_in_love_n_war"),
            modern("alone", "alone"),
            modern("altar_ego", "altarego"),
            modern("alternative_root", "alternative_root"),
            modern("amascuts_promise", "toa_boss_wardens"),
            modern("ambient_jungle", "ambient_jungle"),
            modern("ape_atoll", "monkey_madness", "anywhere", "island_life"),
            modern("ape_ex_predator", "toa_boss_baba"),
            modern("arachnids_of_vampyrium", "nylocas_combat"),
            modern("arboretum", "arboretum"),
            modern("arcane", "arceuus"),
            modern("are_you_not_entertained", "fortis_colosseum"),
            modern("armadyl_alliance", "armadyl_alliance"),
            modern("armageddon", "armageddon"),
            modern("artistry", "artistry"),
            modern("ascent", "ascent"),
            modern("assault_and_battery", "assault_and_battery"),
            modern("attack_1", "attack1"),
            modern("attack_2", "attack2"),
            modern("attack_3", "attack3"),
            modern("attack_4", "attack4"),
            modern("attack_5", "attack5"),
            modern("attack_6", "attack6"),
            modern("auburn_valley", "auburn_valley_1", "auburn_valley_2"),
            modern("avium_savannah", "avium_savannah", "avium_savannah_2", "avium_savannah_3"),
            modern("aye_car_rum_ba", "aye_car_rum_ba"),
            modern("aztec", "aztec"),
            modern("back_to_life", "back_to_life"),
            modern("background", "background"),
            modern("bandit_camp", "bandit_camp"),
            modern("bandos_battalion", "bandos_battalion"),
            modern("bane", "corporealbeast"),
            modern("barb_wire", "barb_wire"),
            modern("barking_mad", "barking_mad"),
            modern("barren_land", "barrenland"),
            modern("beetle_juice", "beetle_juice"),
            modern("below_the_conch", "great_conch_underground"),
            modern("beneath_cursed_sands", "toa_ambience"),
            modern("beneath_the_kingdom", "kourend_catacombs"),
            modern("beneath_the_stronghold", "beneath_the_stronghold"),
            modern("beyond", "beyond"),
            modern("beyond_the_meadow", "hosidius_outskirts"),
            modern("black_of_knight", "black_of_knight"),
            modern("blistering_barnacles", "blistering_barnacles"),
            modern("bloodbath", "bloodbath"),
            modern("body_parts", "body_parts"),
            modern("bone_dance", "bone_dance"),
            modern("bone_dry", "bone_dry"),
            modern("box_of_delights", "boxofdelights"),
            modern("brew_hoo_hoo", "brew_hoo_hoo"),
            modern("brimhaven", "high_seas", "landlubber", "jollyr"),
            modern("brimstails_scales", "brimstails_scales"),
            modern("bubble_and_squeak", "bubble_and_squeak"),
            modern("burning_desire", "burning_desire"),
            modern("business_as_unusual", "red_rock_island"),
            modern("cabin_fever", "cabin_fever"),
            modern("call_of_the_tlati", "tlati_rainforest"),
            modern("cannonballin", "sailing_combat_02"),
            modern("catacombs_and_tombs", "catacombs_and_tombs"),
            modern("catch_me_if_you_can", "catch_me_if_you_can"),
            modern("cave_background", "cave_background"),
            modern("cave_of_beasts", "cave_of_beasts"),
            modern("cave_of_the_goblins", "cave_of_the_goblins"),
            modern("cavern", "cavern"),
            modern("cellar_song", "cellar_song"),
            modern("chain_of_command", "chain_of_command"),
            modern("chamber", "chamber"),
            modern("chickened_out", "chickened_out"),
            modern("city_of_the_dead", "city_of_the_dead"),
            modern("civitas_illa_fortis", "civitas_illa_fortis", "civitas_illa_fortis_2"),
            modern("clan_wars", "clanwars"),
            modern("clanliness", "clanliness"),
            modern("claustrophobia", "claustrophobia"),
            modern("coil", "coil"),
            modern("colossus_of_the_deep", "dt2_leviathan"),
            modern("competition", "competition"),
            modern("complication", "complication"),
            modern("conspiracy", "conspiracy"),
            modern("corporal_punishment", "corporal_punishment"),
            modern("corridors_of_power", "corridors_of_power"),
            modern("country_jig", "hosidius"),
            modern("creature_cruelty", "creature_cruelty"),
            modern("creeping_vines", "hespori_cave"),
            modern("crystal_castle", "crystal_castle"),
            modern("crystal_sword", "crystal_sword"),
            modern("cursed", "cursed"),
            modern("dagannoth_dawn", "dagannoth_dawn"),
            modern("dance_of_death", "dance_of_death"),
            modern("dance_of_the_undead", "dance_of_the_undead"),
            modern("dangerous_logic", "dangerous_logic"),
            modern("dangerous_road", "dangerous_road"),
            modern("dangerous_way", "dangerous_way"),
            modern("darkly_altared", "darklyaltared"),
            modern("darkmeyer_music", "darkmeyer"),
            modern("darkness_in_the_depths", "darknessinthedepths"),
            modern("davy_jones_locker", "davy_jones_locker"),
            modern("dead_quiet", "dead_quiet"),
            modern("dead_quiet_2", "stagnant", "waterlogged", "dead_quiet"),
            modern("deadlands", "deadlands"),
            modern("deep_down", "deep_down"),
            modern("devils_may_care", "devils_may_care"),
            modern("digsite", "lullaby", "venture"),
            modern("dimension_x", "dimension_x"),
            modern("distant_land", "distant_land"),
            modern("distillery_hilarity", "distillery_hilarity"),
            modern("dogs_of_war", "dogs_of_war"),
            modern("doorways", "doorways"),
            modern("dorgeshuun_city", "dorgeshuun_city"),
            modern("dorgeshuun_deep", "dorgeshuun_deep"),
            modern("down_and_out", "down_and_out"),
            modern("down_below", "down_below"),
            modern("down_by_the_docks", "piscarilius"),
            modern("down_to_earth", "down_to_earth"),
            modern("dragontooth_island", "dragontooth_island"),
            modern("dreamstate", "dreamstate"),
            modern("dunes_of_eternity", "necropolis"),
            modern("dusk_in_yubiusk", "dusk_in_yubiusk"),
            modern("dwarf_theme", "dwarf_theme"),
            modern("dwarven_domain", "lovakengj"),
            modern("dynasty", "dynasty"),
            modern("eagles_peak", "eagle_peak"),
            modern("east_ardougne_music", "baroque", "the_tower", "knightly"),
            modern("elder_wisdom", "great_conch_2"),
            modern("elven_seed", "elven_seed"),
            modern("emissaries_of_twilight", "twilight_temple"),
            modern("emotion", "emotion"),
            modern("escape", "escape"),
            modern("espionage", "espionage"),
            modern("etceteria", "etceteria"),
            modern("everywhere", "everywhere"),
            modern("evil_bobs_island", "evil_bobs_island"),
            modern("expecting", "expecting"),
            modern("expedition", "expedition"),
            modern("exposed", "exposed"),
            modern("fanfare_2", "fanfare2"),
            modern("fanfare_3", "fanfare3"),
            modern("fangs_for_the_memory", "fangs_for_the_memory"),
            modern("far_away", "far_away"),
            modern("farming_guild", "a_farmers_grind", "grow_grow_grow", "hoe_down"),
            modern("fe_fi_fo_fum", "fe_fi_fo_fum"),
            modern("fear_and_loathing", "fear_and_loathing"),
            modern("feldip_hills", "chompy_hunt", "grumpy", "jungle_hunt"),
            modern("fenkenstrains_refrain", "fenkenstrains"),
            modern("find_my_way", "find_my_way"),
            modern("fire_and_brimstone", "fire_and_brimstone"),
            modern("fire_in_the_deep", "olmbattle"),
            modern("food_for_thought", "food_for_thought"),
            modern("forever", "forever"),
            modern("forgettable_melody", "forgettable_melody", "right_on_track"),
            modern("fossilised", "fossil_underground"),
            modern("fremennik_province", "legend", "saga", "borderland"),
            modern("frogland", "frogland"),
            modern("frostbite", "frostbite"),
            modern("fruits_de_mer", "fruits_de_mer"),
            modern("gaol", "gaol"),
            modern("garden_of_autumn", "garden_of_autumn"),
            modern("garden_of_spring", "garden_of_spring"),
            modern("garden_of_summer", "garden_of_summer"),
            modern("garden_of_winter", "garden_of_winter"),
            modern("getting_down_to_business", "getting_down_to_business"),
            modern("gill_bill", "gill_bill"),
            modern("goblin_game", "goblin_game"),
            modern("grotto", "grotto"),
            modern("guardians_of_the_rift", "gotr_minigame"),
            modern("h_a_m_and_seek", "ham_and_seek"),
            modern("h_a_m_attack", "ham_attack"),
            modern("h_a_m_fisted", "ham_fisted"),
            modern("harmony", "harmony", "chef_surprise"),
            modern("harmony_2", "harmony2"),
            modern("haunted_mine", "haunted_mine"),
            modern("have_a_blast", "have_a_blast"),
            modern("have_an_ice_day", "have_an_ice_day"),
            modern("head_to_head", "head_to_head"),
            modern("heart_and_mind", "heart_and_mind"),
            modern("hells_bells", "hells_bells"),
            modern("hemenster", "lasting", "wonderous", "magical_journey"),
            modern("hermit", "hermit"),
            modern("home_sweet_home", "home_sweet_home"),
            modern("horizon", "horizon"),
            modern("iban", "iban"),
            modern("ice_and_fire", "wintertodt"),
            modern("ice_melody", "ice_melody"),
            modern("impetuous", "impetuous"),
            modern("in_between", "in_between"),
            modern("in_the_brine", "in_the_brine"),
            modern("in_the_clink", "in_the_clink"),
            modern("in_the_manor", "in_the_manor"),
            modern("in_the_pits", "in_the_pits"),
            modern("inferno", "inferno"),
            modern("insect_queen", "insect_queen"),
            modern("into_the_abyss", "into_the_abyss"),
            modern("into_the_tombs", "toa_lobby"),
            modern("intrepid", "intrepid"),
            modern("invader", "sire"),
            modern(
                "isafdar",
                "riverside",
                "breeze",
                "elven_mist",
                "meridian",
                "forest",
                "woodland",
            ),
            modern("island_life", "island_life"),
            modern("island_of_the_trolls", "island_of_the_trolls"),
            modern("its_not_over_til", "verzik_ambience", "verzik_combat"),
            modern("itsy_bitsy", "araxyte"),
            modern("jaws_of_gluttony", "toa_boss_zebak"),
            modern("judgement_of_the_depths", "judge_of_yama"),
            modern(
                "karamja",
                "reggae",
                "reggae2",
                "tribal2",
                "jungly1",
                "jungly2",
                "jungly3",
                "tribal",
                "jungle_troubles",
            ),
            modern(
                "karuulm_slayer_dungeon_music",
                "ful_to_the_brim",
                "kanon_of_khalith",
                "way_of_the_wyrm",
            ),
            modern("keldagrim_music", "land_of_the_dwarves", "tale_of_keldagrim"),
            modern(
                "kharidian_desert",
                "scarab",
                "egypt",
                "the_desert",
                "arabian3",
                "desert_voyage",
                "sunburn",
                "desert_heat",
                "sphinx",
            ),
            modern("knightmare", "knightmare"),
            modern("kourend_the_magnificent", "kourendthemagnificent"),
            modern("la_mort", "la_mort"),
            modern("labyrinth", "labyrinth"),
            modern("lagoon", "fossil_underwater"),
            modern("laid_to_rest", "toa_victory"),
            modern("lair", "lair"),
            modern("lair_of_the_basilisk", "basilisk_lair"),
            modern("lament", "lament"),
            modern("lament_for_the_hallowed", "icyene_graveyard"),
            modern("lament_of_meiyerditch", "lament_of_meiyerditch"),
            modern("lamistards_labyrinth", "lamistards_labyrinth"),
            modern("land_down_under", "land_down_under"),
            modern("last_man_standing", "lastmanstanding"),
            modern("lava_is_mine", "fossil_lava_mine"),
            modern("legion", "legion"),
            modern("life_at_sea", "industrial_islands"),
            modern("lighthouse", "lighthouse"),
            modern("little_cave_of_horrors", "little_cave_of_horrors"),
            modern("lonesome", "lonesome"),
            modern("looking_back", "looking_back"),
            modern("lord_of_the_larvae", "maggot_boss"),
            modern("lore_and_order", "lore_and_order"),
            modern("lost_soul", "lost_soul"),
            modern("lost_to_time", "old_one_ruins"),
            modern("lower_depths", "lowerdepths"),
            modern("lucid_dream", "luciddream"),
            modern("lucid_nightmare", "lucidnightmare"),
            modern("lumbering", "weiss_town"),
            modern("lunar_isle", "isle_of_everywhere", "the_lunar_isle"),
            modern("lurking_threats", "dangerous_islands"),
            modern("mad_eadgar", "mad_eadgar"),
            modern("mage_arena", "mage_arena"),
            modern("magic_magic_magic", "magic_magic_magic"),
            modern("major_miner", "major_miner"),
            modern("making_waves", "making_waves"),
            modern("malady", "malady"),
            modern("march_of_the_shayzien", "shayzienmarch"),
            modern("marooned", "marooned"),
            modern("marzipan", "marzipan"),
            modern("masquerade", "masquerade"),
            modern("mausoleum", "mausoleum"),
            modern("maws_jaws_and_claws", "mawsjawsclaws"),
            modern("method_of_madness", "method_of_madness"),
            modern("miles_away", "miles_away"),
            modern("military_life", "shayzien_camp"),
            modern("mind_over_matter", "mind_over_matter"),
            modern("miracle_dance", "miracle_dance"),
            modern("mirage", "mirage"),
            modern("miscellania", "miscellania"),
            modern("mistrock", "mistrock"),
            modern("monarch_waltz", "monarch_waltz"),
            modern("monkey_business", "mm2_kruk"),
            modern("monkey_madness", "monkey_madness"),
            modern("monkey_sadness", "mm2_bunkerlab"),
            modern("monkey_trouble", "mm2_bunkercorridors"),
            modern("monster_melee", "monster_melee"),
            modern("mor_ul_rek", "mor_ul_rek"),
            modern("more_than_meets_the_eye", "muspah_boss"),
            modern("morytania", "morytania"),
            modern("mos_leharmless", "in_the_brine", "lifes_a_beach"),
            modern("mouse_trap", "mouse_trap"),
            modern("musa_point", "sea_shanty", "jungle_island"),
            modern("museum_medley", "museummedley"),
            modern("mutant_medley", "mutant_medley"),
            modern("my_arms_journey", "my_arms_journey"),
            modern("mysterious_lands", "mysterious_islands"),
            modern("mystics_of_nature", "amlodd"),
            modern("mythical", "mythsguild"),
            modern("narnodes_theme", "narnodes"),
            modern("natural", "natural"),
            modern("nether_realm", "karamja_jam", "7th_realm", "pathways", "nether_realm"),
            modern("neverland", "neverland"),
            modern("newbie_farming", "newbie_farming"),
            modern("newbie_melody", "newbie_melody"),
            modern(
                "night_of_the_vampyre",
                "lament_of_meiyerditch",
                "the_last_shanty",
                "night_of_the_vampyre",
            ),
            modern("no_pasaran", "no_pasaran"),
            modern("no_way_out", "no_way_out"),
            modern("nomad", "nomad"),
            modern("norse_code", "norse_code"),
            modern("not_a_moment_of_relief", "arceuus_outskirts"),
            modern("noxious_awakening", "araxxor"),
            modern("null_and_void", "null_and_void"),
            modern("observatory", "soundscape", "serenade", "melodrama"),
            modern("ogre_the_top", "ogre_the_top"),
            modern("oh_rats", "rat_boss"),
            modern("on_the_frontline", "battlefront"),
            modern("on_the_wing", "on_the_wing"),
            modern("on_thin_ice", "zombiedragon"),
            modern("oriental", "oriental"),
            modern("out_at_the_mines", "lovakengj_outskirts"),
            modern("out_of_the_deep", "out_of_the_deep"),
            modern("outpost", "tree_spirits", "neverland", "march"),
            modern("over_the_mountains", "custodia_mountains"),
            modern("over_to_nardah", "over_to_nardah"),
            modern("overpass", "overpass"),
            modern("parade", "parade"),
            modern("path_of_peril", "path_of_peril"),
            modern("pest_control", "pest_control"),
            modern("pharaohs_tomb", "pharaohs_tomb"),
            modern("phasmatys", "phasmatys"),
            modern("pheasant_peasant", "pheasant_peasant"),
            modern("pick_and_shovel", "pick_and_shovel"),
            modern("pinball_wizard", "pinball_wizard"),
            modern("pirates_of_penance", "pirates_of_penance"),
            modern("piscatoris_hunter_area", "joy_of_the_hunt", "on_the_wing"),
            modern("poles_apart", "poles_apart"),
            modern("power_of_the_shadow_realm", "sotetseg_combat"),
            modern("predator_xarpus", "xarpus_ambience", "xarpus_combat"),
            modern("preservation", "fossil_overground_2"),
            modern("preserved", "fossil_overground_1"),
            modern(
                "prifddinas",
                "ithell",
                "dance_of_the_meilyr",
                "city_guardians",
                "faith_of_the_hefin",
                "iowerths_lament",
                "amlodd",
                "crwys",
                "the_tower_of_voices",
                "traehern_toil",
            ),
            modern("prime_time", "prime_time"),
            modern("prospering_fortune", "civitas_illa_fortis_2"),
            modern("quest", "quest"),
            modern("race_against_the_clock", "camdozaal_vault"),
            modern("rat_a_tat_tat", "rat_a_tat_tat"),
            modern("rat_hunt", "rat_hunt"),
            modern("ready_for_the_hunt", "hunter_guild"),
            modern("regal_pomp", "coronation"),
            modern("relics", "dragonkintemple"),
            modern("remnants", "sangvesti"),
            modern("rest_in_peace", "restinpeace"),
            modern("revenants", "wilderness_cave"),
            modern("righteousness", "righteousness"),
            modern("romancing_the_crone", "romancing_the_crone"),
            modern("romper_chomper", "romper_chomper"),
            modern("roots_and_flutes", "roots_and_flutes"),
            modern("rose", "rose"),
            modern("rugged_terrain", "ruggedterrain"),
            modern("ruins_of_isolation", "ullek"),
            modern("rune_essence", "rune_essence"),
            modern("sad_meadow", "sad_meadow"),
            modern("safety_in_numbers", "sourhog"),
            modern("saga", "saga"),
            modern("sands_of_time", "toa_boss_akkha"),
            modern("sarachnis", "sarachnis_lair"),
            modern("sarcophagus", "sarcophagus"),
            modern("sarims_vermin", "sarims_vermin"),
            modern("scape_cave", "scape_cave"),
            modern("scape_main", "scape_main"),
            modern("scar_tissue", "dt2_scar"),
            modern("schools_out", "schools_out"),
            modern("scorpia_dances", "scorpia_dances"),
            modern("sea_shanty_2", "sea_shanty2"),
            modern("secrets_of_the_north", "ghorrock_dungeon"),
            modern("serene", "serene"),
            modern("servants_of_strife", "molch"),
            modern("settlement", "settlement"),
            modern("seventh_realm", "7th_realm"),
            modern("shadowland", "shadowland"),
            modern("sharp_end_of_the_crystal", "iowerth_slayer_dungeon"),
            modern("shining_spirit", "shiningspirit"),
            modern("shipwrecked", "shipwrecked"),
            modern("showdown", "showdown"),
            modern("sigmunds_showdown", "sigmunds_showdown"),
            modern("sign_here", "yama_combat"),
            modern("slice_of_silent_movie", "slice_of_silent_movie"),
            modern("slice_of_station", "slice_of_station"),
            modern("slither_and_thither", "slither_and_thither"),
            modern("slug_a_bug_ball", "slug_a_bug_ball"),
            modern("solitude", "sugadintis_hideout"),
            modern("song_of_the_elves", "warped_library"),
            modern("soul_fall", "soulfall"),
            modern("soul_wars", "soul_wars"),
            modern("spirits_of_the_elid", "spirits_of_elid"),
            modern("spooky", "spooky"),
            modern("spooky_2", "spooky2"),
            modern("spooky_jungle", "spookyjungle"),
            modern("stagnant", "stagnant"),
            modern("stalkers", "stalker_dungeon"),
            modern("stillness", "stillness"),
            modern("stones_of_old", "quetzacalli_gorge"),
            modern("storeroom_shuffle", "storeroom_shuffle"),
            modern("storm_brew", "storm_brew"),
            modern("stranded", "stranded"),
            modern("strange_place", "strange_place"),
            modern("strangled", "dt2_stranglewood"),
            modern("stratosphere", "stratosphere"),
            modern("strength_of_saradomin", "strength_of_saradomin"),
            modern("stuck_in_the_mire", "stuck_in_the_mire"),
            modern("subterranea", "subterranea"),
            modern("superstition", "superstition"),
            modern("suspicious", "suspicious"),
            modern("tears_of_guthix", "tears_of_guthix_music"),
            modern("technology", "technology"),
            modern("teklan", "tal_teklan"),
            modern("tempest", "gargoyleboss"),
            modern("temple", "temple"),
            modern("temple_desecrated", "temple_desecrated"),
            modern("temple_of_light", "temple_of_light"),
            modern("temple_of_the_eye", "temple_of_the_eye"),
            modern("temple_of_tribes", "temple_of_tribes"),
            modern("tempor_of_the_storm", "tempoross"),
            modern("that_sullen_hall", "thatsullenhall"),
            modern("the_ancient_prison", "ancient_prison"),
            modern("the_angels_fury", "the_angels_fury"),
            modern("the_bane_of_ashihama", "nightmare_combat"),
            modern("the_chosen", "the_chosen"),
            modern("the_consortium", "giant_dwarf_meeting"),
            modern("the_curtain_closes", "verzik_defeated"),
            modern("the_depths", "the_depths"),
            modern("the_desolate_isle", "the_desolate_isle"),
            modern("the_desolate_mage", "desolatemage"),
            modern("the_doom", "doom_boss"),
            modern("the_doors_of_dinh", "wasteland"),
            modern("the_enchanter", "the_enchanter", "roll_the_bones", "golden_touch"),
            modern("the_enclave", "enclave"),
            modern("the_everlasting_slumber", "slepe_dungeon"),
            modern("the_fallen_empire", "dt2_lassar"),
            modern("the_far_side", "the_far_side"),
            modern("the_feathered_serpent", "hueycoatl"),
            modern("the_fires_of_lletya", "lletyas_destruction"),
            modern("the_forests_of_shayzien", "shayzien_outskirts"),
            modern("the_forgotten_tomb", "mehhars_tomb"),
            modern("the_forlorn_homestead", "forlornhomestead"),
            modern("the_forsaken", "dragonkintheme"),
            modern("the_forsaken_tower", "forsaken_tower"),
            modern("the_foundry", "giants_foundry"),
            modern("the_fragment", "the_dark_fragment"),
            modern("the_galleon", "the_galleon"),
            modern("the_gauntlet", "gauntlet_minigame"),
            modern("the_genie", "the_genie"),
            modern("the_golem", "the_golem"),
            modern("the_great_conch", "great_conch_2", "great_conch"),
            modern("the_guardian_of_tapoyauik", "amoxliatl"),
            modern("the_guidance_of_ralos", "ralos_rise"),
            modern("the_houses_of_kourend", "kourend_houses"),
            modern("the_longramble_scramble", "longramble_scramble"),
            modern("the_lost_melody", "the_lost_melody"),
            modern("the_lost_tribe", "the_lost_tribe"),
            modern("the_mad_mole", "the_mad_mole"),
            modern("the_maidens_anger", "maiden_combat"),
            modern("the_maze", "melzars_maze"),
            modern("the_militia", "shayzien"),
            modern("the_mollusc_menace", "the_mollusc_menace"),
            modern("the_monsters_below", "the_monsters_below"),
            modern("the_moons_of_ruin", "perilous_moons"),
            modern("the_navigator", "the_navigator"),
            modern("the_nightmare_continues", "pestilent_bloat_combat"),
            modern("the_north", "the_north"),
            modern("the_other_side", "the_other_side"),
            modern("the_pandemonium", "honkytonky_sea_shanty2", "yo_ho_ho"),
            modern("the_part_where_you_die", "xamphur"),
            modern("the_plundered_tomb", "the_plundered_tomb"),
            modern("the_power_of_tears", "the_power_of_tears"),
            modern("the_quizmaster", "the_quizmaster"),
            modern("the_rogues_den", "the_rogues_den"),
            modern("the_route_of_all_evil", "the_route_of_all_evil"),
            modern("the_ruins_of_camdozaal", "camdozaal_ruins"),
            modern("the_shadow", "the_shadow"),
            modern("the_slayer", "the_slayer"),
            modern("the_sound_of_guthix", "the_sound_of_guthix"),
            modern("the_spurned_demon", "zalcano_combat"),
            modern("the_talkasti_people", "kastori"),
            modern("the_terrible_tower", "the_terrible_tower"),
            modern("the_terrible_tunnels", "terrible_tunnels"),
            modern("the_tortugan_way", "great_conch_2", "great_conch"),
            modern("the_vault", "dt2_vault"),
            modern("the_waiting_game", "waiting_game"),
            modern("the_walking_dead", "shayziencrypt"),
            modern("theme", "theme"),
            modern("thrall_of_the_serpent", "thrall_of_the_serpent"),
            modern("throne_of_the_demon", "throne_of_the_demon", "forgotten"),
            modern("time_out", "time_out"),
            modern("time_to_mine", "time_to_mine"),
            modern("tiptoe", "tiptoe"),
            modern("title_fight", "title_fight"),
            modern("tomb_raider", "tomb_raider"),
            modern("tomorrow", "tomorrow"),
            modern("too_many_cooks", "too_many_cooks"),
            modern("trahaearn_toil", "traehern_toil"),
            modern("tranquillity", "calm_islands"),
            modern("trawler", "trawler"),
            modern("trawler_minor", "trawler_minor"),
            modern("tribal_background", "tribal_background"),
            modern("trinity", "trinity"),
            modern("troll_country", "tremble", "sojourn", "contest"),
            modern("troll_shuffle", "trollshuffle"),
            modern("trouble_brewing", "trouble_brewing"),
            modern("troubled_waters", "troubled_waters"),
            modern("twilight", "twilight"),
            modern("tzhaar", "tzhaar"),
            modern("undead_dungeon", "undead_dungeon"),
            modern("under_the_mountain", "cam_torum"),
            modern("underground", "underground"),
            modern("underground_pass", "upass"),
            modern("understanding", "understanding"),
            modern("untouchable", "untouchable"),
            modern("unturned_stones", "dt2_digsite"),
            modern("upcoming", "upcoming"),
            modern("upir_likhyi", "upir_likhyi"),
            modern("upper_depths", "upperdepths"),
            modern("varlamores_sunset", "sunset_coast"),
            modern("venture_2", "venture2"),
            modern("victory_is_mine", "victory_is_mine"),
            modern("village", "village"),
            modern("volcanic_vikings", "volcanic_vikings"),
            modern("voodoo_cult", "voodoo_cult"),
            modern("waking_dream", "waking_dream"),
            modern("warrior", "warrior"),
            modern("warriors_guild", "warriors_guild"),
            modern("waste_defaced", "waste_defaced"),
            modern("watch_your_step", "hallowed_sepulchre"),
            modern("waterfall", "waterfall"),
            modern("waterlogged", "waterlogged"),
            modern("way_of_the_enchanter", "way_of_the_enchanter"),
            modern("wayward", "wayward"),
            modern("we_are_the_fairies", "we_are_the_fairies"),
            modern("welcome_to_the_theatre", "thetheatre"),
            modern("well_hallowed_air", "hallowed_sepulchre_lobby"),
            modern("well_of_voyage", "well_of_voyage"),
            modern("what_happens_below", "warrens"),
            modern("what_the_shell", "gryphon_boss"),
            modern("where_eagles_lair", "where_eagles_lair"),
            modern("whispering_wind", "hailstorm_mountains"),
            modern(
                "wilderness_2",
                "venomous",
                "underground",
                "wild_isle",
                "wildwood",
                "moody",
                "witching",
                "wonder",
                "deep_wildy",
                "wilderness2",
                "wilderness3",
                "close_quarters",
                "dark",
                "inspiration",
                "shining",
                "forbidden",
                "army_of_darkness",
                "crystal_sword",
                "dangerous",
                "troubled",
                "regal",
                "scape_sad",
                "scape_wild",
                "faithless",
                "dead_can_dance",
                "everlasting_fire",
                "undercurrent",
                "wild_side",
                "wilderness",
            ),
            modern("wings_of_madness", "mad_angel_boss"),
            modern("wonder", "wonder"),
            modern("work_work_work", "work_work_work"),
            modern("wrath_and_ruin", "wrath_and_ruin"),
            modern("xenophobe", "xenophobe"),
            modern("zamorak_zoo", "zamorak_zoo"),
            modern("zaniks_theme", "zaniks_theme"),
            modern("zealot", "zealot"),
            modern("zogre_dance", "zogre_dance"),
            modern("zombiism", "zombiism"),
        )

    fun musicModern() =
        dbTable("dbtable.music_modern", serverOnly = true) {
            column("area", 0, VarType.STRING)
            column("tracks", 1, VarType.DBROW)
            column("auto_script", 2, VarType.BOOLEAN)

            for (entry in MODERN_AREAS) {
                row(entry.row) {
                    column(0, entry.area)
                    columnRSCM(1, *entry.tracks.toTypedArray())
                    column(2, true)
                }
            }
        }

    fun musicClassic() =
        dbTable("dbtable.music_classic", serverOnly = true) {
            column("area", 0, VarType.AREA)
            column("track", 1, VarType.DBROW)
            column("auto_script", 2, VarType.BOOLEAN)
        }
}
