package dev.openrune.tables.consumables.food

// TODO: Add Cavefish and Tetra when their cache item options become edible.
internal enum class FoodData(
    val row: String,
    val items: List<String>,
    val heal: Int,
    val combo: Boolean = false,
    val effect: String = "",
    val overheal: Boolean = false,
    val eatDelay: List<Int> = emptyList(),
    val combatDelay: List<Int> = emptyList(),
) {
    SHRIMP(
        row = "dbrow.shrimp",
        items = listOf("obj.shrimp"),
        heal = 3,
    ),
    ANCHOVIES(
        row = "dbrow.anchovies",
        items = listOf("obj.anchovies"),
        heal = 1,
    ),
    SARDINE(
        row = "dbrow.sardine",
        items = listOf("obj.sardine"),
        heal = 4,
    ),
    HERRING(
        row = "dbrow.herring",
        items = listOf("obj.herring"),
        heal = 5,
    ),
    MACKEREL(
        row = "dbrow.mackerel",
        items = listOf("obj.mackerel"),
        heal = 6,
    ),
    COD(
        row = "dbrow.cod",
        items = listOf("obj.cod"),
        heal = 7,
    ),
    TROUT(
        row = "dbrow.trout",
        items = listOf("obj.trout"),
        heal = 7,
    ),
    PIKE(
        row = "dbrow.pike",
        items = listOf("obj.pike"),
        heal = 8,
    ),
    SALMON(
        row = "dbrow.salmon",
        items = listOf("obj.salmon"),
        heal = 9,
    ),
    TUNA(
        row = "dbrow.tuna",
        items = listOf("obj.tuna"),
        heal = 10,
    ),
    CAVE_EEL(
        row = "dbrow.cave_eel",
        items = listOf("obj.cave_eel"),
        heal = 10,
        effect = "cave_eel",
    ),
    LAVA_EEL(
        row = "dbrow.lava_eel",
        items = listOf("obj.lava_eel"),
        heal = 11,
    ),
    LOBSTER(
        row = "dbrow.lobster",
        items = listOf("obj.lobster"),
        heal = 12,
    ),
    BASS(
        row = "dbrow.bass",
        items = listOf("obj.bass"),
        heal = 13,
    ),
    SWORDFISH(
        row = "dbrow.swordfish",
        items = listOf("obj.swordfish"),
        heal = 14,
    ),
    SWORDTIP_SQUID(
        row = "dbrow.swordtip_squid",
        items = listOf("obj.swordtip_squid"),
        heal = 15,
    ),
    IXCOZTIC_WHITE(
        row = "dbrow.ixcoztic_white",
        items = listOf("obj.ixcoztic_white"),
        heal = 16,
        effect = "ixcoztic_white",
    ),
    MONKFISH(
        row = "dbrow.monkfish",
        items = listOf("obj.monkfish"),
        heal = 16,
    ),
    JUMBO_SQUID(
        row = "dbrow.jumbo_squid",
        items = listOf("obj.jumbo_squid"),
        heal = 17,
    ),
    GIANT_KRILL(
        row = "dbrow.giant_krill",
        items = listOf("obj.giant_krill"),
        heal = 17,
    ),
    HADDOCK(
        row = "dbrow.haddock",
        items = listOf("obj.haddock"),
        heal = 18,
        effect = "haddock",
        overheal = true,
    ),
    YELLOWFIN(
        row = "dbrow.yellowfin",
        items = listOf("obj.yellowfin"),
        heal = 19,
        effect = "yellowfin",
    ),
    SHARK(
        row = "dbrow.shark",
        items = listOf("obj.shark"),
        heal = 20,
    ),
    HALIBUT(
        row = "dbrow.halibut",
        items = listOf("obj.halibut"),
        heal = 20,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    SEA_TURTLE(
        row = "dbrow.sea_turtle",
        items = listOf("obj.seaturtle"),
        heal = 21,
    ),
    MANTA_RAY(
        row = "dbrow.manta_ray",
        items = listOf("obj.mantaray"),
        heal = 22,
    ),
    DARK_CRAB(
        row = "dbrow.dark_crab",
        items = listOf("obj.dark_crab"),
        heal = 22,
    ),
    BLUEFIN(
        row = "dbrow.bluefin",
        items = listOf("obj.bluefin"),
        heal = 22,
        effect = "bluefin",
    ),
    MARLIN(
        row = "dbrow.marlin",
        items = listOf("obj.marlin"),
        heal = 24,
    ),
    ANGLERFISH(
        row = "dbrow.anglerfish",
        items = listOf("obj.anglerfish"),
        heal = -1,
        overheal = true,
    ),
    BREAD(
        row = "dbrow.bread",
        items = listOf("obj.bread"),
        heal = 5,
    ),
    PEACH(
        row = "dbrow.peach",
        items = listOf("obj.peach"),
        heal = 8,
    ),
    ONION(
        row = "dbrow.onion",
        items = listOf("obj.onion"),
        heal = 1,
    ),
    POTATO(
        row = "dbrow.potato",
        items = listOf("obj.potato"),
        heal = 1,
    ),
    CABBAGE(
        row = "dbrow.cabbage",
        items = listOf("obj.cabbage"),
        heal = 1,
    ),
    BANANA(
        row = "dbrow.banana",
        items = listOf("obj.banana"),
        heal = 2,
    ),
    TOMATO(
        row = "dbrow.tomato",
        items = listOf("obj.tomato"),
        heal = 2,
    ),
    CHEESE(
        row = "dbrow.cheese",
        items = listOf("obj.cheese"),
        heal = 2,
    ),
    POT_OF_CREAM(
        row = "dbrow.pot_of_cream",
        items = listOf("obj.pot_of_cream"),
        heal = 1,
    ),
    SLICED_BANANA(
        row = "dbrow.sliced_banana",
        items = listOf("obj.tbwt_sliced_banana"),
        heal = 2,
    ),
    ORANGE_CHUNKS(
        row = "dbrow.orange_chunks",
        items = listOf("obj.orange_chunks"),
        heal = 2,
    ),
    ORANGE_SLICES(
        row = "dbrow.orange_slices",
        items = listOf("obj.orange_slices"),
        heal = 2,
    ),
    PINEAPPLE_CHUNKS(
        row = "dbrow.pineapple_chunks",
        items = listOf("obj.pineapple_chunks"),
        heal = 2,
    ),
    PINEAPPLE_RING(
        row = "dbrow.pineapple_ring",
        items = listOf("obj.pineapple_ring"),
        heal = 2,
    ),
    LEMON_CHUNKS(
        row = "dbrow.lemon_chunks",
        items = listOf("obj.lemon_chunks"),
        heal = 2,
    ),
    LEMON_SLICES(
        row = "dbrow.lemon_slices",
        items = listOf("obj.lemon_slices"),
        heal = 2,
    ),
    LIME_CHUNKS(
        row = "dbrow.lime_chunks",
        items = listOf("obj.lime_chunks"),
        heal = 2,
    ),
    LIME_SLICES(
        row = "dbrow.lime_slices",
        items = listOf("obj.lime_slices"),
        heal = 2,
    ),
    KING_WORM(
        row = "dbrow.king_worm",
        items = listOf("obj.king_worm"),
        heal = 2,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    EQUA_LEAVES(
        row = "dbrow.equa_leaves",
        items = listOf("obj.equa_leaves"),
        heal = 1,
    ),
    LEMON(
        row = "dbrow.lemon",
        items = listOf("obj.lemon"),
        heal = 2,
    ),
    ORANGE(
        row = "dbrow.orange",
        items = listOf("obj.orange"),
        heal = 2,
    ),
    LIME(
        row = "dbrow.lime",
        items = listOf("obj.lime"),
        heal = 2,
    ),
    PINEAPPLE(
        row = "dbrow.pineapple",
        items = listOf("obj.pineapple"),
        heal = 2,
    ),
    DWELLBERRIES(
        row = "dbrow.dwellberries",
        items = listOf("obj.dwellberries"),
        heal = 2,
    ),
    JANGERBERRIES(
        row = "dbrow.jangerberries",
        items = listOf("obj.jangerberries"),
        heal = 2,
        effect = "jangerberries",
    ),
    CAERULA_BERRIES(
        row = "dbrow.caerula_berries",
        items = listOf("obj.caerula_berries"),
        heal = 2,
    ),
    STRAWBERRY(
        row = "dbrow.strawberry",
        items = listOf("obj.strawberry"),
        heal = 5,
        effect = "strawberry",
    ),
    WATERMELON_SLICE(
        row = "dbrow.watermelon_slice",
        items = listOf("obj.watermelon_slice"),
        heal = 2,
        effect = "watermelon_slice",
    ),
    PAPAYA_FRUIT(
        row = "dbrow.papaya_fruit",
        items = listOf("obj.papaya"),
        heal = 8,
        effect = "papaya_fruit",
    ),
    DRAGONFRUIT(
        row = "dbrow.dragonfruit",
        items = listOf("obj.dragonfruit"),
        heal = 10,
    ),
    CHOCOLATE_BAR(
        row = "dbrow.chocolate_bar",
        items = listOf("obj.chocolate_bar"),
        heal = 3,
    ),
    EDIBLE_SEAWEED(
        row = "dbrow.edible_seaweed",
        items = listOf("obj.edible_seaweed"),
        heal = 4,
    ),
    MAGIC_CABBAGE(
        row = "dbrow.magic_cabbage",
        items = listOf("obj.magic_cabbage"),
        heal = 1,
        effect = "magic_cabbage",
    ),
    CUP_OF_TEA(
        row = "dbrow.cup_of_tea",
        items = listOf(
            "obj.cup_of_tea",
            "obj.cup_empty",
        ),
        heal = 3,
        effect = "cup_of_tea",
    ),
    WHITE_TREE_FRUIT(
        row = "dbrow.white_tree_fruit",
        items = listOf("obj.garden_white_tree_fruit"),
        heal = 3,
        effect = "white_tree_fruit",
    ),
    STRANGE_FRUIT(
        row = "dbrow.strange_fruit",
        items = listOf("obj.macro_triffidfruit"),
        heal = 0,
        effect = "strange_fruit",
    ),
    MINT_CAKE(
        row = "dbrow.mint_cake",
        items = listOf("obj.aluft_gnome_mint_cake"),
        heal = 0,
        effect = "mint_cake",
    ),
    RARE_TUBER(
        row = "dbrow.rare_tuber",
        items = listOf("obj.village_rare_tuber"),
        heal = 12,
        effect = "rare_tuber",
    ),
    TBONE_STEAK(
        row = "dbrow.tbone_steak",
        items = listOf("obj.tbone_steak"),
        heal = 9,
        effect = "tbone_steak",
    ),
    COOKED_CHICKEN(
        row = "dbrow.cooked_chicken",
        items = listOf("obj.cooked_chicken"),
        heal = 3,
    ),
    COOKED_MEAT(
        row = "dbrow.cooked_meat",
        items = listOf("obj.cooked_meat"),
        heal = 3,
    ),
    COOKED_UGTHANKI_MEAT(
        row = "dbrow.cooked_ugthanki_meat",
        items = listOf("obj.cooked_ugthanki_meat"),
        heal = 3,
    ),
    UGTHANKI_KEBAB(
        row = "dbrow.ugthanki_kebab",
        items = listOf("obj.ugthanki_kebab"),
        heal = 19,
    ),
    KEBAB(
        row = "dbrow.kebab",
        items = listOf("obj.kebab"),
        heal = 3,
        effect = "kebab",
    ),
    LOCUST_MEAT(
        row = "dbrow.locust_meat",
        items = listOf("obj.locust_meat"),
        heal = 3,
    ),
    ROE(
        row = "dbrow.roe",
        items = listOf("obj.brut_roe"),
        heal = 3,
    ),
    STEW(
        row = "dbrow.stew",
        items = listOf(
            "obj.stew",
            "obj.bowl_empty",
        ),
        heal = 11,
    ),
    SPICY_STEW(
        row = "dbrow.spicy_stew",
        items = listOf("obj.hundred_dave_stew"),
        heal = 11,
        effect = "spicy_stew",
    ),
    COOKED_RABBIT(
        row = "dbrow.cooked_rabbit",
        items = listOf("obj.cooked_rabbit"),
        heal = 5,
    ),
    COOKED_MYSTERY_MEAT(
        row = "dbrow.cooked_mystery_meat",
        items = listOf("obj.cooked_mystery_meat"),
        heal = 5,
    ),
    CAVIAR(
        row = "dbrow.caviar",
        items = listOf("obj.brut_caviar"),
        heal = 5,
    ),
    BAGUETTE(
        row = "dbrow.baguette",
        items = listOf("obj.baguette"),
        heal = 6,
    ),
    GIANT_FROG_LEGS(
        row = "dbrow.giant_frog_legs",
        items = listOf("obj.giant_frog_legs"),
        heal = 6,
    ),
    GIANT_CARP(
        row = "dbrow.giant_carp",
        items = listOf("obj.giant_carp"),
        heal = 6,
    ),
    GIANT_FROGSPAWN(
        row = "dbrow.giant_frogspawn",
        items = listOf("obj.giant_frogspawn"),
        heal = 3,
        effect = "giant_frogspawn",
    ),
    COOKED_SLIMY_EEL(
        row = "dbrow.cooked_slimy_eel",
        items = listOf("obj.mort_slimey_eel_cooked"),
        heal = 6,
        effect = "cooked_slimy_eel",
    ),
    COOKED_FISHCAKE(
        row = "dbrow.cooked_fishcake",
        items = listOf("obj.hundred_pirate_fishcake"),
        heal = 11,
    ),
    COOKED_CHOMPY(
        row = "dbrow.cooked_chompy",
        items = listOf("obj.cooked_chompy"),
        heal = 10,
    ),
    CHOC_ICE(
        row = "dbrow.choc_ice",
        items = listOf("obj.elid_choc_ice"),
        heal = 7,
    ),
    PUMPKIN(
        row = "dbrow.pumpkin",
        items = listOf("obj.pumpkin"),
        heal = 14,
    ),
    EASTER_EGG(
        row = "dbrow.easter_egg",
        items = listOf("obj.easter_egg"),
        heal = 14,
    ),
    COOKED_OOMLIE(
        row = "dbrow.cooked_oomlie",
        items = listOf("obj.cooked_oomlie"),
        heal = 14,
    ),
    COOKED_SWEETCORN(
        row = "dbrow.cooked_sweetcorn",
        items = listOf("obj.sweetcorn_cooked"),
        heal = 10,
        effect = "cooked_sweetcorn",
    ),
    BOWL_OF_SWEETCORN(
        row = "dbrow.bowl_of_sweetcorn",
        items = listOf(
            "obj.bowl_sweetcorn",
            "obj.bowl_empty",
        ),
        heal = 10,
        effect = "cooked_sweetcorn",
    ),
    ROAST_BIRD_MEAT(
        row = "dbrow.roast_bird_meat",
        items = listOf("obj.spit_roasted_bird_meat"),
        heal = 6,
    ),
    ROAST_RABBIT(
        row = "dbrow.roast_rabbit",
        items = listOf("obj.spit_roasted_rabbit_meat"),
        heal = 7,
    ),
    ROAST_BEAST_MEAT(
        row = "dbrow.roast_beast_meat",
        items = listOf("obj.spit_roasted_beast_meat"),
        heal = 8,
    ),
    THIN_SNAIL_MEAT(
        row = "dbrow.thin_snail_meat",
        items = listOf("obj.snail_corpse_cooked1"),
        heal = 5,
        effect = "thin_snail_meat",
    ),
    LEAN_SNAIL_MEAT(
        row = "dbrow.lean_snail_meat",
        items = listOf("obj.snail_corpse_cooked2"),
        heal = 6,
        effect = "lean_snail_meat",
    ),
    FAT_SNAIL_MEAT(
        row = "dbrow.fat_snail_meat",
        items = listOf("obj.snail_corpse_cooked3"),
        heal = 8,
        effect = "fat_snail_meat",
    ),
    SPIDER_ON_STICK(
        row = "dbrow.spider_on_stick",
        items = listOf("obj.tbw_spider_on_stick_cooked"),
        heal = 7,
        effect = "spider_on_stick",
    ),
    SPIDER_ON_SHAFT(
        row = "dbrow.spider_on_shaft",
        items = listOf("obj.tbw_spider_on_shaft_cooked"),
        heal = 7,
        effect = "spider_on_shaft",
    ),
    COOKED_JUBBLY(
        row = "dbrow.cooked_jubbly",
        items = listOf("obj.100_jubbly_meat_cooked"),
        heal = 15,
    ),
    COOKED_GIANT_CRAB_MEAT(
        row = "dbrow.cooked_giant_crab_meat",
        items = listOf(
            "obj.hundred_pirate_giant_crab_meat_5",
            "obj.hundred_pirate_giant_crab_meat_4",
            "obj.hundred_pirate_giant_crab_meat_3",
            "obj.hundred_pirate_giant_crab_meat_2",
            "obj.hundred_pirate_giant_crab_meat_1",
        ),
        heal = 2,
        eatDelay = listOf(
            2,
            2,
            2,
            2,
            2,
        ),
        combatDelay = listOf(
            2,
            2,
            2,
            2,
            2,
        ),
    ),
    COOKED_WILD_KEBBIT(
        row = "dbrow.cooked_wild_kebbit",
        items = listOf("obj.wildkebbit_cooked"),
        heal = 4,
        effect = "cooked_wild_kebbit",
    ),
    COOKED_LARUPIA(
        row = "dbrow.cooked_larupia",
        items = listOf("obj.larupia_cooked"),
        heal = 6,
        effect = "cooked_larupia",
    ),
    COOKED_BARB_TAILED_KEBBIT(
        row = "dbrow.cooked_barb_tailed_kebbit",
        items = listOf("obj.barbkebbit_cooked"),
        heal = 7,
        effect = "cooked_barb_tailed_kebbit",
    ),
    COOKED_GRAAHK(
        row = "dbrow.cooked_graahk",
        items = listOf("obj.graahk_cooked"),
        heal = 8,
        effect = "cooked_graahk",
    ),
    COOKED_KYATT(
        row = "dbrow.cooked_kyatt",
        items = listOf("obj.kyatt_cooked"),
        heal = 9,
        effect = "cooked_kyatt",
    ),
    COOKED_DASHING_KEBBIT(
        row = "dbrow.cooked_dashing_kebbit",
        items = listOf("obj.dashingkebbit_cooked"),
        heal = 13,
        effect = "cooked_dashing_kebbit",
    ),
    COOKED_FENNEC_FOX(
        row = "dbrow.cooked_fennec_fox",
        items = listOf("obj.fennecfox_cooked"),
        heal = 11,
        effect = "cooked_fennec_fox",
    ),
    COOKED_SUNLIGHT_ANTELOPE(
        row = "dbrow.cooked_sunlight_antelope",
        items = listOf("obj.antelopesun_cooked"),
        heal = 12,
        effect = "cooked_sunlight_antelope",
    ),
    COOKED_MOONLIGHT_ANTELOPE(
        row = "dbrow.cooked_moonlight_antelope",
        items = listOf("obj.antelopemoon_cooked"),
        heal = 14,
        effect = "cooked_moonlight_antelope",
    ),
    POTATO_WITH_CHEESE(
        row = "dbrow.potato_with_cheese",
        items = listOf("obj.potato_cheese"),
        heal = 16,
    ),
    TUNA_POTATO(
        row = "dbrow.tuna_potato",
        items = listOf("obj.potato_tuna+sweetcorn"),
        heal = 22,
    ),
    CURRY(
        row = "dbrow.curry",
        items = listOf(
            "obj.curry",
            "obj.bowl_empty",
        ),
        heal = 19,
    ),
    BAKED_POTATO(
        row = "dbrow.baked_potato",
        items = listOf("obj.potato_baked"),
        heal = 4,
    ),
    POTATO_WITH_BUTTER(
        row = "dbrow.potato_with_butter",
        items = listOf("obj.potato_butter"),
        heal = 14,
    ),
    CHILLI_POTATO(
        row = "dbrow.chilli_potato",
        items = listOf("obj.potato_chilli+carne"),
        heal = 14,
    ),
    EGG_POTATO(
        row = "dbrow.egg_potato",
        items = listOf("obj.potato_egg+tomato"),
        heal = 16,
    ),
    MUSHROOM_POTATO(
        row = "dbrow.mushroom_potato",
        items = listOf("obj.potato_mushroom+onion"),
        heal = 20,
    ),
    BOWL_OF_ONION(
        row = "dbrow.bowl_of_onion",
        items = listOf(
            "obj.bowl_onion",
            "obj.bowl_empty",
        ),
        heal = 1,
    ),
    BOWL_OF_TOMATO(
        row = "dbrow.bowl_of_tomato",
        items = listOf(
            "obj.bowl_tomato",
            "obj.bowl_empty",
        ),
        heal = 2,
    ),
    BOWL_OF_CHILLI(
        row = "dbrow.bowl_of_chilli",
        items = listOf(
            "obj.bowl_chilli",
            "obj.bowl_empty",
        ),
        heal = 2,
    ),
    BOWL_OF_MEAT(
        row = "dbrow.bowl_of_meat",
        items = listOf(
            "obj.bowl_carne",
            "obj.bowl_empty",
        ),
        heal = 2,
    ),
    BOWL_OF_SPICY_TOMATO(
        row = "dbrow.bowl_of_spicy_tomato",
        items = listOf(
            "obj.bowl_spicytomato",
            "obj.bowl_empty",
        ),
        heal = 2,
    ),
    ONION_AND_TOMATO(
        row = "dbrow.onion_and_tomato",
        items = listOf(
            "obj.bowl_oniontomato",
            "obj.bowl_empty",
        ),
        heal = 3,
    ),
    SPICY_MEAT(
        row = "dbrow.spicy_meat",
        items = listOf(
            "obj.bowl_spicymeat",
            "obj.bowl_empty",
        ),
        heal = 3,
    ),
    SCRAMBLED_EGG_BOWL(
        row = "dbrow.scrambled_egg_bowl",
        items = listOf(
            "obj.bowl_egg_scrambled",
            "obj.bowl_empty",
        ),
        heal = 5,
    ),
    FRIED_ONION(
        row = "dbrow.fried_onion",
        items = listOf(
            "obj.bowl_onion_fried",
            "obj.bowl_empty",
        ),
        heal = 5,
    ),
    BOWL_OF_CHILLI_CON_CARNE(
        row = "dbrow.bowl_of_chilli_con_carne",
        items = listOf(
            "obj.bowl_chilli+carne",
            "obj.bowl_empty",
        ),
        heal = 5,
    ),
    EGG_AND_TOMATO(
        row = "dbrow.egg_and_tomato",
        items = listOf(
            "obj.bowl_egg+tomato",
            "obj.bowl_empty",
        ),
        heal = 8,
    ),
    MUSHROOM_AND_ONION(
        row = "dbrow.mushroom_and_onion",
        items = listOf(
            "obj.bowl_mushroom+onion",
            "obj.bowl_empty",
        ),
        heal = 11,
    ),
    TUNA_AND_CORN(
        row = "dbrow.tuna_and_corn",
        items = listOf(
            "obj.bowl_tuna+sweetcorn",
            "obj.bowl_empty",
        ),
        heal = 13,
    ),
    BAT_SHISH(
        row = "dbrow.bat_shish",
        items = listOf("obj.dorgesh_bat_shish"),
        heal = 2,
    ),
    GREEN_GLOOP_SOUP(
        row = "dbrow.green_gloop_soup",
        items = listOf("obj.dorgesh_green_gloop_soup"),
        heal = 2,
    ),
    FROG_SPAWN_GUMBO(
        row = "dbrow.frog_spawn_gumbo",
        items = listOf("obj.dorgesh_frog_spawn_gumbo"),
        heal = 3,
    ),
    FRIED_MUSHROOMS(
        row = "dbrow.fried_mushrooms",
        items = listOf(
            "obj.bowl_mushroom_fried",
            "obj.bowl_empty",
        ),
        heal = 5,
    ),
    SAUTEED_MUSHROOMS(
        row = "dbrow.sauteed_mushrooms",
        items = listOf("obj.dorgesh_sauteed_mushrooms"),
        heal = 6,
    ),
    CAVE_EEL_SUSHI(
        row = "dbrow.cave_eel_sushi",
        items = listOf("obj.dorgesh_cave_eel_sushi"),
        heal = 7,
    ),
    FROG_BURGER(
        row = "dbrow.frog_burger",
        items = listOf("obj.dorgesh_frog_burger"),
        heal = 6,
    ),
    RED_CRAB_MEAT(
        row = "dbrow.red_crab_meat",
        items = listOf("obj.red_crab_meat"),
        heal = 8,
    ),
    BLUE_CRAB_MEAT(
        row = "dbrow.blue_crab_meat",
        items = listOf("obj.blue_crab_meat"),
        heal = 14,
    ),
    RAINBOW_CRAB_MEAT(
        row = "dbrow.rainbow_crab_meat",
        items = listOf("obj.rainbow_crab_meat"),
        heal = 19,
    ),
    JUG_OF_WINE(
        row = "dbrow.jug_of_wine",
        items = listOf("obj.jug_wine"),
        heal = 11,
        effect = "jug_of_wine",
    ),
    BEER(
        row = "dbrow.beer",
        items = listOf(
            "obj.beer",
            "obj.beer_glass",
        ),
        heal = 1,
        effect = "beer",
    ),
    ASGARNIAN_ALE(
        row = "dbrow.asgarnian_ale",
        items = listOf(
            "obj.asgarnian_ale",
            "obj.beer_glass",
        ),
        heal = 1,
        effect = "asgarnian_ale",
    ),
    WIZARDS_MIND_BOMB(
        row = "dbrow.wizards_mind_bomb",
        items = listOf(
            "obj.wizards_mind_bomb",
            "obj.beer_glass",
        ),
        heal = 1,
        effect = "wizards_mind_bomb",
    ),
    GREENMANS_ALE(
        row = "dbrow.greenmans_ale",
        items = listOf(
            "obj.greenmans_ale",
            "obj.beer_glass",
        ),
        heal = 1,
        effect = "greenmans_ale",
    ),
    DRAGON_BITTER(
        row = "dbrow.dragon_bitter",
        items = listOf(
            "obj.dragon_bitter",
            "obj.beer_glass",
        ),
        heal = 1,
        effect = "dragon_bitter",
    ),
    DWARVEN_STOUT(
        row = "dbrow.dwarven_stout",
        items = listOf(
            "obj.dwarven_stout",
            "obj.beer_glass",
        ),
        heal = 1,
        effect = "dwarven_stout",
    ),
    CIDER(
        row = "dbrow.cider",
        items = listOf(
            "obj.cider",
            "obj.beer_glass",
        ),
        heal = 1,
        effect = "cider",
    ),
    AXEMANS_FOLLY(
        row = "dbrow.axemans_folly",
        items = listOf(
            "obj.axemans_folly",
            "obj.beer_glass",
        ),
        heal = 1,
        effect = "axemans_folly",
    ),
    CHEFS_DELIGHT(
        row = "dbrow.chefs_delight",
        items = listOf(
            "obj.chefs_delight",
            "obj.beer_glass",
        ),
        heal = 1,
        effect = "chefs_delight",
    ),
    SLAYERS_RESPITE(
        row = "dbrow.slayers_respite",
        items = listOf(
            "obj.slayers_respite",
            "obj.beer_glass",
        ),
        heal = 1,
        effect = "slayers_respite",
    ),
    GROG(
        row = "dbrow.grog",
        items = listOf("obj.grog"),
        heal = 3,
        effect = "grog",
    ),
    VODKA(
        row = "dbrow.vodka",
        items = listOf("obj.vodka"),
        heal = 5,
        effect = "vodka",
    ),
    WHISKY(
        row = "dbrow.whisky",
        items = listOf("obj.whisky"),
        heal = 5,
        effect = "whisky",
    ),
    GIN(
        row = "dbrow.gin",
        items = listOf("obj.gin"),
        heal = 5,
        effect = "gin",
    ),
    BRANDY(
        row = "dbrow.brandy",
        items = listOf("obj.brandy"),
        heal = 5,
        effect = "brandy",
    ),
    KEG_OF_BEER(
        row = "dbrow.keg_of_beer",
        items = listOf("obj.keg_of_beer"),
        heal = 15,
        effect = "keg_of_beer",
    ),
    KOVACS_GROG(
        row = "dbrow.kovacs_grog",
        items = listOf("obj.kovacs_grog"),
        heal = 3,
        effect = "kovacs_grog",
    ),
    MOONLIGHT_MEAD(
        row = "dbrow.moonlight_mead",
        items = listOf(
            "obj.moonlight_mead",
            "obj.beer_glass",
        ),
        heal = 4,
    ),
    MOONLIGHT_MEAD_KEG(
        row = "dbrow.moonlight_mead_keg",
        items = listOf(
            "obj.keg_moonlight_mead_4",
            "obj.keg_moonlight_mead_3",
            "obj.keg_moonlight_mead_2",
            "obj.keg_moonlight_mead_1",
            "obj.calquat_fruit_keg_empty",
        ),
        heal = 4,
    ),
    MATURE_MOONLIGHT_MEAD(
        row = "dbrow.mature_moonlight_mead",
        items = listOf(
            "obj.mature_moonlight_mead",
            "obj.beer_glass",
        ),
        heal = 6,
    ),
    MATURE_MOONLIGHT_MEAD_KEG(
        row = "dbrow.mature_moonlight_mead_keg",
        items = listOf(
            "obj.keg_mature_moonlight_mead_4",
            "obj.keg_mature_moonlight_mead_3",
            "obj.keg_mature_moonlight_mead_2",
            "obj.keg_mature_moonlight_mead_1",
            "obj.calquat_fruit_keg_empty",
        ),
        heal = 6,
    ),
    FRUIT_BLAST(
        row = "dbrow.fruit_blast",
        items = listOf("obj.fruit_blast"),
        heal = 9,
    ),
    PREMADE_FRUIT_BLAST(
        row = "dbrow.premade_fruit_blast",
        items = listOf("obj.premade_fruit_blast"),
        heal = 9,
    ),
    PINEAPPLE_PUNCH(
        row = "dbrow.pineapple_punch",
        items = listOf("obj.pineapple_punch"),
        heal = 9,
    ),
    PREMADE_PINEAPPLE_PUNCH(
        row = "dbrow.premade_pineapple_punch",
        items = listOf("obj.premade_pineapple_punch"),
        heal = 9,
    ),
    SHORT_GREEN_GUY(
        row = "dbrow.short_green_guy",
        items = listOf("obj.sgg"),
        heal = 5,
        effect = "short_green_guy",
    ),
    PREMADE_SHORT_GREEN_GUY(
        row = "dbrow.premade_short_green_guy",
        items = listOf("obj.premade_sgg"),
        heal = 5,
        effect = "premade_short_green_guy",
    ),
    BLURBERRY_SPECIAL(
        row = "dbrow.blurberry_special",
        items = listOf("obj.blurberry_special"),
        heal = 7,
        effect = "blurberry_special",
    ),
    PREMADE_BLURBERRY_SPECIAL(
        row = "dbrow.premade_blurberry_special",
        items = listOf("obj.premade_blurberry_special"),
        heal = 7,
        effect = "premade_blurberry_special",
    ),
    DRUNK_DRAGON(
        row = "dbrow.drunk_dragon",
        items = listOf("obj.drunk_dragon"),
        heal = 5,
        effect = "drunk_dragon",
    ),
    PREMADE_DRUNK_DRAGON(
        row = "dbrow.premade_drunk_dragon",
        items = listOf("obj.premade_drunk_dragon"),
        heal = 5,
        effect = "premade_drunk_dragon",
    ),
    WIZARD_BLIZZARD(
        row = "dbrow.wizard_blizzard",
        items = listOf("obj.wizard_blizzard"),
        heal = 5,
        effect = "wizard_blizzard",
    ),
    PREMADE_WIZARD_BLIZZARD(
        row = "dbrow.premade_wizard_blizzard",
        items = listOf("obj.premade_wizard_blizzard"),
        heal = 5,
        effect = "premade_wizard_blizzard",
    ),
    CHOCOLATE_SATURDAY(
        row = "dbrow.chocolate_saturday",
        items = listOf("obj.chocolate_saturday"),
        heal = 5,
        effect = "chocolate_saturday",
    ),
    PREMADE_CHOCOLATE_SATURDAY(
        row = "dbrow.premade_chocolate_saturday",
        items = listOf("obj.premade_choc_saturday"),
        heal = 5,
        effect = "premade_chocolate_saturday",
    ),
    CAKE(
        row = "dbrow.cake",
        items = listOf(
            "obj.cake",
            "obj.partial_cake",
            "obj.cake_slice",
        ),
        heal = 4,
        eatDelay = listOf(
            2,
            2,
            3,
        ),
        combatDelay = listOf(
            3,
            3,
            3,
        ),
    ),
    CHOCOLATE_CAKE(
        row = "dbrow.chocolate_cake",
        items = listOf(
            "obj.chocolate_cake",
            "obj.partial_chocolate_cake",
            "obj.chocolate_slice",
        ),
        heal = 5,
        eatDelay = listOf(
            2,
            2,
            3,
        ),
        combatDelay = listOf(
            3,
            3,
            3,
        ),
    ),
    REDBERRY_PIE(
        row = "dbrow.redberry_pie",
        items = listOf(
            "obj.redberry_pie",
            "obj.half_a_redberry_pie",
            "obj.piedish",
        ),
        heal = 5,
        eatDelay = listOf(
            1,
            2,
        ),
        combatDelay = listOf(
            3,
            3,
        ),
    ),
    MEAT_PIE(
        row = "dbrow.meat_pie",
        items = listOf(
            "obj.meat_pie",
            "obj.half_a_meat_pie",
            "obj.piedish",
        ),
        heal = 6,
        eatDelay = listOf(
            1,
            2,
        ),
        combatDelay = listOf(
            3,
            3,
        ),
    ),
    GARDEN_PIE(
        row = "dbrow.garden_pie",
        items = listOf(
            "obj.garden_pie",
            "obj.half_garden_pie",
            "obj.piedish",
        ),
        heal = 6,
        effect = "garden_pie",
        eatDelay = listOf(
            1,
            1,
        ),
        combatDelay = listOf(
            3,
            3,
        ),
    ),
    FISH_PIE(
        row = "dbrow.fish_pie",
        items = listOf(
            "obj.fish_pie",
            "obj.half_fish_pie",
            "obj.piedish",
        ),
        heal = 6,
        effect = "fish_pie",
        eatDelay = listOf(
            1,
            1,
        ),
        combatDelay = listOf(
            3,
            3,
        ),
    ),
    APPLE_PIE(
        row = "dbrow.apple_pie",
        items = listOf(
            "obj.apple_pie",
            "obj.half_an_apple_pie",
            "obj.piedish",
        ),
        heal = 7,
        eatDelay = listOf(
            1,
            2,
        ),
        combatDelay = listOf(
            3,
            3,
        ),
    ),
    BOTANICAL_PIE(
        row = "dbrow.botanical_pie",
        items = listOf(
            "obj.botanical_pie",
            "obj.half_botanical_pie",
            "obj.piedish",
        ),
        heal = 7,
        effect = "botanical_pie",
        eatDelay = listOf(
            1,
            1,
        ),
        combatDelay = listOf(
            3,
            3,
        ),
    ),
    MUSHROOM_PIE(
        row = "dbrow.mushroom_pie",
        items = listOf(
            "obj.mushroom_pie",
            "obj.half_mushroom_pie",
            "obj.piedish",
        ),
        heal = 8,
        effect = "mushroom_pie",
        eatDelay = listOf(
            1,
            1,
        ),
        combatDelay = listOf(
            3,
            3,
        ),
    ),
    ADMIRAL_PIE(
        row = "dbrow.admiral_pie",
        items = listOf(
            "obj.admiral_pie",
            "obj.half_admiral_pie",
            "obj.piedish",
        ),
        heal = 8,
        effect = "admiral_pie",
        eatDelay = listOf(
            1,
            1,
        ),
        combatDelay = listOf(
            3,
            3,
        ),
    ),
    PLAIN_PIZZA(
        row = "dbrow.plain_pizza",
        items = listOf(
            "obj.plain_pizza",
            "obj.half_plain_pizza",
        ),
        heal = 3,
        eatDelay = listOf(
            1,
            2,
        ),
        combatDelay = listOf(3),
    ),
    MEAT_PIZZA(
        row = "dbrow.meat_pizza",
        items = listOf(
            "obj.meat_pizza",
            "obj.half_meat_pizza",
        ),
        heal = 3,
        eatDelay = listOf(
            1,
            2,
        ),
        combatDelay = listOf(3),
    ),
    ANCHOVY_PIZZA(
        row = "dbrow.anchovy_pizza",
        items = listOf(
            "obj.anchovie_pizza",
            "obj.half_anchovie_pizza",
        ),
        heal = 2,
        eatDelay = listOf(
            1,
            2,
        ),
        combatDelay = listOf(3),
    ),
    DRAGONFRUIT_PIE(
        row = "dbrow.dragonfruit_pie",
        items = listOf(
            "obj.dragonfruit_pie",
            "obj.half_dragonfruit_pie",
        ),
        heal = 10,
        effect = "dragonfruit_pie",
        eatDelay = listOf(
            1,
            1,
        ),
        combatDelay = listOf(
            3,
            3,
        ),
    ),
    PINEAPPLE_PIZZA(
        row = "dbrow.pineapple_pizza",
        items = listOf(
            "obj.pineapple_pizza",
            "obj.half_pineapple_pizza",
        ),
        heal = 11,
        eatDelay = listOf(
            1,
            2,
        ),
        combatDelay = listOf(3),
    ),
    WILD_PIE(
        row = "dbrow.wild_pie",
        items = listOf(
            "obj.wild_pie",
            "obj.half_wild_pie",
        ),
        heal = 11,
        effect = "wild_pie",
        eatDelay = listOf(
            1,
            1,
        ),
        combatDelay = listOf(
            3,
            3,
        ),
    ),
    SUMMER_PIE(
        row = "dbrow.summer_pie",
        items = listOf(
            "obj.summer_pie",
            "obj.half_summer_pie",
        ),
        heal = 11,
        effect = "summer_pie",
        eatDelay = listOf(
            1,
            1,
        ),
        combatDelay = listOf(
            3,
            3,
        ),
    ),
    TOAD_CRUNCHIES(
        row = "dbrow.toad_crunchies",
        items = listOf("obj.toad_crunchies"),
        heal = 8,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_TOAD_CRUNCHIES(
        row = "dbrow.premade_toad_crunchies",
        items = listOf("obj.premade_toad_crunchies"),
        heal = 8,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    SPICY_CRUNCHIES(
        row = "dbrow.spicy_crunchies",
        items = listOf("obj.spicy_crunchies"),
        heal = 8,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_SPICY_CRUNCHIES(
        row = "dbrow.premade_spicy_crunchies",
        items = listOf("obj.premade_spicy_crunchies"),
        heal = 8,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    WORM_CRUNCHIES(
        row = "dbrow.worm_crunchies",
        items = listOf("obj.worm_crunchies"),
        heal = 8,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_WORM_CRUNCHIES(
        row = "dbrow.premade_worm_crunchies",
        items = listOf("obj.premade_worm_crunchies"),
        heal = 8,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    CHOCOLATE_CHIP_CRUNCHIES(
        row = "dbrow.chocolate_chip_crunchies",
        items = listOf("obj.chocchip_crunchies"),
        heal = 7,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_CHOCOLATE_CHIP_CRUNCHIES(
        row = "dbrow.premade_chocolate_chip_crunchies",
        items = listOf("obj.premade_chocchip_crunchies"),
        heal = 7,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    FRUIT_BATTA(
        row = "dbrow.fruit_batta",
        items = listOf("obj.fruit_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_FRUIT_BATTA(
        row = "dbrow.premade_fruit_batta",
        items = listOf("obj.premade_fruit_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    TOAD_BATTA(
        row = "dbrow.toad_batta",
        items = listOf("obj.toad_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_TOAD_BATTA(
        row = "dbrow.premade_toad_batta",
        items = listOf("obj.premade_toad_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    WORM_BATTA(
        row = "dbrow.worm_batta",
        items = listOf("obj.worm_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_WORM_BATTA(
        row = "dbrow.premade_worm_batta",
        items = listOf("obj.premade_worm_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    VEGETABLE_BATTA(
        row = "dbrow.vegetable_batta",
        items = listOf("obj.vegetable_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_VEGETABLE_BATTA(
        row = "dbrow.premade_vegetable_batta",
        items = listOf("obj.premade_vegetable_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    CHEESE_TOMATO_BATTA(
        row = "dbrow.cheese_tomato_batta",
        items = listOf("obj.cheese+tom_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_CHEESE_TOMATO_BATTA(
        row = "dbrow.premade_cheese_tomato_batta",
        items = listOf("obj.premade_cheese+tom_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    WORM_HOLE(
        row = "dbrow.worm_hole",
        items = listOf("obj.worm_hole"),
        heal = 12,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_WORM_HOLE(
        row = "dbrow.premade_worm_hole",
        items = listOf("obj.premade_worm_hole"),
        heal = 12,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    VEGETABLE_BALL(
        row = "dbrow.vegetable_ball",
        items = listOf("obj.veg_ball"),
        heal = 12,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_VEGETABLE_BALL(
        row = "dbrow.premade_vegetable_ball",
        items = listOf("obj.premade_veg_ball"),
        heal = 12,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    CHOCOLATE_BOMB(
        row = "dbrow.chocolate_bomb",
        items = listOf("obj.chocolate_bomb"),
        heal = 15,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_CHOCOLATE_BOMB(
        row = "dbrow.premade_chocolate_bomb",
        items = listOf("obj.premade_chocolate_bomb"),
        heal = 15,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    TANGLED_TOADS_LEGS(
        row = "dbrow.tangled_toads_legs",
        items = listOf("obj.tangled_toads_legs"),
        heal = 15,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    PREMADE_TANGLED_TOADS_LEGS(
        row = "dbrow.premade_tangled_toads_legs",
        items = listOf("obj.premade_tangled_toads_legs"),
        heal = 15,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    TOADS_LEGS(
        row = "dbrow.toads_legs",
        items = listOf("obj.toads_legs"),
        heal = 3,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    CRYSTAL_PADDLEFISH(
        row = "dbrow.crystal_paddlefish",
        items = listOf("obj.gauntlet_combo_food"),
        heal = 16,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    CORRUPTED_PADDLEFISH(
        row = "dbrow.corrupted_paddlefish",
        items = listOf("obj.gauntlet_combo_food_hm"),
        heal = 16,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    COOKED_KARAMBWAN(
        row = "dbrow.cooked_karambwan",
        items = listOf("obj.tbwt_cooked_karambwan"),
        heal = 18,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    BLIGHTED_KARAMBWAN(
        row = "dbrow.blighted_karambwan",
        items = listOf("obj.blighted_karambwan"),
        heal = 18,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    BLIGHTED_MANTA_RAY(
        row = "dbrow.blighted_manta_ray",
        items = listOf("obj.blighted_mantaray"),
        heal = 22,
    ),
    BLIGHTED_ANGLERFISH(
        row = "dbrow.blighted_anglerfish",
        items = listOf("obj.blighted_anglerfish"),
        heal = -1,
        overheal = true,
    ),
    PURPLE_SWEETS(
        row = "dbrow.purple_sweets",
        items = listOf("obj.trail_sweets"),
        heal = -1,
    ),
    ALUFT_FRUIT_BLAST(
        row = "dbrow.aluft_fruit_blast",
        items = listOf("obj.aluft_fruit_blast"),
        heal = 9,
    ),
    ALUFT_PINEAPPLE_PUNCH(
        row = "dbrow.aluft_pineapple_punch",
        items = listOf("obj.aluft_pineapple_punch"),
        heal = 9,
    ),
    ALUFT_WIZARD_BLIZZARD(
        row = "dbrow.aluft_wizard_blizzard",
        items = listOf("obj.aluft_wizard_blizzard"),
        heal = 5,
        effect = "wizard_blizzard",
    ),
    ALUFT_SHORT_GREEN_GUY(
        row = "dbrow.aluft_short_green_guy",
        items = listOf("obj.aluft_sgg"),
        heal = 5,
        effect = "short_green_guy",
    ),
    ALUFT_DRUNK_DRAGON(
        row = "dbrow.aluft_drunk_dragon",
        items = listOf("obj.aluft_drunk_dragon"),
        heal = 5,
        effect = "drunk_dragon",
    ),
    ALUFT_CHOCOLATE_SATURDAY(
        row = "dbrow.aluft_chocolate_saturday",
        items = listOf("obj.aluft_choc_saturday"),
        heal = 5,
        effect = "chocolate_saturday",
    ),
    ALUFT_BLURBERRY_SPECIAL(
        row = "dbrow.aluft_blurberry_special",
        items = listOf("obj.aluft_blurberry_special"),
        heal = 7,
        effect = "blurberry_special",
    ),
    ALUFT_FRUIT_BATTA(
        row = "dbrow.aluft_fruit_batta",
        items = listOf("obj.aluft_fruit_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_TOAD_BATTA(
        row = "dbrow.aluft_toad_batta",
        items = listOf("obj.aluft_toad_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_WORM_BATTA(
        row = "dbrow.aluft_worm_batta",
        items = listOf("obj.aluft_worm_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_VEGETABLE_BATTA(
        row = "dbrow.aluft_vegetable_batta",
        items = listOf("obj.aluft_vegetable_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_CHEESE_TOMATO_BATTA(
        row = "dbrow.aluft_cheese_tomato_batta",
        items = listOf("obj.aluft_cheese+tom_batta"),
        heal = 11,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_TOAD_CRUNCHIES(
        row = "dbrow.aluft_toad_crunchies",
        items = listOf("obj.aluft_toad_crunchies"),
        heal = 8,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_SPICY_CRUNCHIES(
        row = "dbrow.aluft_spicy_crunchies",
        items = listOf("obj.aluft_spicy_crunchies"),
        heal = 8,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_WORM_CRUNCHIES(
        row = "dbrow.aluft_worm_crunchies",
        items = listOf("obj.aluft_worm_crunchies"),
        heal = 8,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_CHOCOLATE_CHIP_CRUNCHIES(
        row = "dbrow.aluft_chocolate_chip_crunchies",
        items = listOf("obj.aluft_chocchip_crunchies"),
        heal = 7,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_WORM_HOLE(
        row = "dbrow.aluft_worm_hole",
        items = listOf("obj.aluft_worm_hole"),
        heal = 12,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_VEGETABLE_BALL(
        row = "dbrow.aluft_vegetable_ball",
        items = listOf("obj.aluft_veg_ball"),
        heal = 12,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_TANGLED_TOADS_LEGS(
        row = "dbrow.aluft_tangled_toads_legs",
        items = listOf("obj.aluft_tangled_toads_legs"),
        heal = 15,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    ALUFT_CHOCOLATE_BOMB(
        row = "dbrow.aluft_chocolate_bomb",
        items = listOf("obj.aluft_chocolate_bomb"),
        heal = 15,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    ),
    VAMPYRIUM_MYSTERY_KEBAB(
        row = "dbrow.vampyrium_mystery_kebab",
        items = listOf("obj.vampyrium_mystery_kebab"),
        heal = 18,
        combo = true,
        eatDelay = listOf(3),
        combatDelay = listOf(2),
    );
}
