[[varp]]
id = "varp.diango_holiday_items_1"
scope = "Perm"
transmit = "Never"

[[varp]]
id = "varp.diango_holiday_items_2"
scope = "Perm"
transmit = "Never"

[[varp]]
id = "varp.diango_holiday_items_3"
scope = "Perm"
transmit = "Never"

[[varp]]
id = "varp.diango_holiday_items_4"
scope = "Perm"
transmit = "Never"

[[varp]]
id = "varp.diango_holiday_items_5"
scope = "Perm"
transmit = "Never"

[[varp]]
id = "varp.diango_holiday_items_6"
scope = "Perm"
transmit = "Never"

[[varp]]
id = "varp.diango_holiday_items_7"
scope = "Perm"
transmit = "Never"

[[varp]]
id = "varp.diango_holiday_items_8"
scope = "Perm"
transmit = "Never"

