package dev.openrune.tables.consumables.potion

internal enum class PotionEffectData(
    val key: String,
    val kind: String,
    val row: String = "dbrow.effect_$key",
    val skills: List<String> = emptyList(),
    val base: Int = 0,
    val percent: Int = 0,
    val amount: Int = 0,
    val effects: List<String> = emptyList(),
    val excludedSkills: List<String> = emptyList(),
    val restorePrayer: Boolean = false,
    val stamina: Boolean = false,
    val duration: Int = 0,
    val poisonImmunity: Int = 0,
    val venomImmunity: Int = 0,
    val fullProtection: Boolean = false,
    val curesDisease: Boolean = false,
    val handler: String = "",
    val baseEffect: String? = null,
    val damage: Int = 0,
    val variant: String = "",
) {
    ATTACK_BOOST(
        key = "attack_boost",
        kind = "stat_boost",
        skills = listOf("stat.attack"),
        base = 3,
        percent = 10,
    ),
    STRENGTH_BOOST(
        key = "strength_boost",
        kind = "stat_boost",
        skills = listOf("stat.strength"),
        base = 3,
        percent = 10,
    ),
    DEFENCE_BOOST(
        key = "defence_boost",
        kind = "stat_boost",
        skills = listOf("stat.defence"),
        base = 3,
        percent = 10,
    ),
    COMBAT_BOOST(
        key = "combat_boost",
        kind = "stat_boost",
        skills = listOf(
            "stat.attack",
            "stat.strength",
        ),
        base = 3,
        percent = 10,
    ),
    SUPER_ATTACK_BOOST(
        key = "super_attack_boost",
        kind = "stat_boost",
        skills = listOf("stat.attack"),
        base = 5,
        percent = 15,
    ),
    SUPER_STRENGTH_BOOST(
        key = "super_strength_boost",
        kind = "stat_boost",
        skills = listOf("stat.strength"),
        base = 5,
        percent = 15,
    ),
    SUPER_DEFENCE_BOOST(
        key = "super_defence_boost",
        kind = "stat_boost",
        skills = listOf("stat.defence"),
        base = 5,
        percent = 15,
    ),
    SUPER_COMBAT_BOOST(
        key = "super_combat_boost",
        kind = "stat_boost",
        skills = listOf(
            "stat.attack",
            "stat.strength",
            "stat.defence",
        ),
        base = 5,
        percent = 15,
    ),
    RANGING_BOOST(
        key = "ranging_boost",
        kind = "stat_boost",
        skills = listOf("stat.ranged"),
        base = 4,
        percent = 10,
    ),
    MAGIC_BOOST(
        key = "magic_boost",
        kind = "flat_stat_boost",
        skills = listOf("stat.magic"),
        amount = 4,
    ),
    AGILITY_BOOST(
        key = "agility_boost",
        kind = "flat_stat_boost",
        skills = listOf("stat.agility"),
        amount = 3,
    ),
    FISHING_BOOST(
        key = "fishing_boost",
        kind = "flat_stat_boost",
        skills = listOf("stat.fishing"),
        amount = 3,
    ),
    HUNTER_BOOST(
        key = "hunter_boost",
        kind = "flat_stat_boost",
        skills = listOf("stat.hunter"),
        amount = 3,
    ),
    SUPER_FISHING_BOOST(
        key = "super_fishing_boost",
        kind = "flat_stat_boost",
        skills = listOf("stat.fishing"),
        amount = 6,
    ),
    EXTREME_ENERGY_RESTORE(
        key = "extreme_energy_restore",
        kind = "run_energy",
        amount = 40,
    ),
    SUPER_HUNTER_BOOST(
        key = "super_hunter_boost",
        kind = "flat_stat_boost",
        skills = listOf("stat.hunter"),
        amount = 6,
    ),
    EXTENDED_STAMINA(
        key = "extended_stamina",
        kind = "compound",
        effects = listOf("dbrow.effect_extreme_energy_restore"),
        stamina = true,
        duration = minutes(4),
    ),
    ARMADYL_BREW(
        key = "armadyl_brew",
        kind = "handler",
        handler = "armadyl_brew",
    ),
    BASTION_BOOST(
        key = "bastion_boost",
        kind = "compound",
        effects = listOf(
            "dbrow.effect_ranging_boost",
            "dbrow.effect_super_defence_boost",
        ),
    ),
    BATTLEMAGE_BOOST(
        key = "battlemage_boost",
        kind = "compound",
        effects = listOf(
            "dbrow.effect_magic_boost",
            "dbrow.effect_super_defence_boost",
        ),
    ),
    RESTORE_POTION(
        key = "restore_potion",
        kind = "stat_restore",
        base = 10,
        percent = 30,
        excludedSkills = listOf(
            "stat.hitpoints",
            "stat.prayer",
        ),
    ),
    PRAYER_RESTORE(
        key = "prayer_restore",
        kind = "prayer_restore",
        base = 7,
        percent = 25,
    ),
    SUPER_RESTORE(
        key = "super_restore",
        kind = "stat_restore",
        base = 8,
        percent = 25,
        excludedSkills = listOf("stat.hitpoints"),
        restorePrayer = true,
    ),
    ENERGY_RESTORE(
        key = "energy_restore",
        kind = "run_energy",
        amount = 10,
    ),
    SUPER_ENERGY_RESTORE(
        key = "super_energy_restore",
        kind = "run_energy",
        amount = 20,
    ),
    PRAYER_REGENERATION(
        key = "prayer_regeneration",
        kind = "prayer_regeneration",
        duration = minutes(8),
    ),
    STAMINA(
        key = "stamina",
        kind = "compound",
        effects = listOf("dbrow.effect_super_energy_restore"),
        stamina = true,
        duration = minutes(2),
    ),
    ANTIPOISON(
        key = "antipoison",
        kind = "poison_cure",
        poisonImmunity = seconds(90),
    ),
    SUPERANTIPOISON(
        key = "superantipoison",
        kind = "poison_cure",
        poisonImmunity = minutes(6),
    ),
    ANTIFIRE(
        key = "antifire",
        kind = "dragonfire_protection",
        duration = minutes(6),
    ),
    SUPER_ANTIFIRE(
        key = "super_antifire",
        kind = "dragonfire_protection",
        duration = minutes(3),
        fullProtection = true,
    ),
    ANTI_VENOM_PLUS(
        key = "anti_venom_plus",
        kind = "venom_cure",
        poisonImmunity = minutes(15),
        venomImmunity = minutes(3),
    ),
    EXTENDED_ANTI_VENOM_PLUS(
        key = "extended_anti_venom_plus",
        kind = "venom_cure",
        poisonImmunity = minutes(17),
        venomImmunity = minutes(6),
    ),
    SANFEW_RESTORE(
        key = "sanfew_restore",
        kind = "stat_restore",
        base = 4,
        percent = 30,
        excludedSkills = listOf("stat.hitpoints"),
        restorePrayer = true,
    ),
    SANFEW_SERUM(
        key = "sanfew_serum",
        kind = "compound",
        effects = listOf(
            "dbrow.effect_sanfew_restore",
            "dbrow.effect_superantipoison",
        ),
        curesDisease = true,
    ),
    SARADOMIN_BREW(
        key = "saradomin_brew",
        kind = "handler",
        handler = "saradomin_brew",
    ),
    ZAMORAK_BREW(
        key = "zamorak_brew",
        kind = "handler",
        handler = "zamorak_brew",
    ),
    ANCIENT_BREW(
        key = "ancient_brew",
        kind = "handler",
        handler = "ancient_brew",
    ),
    DIVINE_SUPER_ATTACK_BOOST(
        key = "divine_super_attack_boost",
        kind = "divine",
        duration = minutes(5),
        baseEffect = "dbrow.effect_super_attack_boost",
        damage = 10,
    ),
    DIVINE_SUPER_STRENGTH_BOOST(
        key = "divine_super_strength_boost",
        kind = "divine",
        duration = minutes(5),
        baseEffect = "dbrow.effect_super_strength_boost",
        damage = 10,
    ),
    DIVINE_SUPER_DEFENCE_BOOST(
        key = "divine_super_defence_boost",
        kind = "divine",
        duration = minutes(5),
        baseEffect = "dbrow.effect_super_defence_boost",
        damage = 10,
    ),
    DIVINE_RANGING_BOOST(
        key = "divine_ranging_boost",
        kind = "divine",
        duration = minutes(5),
        baseEffect = "dbrow.effect_ranging_boost",
        damage = 10,
    ),
    DIVINE_MAGIC_BOOST(
        key = "divine_magic_boost",
        kind = "divine",
        duration = minutes(5),
        baseEffect = "dbrow.effect_magic_boost",
        damage = 10,
    ),
    DIVINE_BASTION_BOOST(
        key = "divine_bastion_boost",
        kind = "divine",
        duration = minutes(5),
        baseEffect = "dbrow.effect_bastion_boost",
        damage = 10,
    ),
    DIVINE_BATTLEMAGE_BOOST(
        key = "divine_battlemage_boost",
        kind = "divine",
        duration = minutes(5),
        baseEffect = "dbrow.effect_battlemage_boost",
        damage = 10,
    ),
    DIVINE_SUPER_COMBAT_BOOST(
        key = "divine_super_combat_boost",
        kind = "divine",
        duration = minutes(5),
        baseEffect = "dbrow.effect_super_combat_boost",
        damage = 10,
    ),
    ANTI_VENOM(
        key = "anti_venom",
        kind = "venom_cure",
        poisonImmunity = minutes(12),
        venomImmunity = seconds(36),
    ),
    EXTENDED_ANTIFIRE(
        key = "extended_antifire",
        kind = "dragonfire_protection",
        duration = minutes(12),
    ),
    EXTENDED_SUPER_ANTIFIRE(
        key = "extended_super_antifire",
        kind = "dragonfire_protection",
        duration = minutes(6),
        fullProtection = true,
    ),
    FORGOTTEN_BREW(
        key = "forgotten_brew",
        kind = "handler",
        handler = "forgotten_brew",
    ),
    MENAPHITE_REMEDY(
        key = "menaphite_remedy",
        kind = "handler",
        handler = "menaphite_remedy",
    ),
    GUTHIX_REST(
        key = "guthix_rest",
        kind = "handler",
        handler = "guthix_rest",
    ),
    NZONE_OVERLOAD(
        key = "nzone_overload",
        kind = "handler",
        handler = "nzone_overload",
    ),
    NZONE_ABSORPTION(
        key = "nzone_absorption",
        kind = "handler",
        handler = "nzone_absorption",
    ),
    NZONE_SUPER_RANGING(
        key = "nzone_super_ranging",
        kind = "stat_boost",
        skills = listOf("stat.ranged"),
        base = 5,
        percent = 15,
    ),
    NZONE_SUPER_MAGIC(
        key = "nzone_super_magic",
        kind = "stat_boost",
        skills = listOf("stat.magic"),
        base = 5,
        percent = 15,
    ),
    COX_XERICS_AID_WEAK(
        key = "cox_xerics_aid_weak",
        kind = "handler",
        handler = "cox_xerics_aid",
        variant = "weak",
    ),
    COX_XERICS_AID(
        key = "cox_xerics_aid",
        kind = "handler",
        handler = "cox_xerics_aid",
        variant = "normal",
    ),
    COX_XERICS_AID_STRONG(
        key = "cox_xerics_aid_strong",
        kind = "handler",
        handler = "cox_xerics_aid",
        variant = "strong",
    ),
    COX_REVITALISATION_WEAK(
        key = "cox_revitalisation_weak",
        kind = "handler",
        handler = "cox_revitalisation",
        variant = "weak",
    ),
    COX_REVITALISATION(
        key = "cox_revitalisation",
        kind = "handler",
        handler = "cox_revitalisation",
        variant = "normal",
    ),
    COX_REVITALISATION_STRONG(
        key = "cox_revitalisation_strong",
        kind = "handler",
        handler = "cox_revitalisation",
        variant = "strong",
    ),
    COX_PRAYER_ENHANCE_WEAK(
        key = "cox_prayer_enhance_weak",
        kind = "handler",
        handler = "cox_prayer_enhance",
        variant = "weak",
    ),
    COX_PRAYER_ENHANCE(
        key = "cox_prayer_enhance",
        kind = "handler",
        handler = "cox_prayer_enhance",
        variant = "normal",
    ),
    COX_PRAYER_ENHANCE_STRONG(
        key = "cox_prayer_enhance_strong",
        kind = "handler",
        handler = "cox_prayer_enhance",
        variant = "strong",
    ),
    COX_OVERLOAD_WEAK(
        key = "cox_overload_weak",
        kind = "handler",
        handler = "cox_overload",
        variant = "weak",
    ),
    COX_OVERLOAD(
        key = "cox_overload",
        kind = "handler",
        handler = "cox_overload",
        variant = "normal",
    ),
    COX_OVERLOAD_STRONG(
        key = "cox_overload_strong",
        kind = "handler",
        handler = "cox_overload",
        variant = "strong",
    ),
    COX_ELDER_POTION_WEAK(
        key = "cox_elder_potion_weak",
        kind = "handler",
        handler = "cox_elder_potion",
        variant = "weak",
    ),
    COX_ELDER_POTION(
        key = "cox_elder_potion",
        kind = "handler",
        handler = "cox_elder_potion",
        variant = "normal",
    ),
    COX_ELDER_POTION_STRONG(
        key = "cox_elder_potion_strong",
        kind = "handler",
        handler = "cox_elder_potion",
        variant = "strong",
    ),
    COX_KODAI_POTION_WEAK(
        key = "cox_kodai_potion_weak",
        kind = "handler",
        handler = "cox_kodai_potion",
        variant = "weak",
    ),
    COX_KODAI_POTION(
        key = "cox_kodai_potion",
        kind = "handler",
        handler = "cox_kodai_potion",
        variant = "normal",
    ),
    COX_KODAI_POTION_STRONG(
        key = "cox_kodai_potion_strong",
        kind = "handler",
        handler = "cox_kodai_potion",
        variant = "strong",
    ),
    COX_TWISTED_POTION_WEAK(
        key = "cox_twisted_potion_weak",
        kind = "handler",
        handler = "cox_twisted_potion",
        variant = "weak",
    ),
    COX_TWISTED_POTION(
        key = "cox_twisted_potion",
        kind = "handler",
        handler = "cox_twisted_potion",
        variant = "normal",
    ),
    COX_TWISTED_POTION_STRONG(
        key = "cox_twisted_potion_strong",
        kind = "handler",
        handler = "cox_twisted_potion",
        variant = "strong",
    ),
    TOA_NECTAR(
        key = "toa_nectar",
        kind = "handler",
        handler = "toa_nectar",
    ),
    TOA_AMBROSIA(
        key = "toa_ambrosia",
        kind = "handler",
        handler = "toa_ambrosia",
    ),
    TOA_TEARS_OF_ELIDINIS(
        key = "toa_tears_of_elidinis",
        kind = "handler",
        handler = "toa_tears_of_elidinis",
    ),
    TOA_LIQUID_ADRENALINE(
        key = "toa_liquid_adrenaline",
        kind = "handler",
        handler = "toa_liquid_adrenaline",
    ),
    TOA_SMELLING_SALTS(
        key = "toa_smelling_salts",
        kind = "handler",
        handler = "toa_smelling_salts",
    ),
    TOA_SILK_DRESSING(
        key = "toa_silk_dressing",
        kind = "handler",
        handler = "toa_silk_dressing",
    ),
    TOA_BLESSED_CRYSTAL_SCARAB(
        key = "toa_blessed_crystal_scarab",
        kind = "handler",
        handler = "toa_blessed_crystal_scarab",
    ),
    ANTIDOTE_PLUS(
        key = "antidote_plus",
        kind = "poison_cure",
        poisonImmunity = minutes(9),
    ),
    ANTIDOTE_PLUS_PLUS(
        key = "antidote_plus_plus",
        kind = "poison_cure",
        poisonImmunity = minutes(12),
        venomImmunity = seconds(36),
    ),
    RELICYMS_BALM(
        key = "relicyms_balm",
        kind = "handler",
        handler = "relicyms_balm",
    ),
    MOONLIGHT_POTION(
        key = "moonlight_potion",
        kind = "handler",
        handler = "moonlight_potion",
    );
}

private fun seconds(value: Int): Int =
    (value * 5 + 2) / 3

private fun minutes(value: Int): Int =
    seconds(value * 60)
