/**
 * Revision-240 desktop server packet metadata.
 *
 * Source of truth: blurite/rsprot @ a0c06bdfbe0b5654d737431cc28966e093e0e20f
 * GameServerProt.kt + GameServerProtId.kt.
 *
 * size >= 0: fixed payload size
 * size === -1: unsigned one-byte payload length
 * size === -2: unsigned two-byte big-endian payload length
 */
export interface ServerPacketSpec {
  readonly opcode: number;
  readonly name: string;
  readonly size: number;
}

export const VAR_BYTE = -1;
export const VAR_SHORT = -2;

const SPECS: ReadonlyArray<ServerPacketSpec | undefined> = [
  { opcode: 0, name: 'CAM_TARGET_V4', size: 5 },
  { opcode: 1, name: 'IF_SETOBJECT', size: 10 },
  { opcode: 2, name: 'MESSAGE_FRIENDCHANNEL', size: -1 },
  { opcode: 3, name: 'HINT_ARROW', size: 6 },
  { opcode: 4, name: 'IF_SETANGLE', size: 10 },
  { opcode: 5, name: 'CLANSETTINGS_DELTA', size: -2 },
  { opcode: 6, name: 'SET_INTERACTION_MODE', size: 4 },
  { opcode: 7, name: 'CLANCHANNEL_FULL', size: -2 },
  { opcode: 8, name: 'MIDI_SONG_STOP', size: 4 },
  { opcode: 9, name: 'UPDATE_IGNORELIST', size: -2 },
  { opcode: 10, name: 'RUNCLIENTSCRIPT', size: -2 },
  { opcode: 11, name: 'IF_SETTEXT', size: -2 },
  { opcode: 12, name: 'REBUILD_REGION_V2', size: -2 },
  { opcode: 13, name: 'MAP_ANIM', size: 6 },
  { opcode: 14, name: 'UPDATE_INV_STOPTRANSMIT', size: 2 },
  { opcode: 15, name: 'SET_HEATMAP_ENABLED', size: 1 },
  { opcode: 16, name: 'SOUND_AREA', size: 7 },
  { opcode: 17, name: 'CAM_RESET', size: 0 },
  { opcode: 18, name: 'CHAT_FILTER_SETTINGS', size: 2 },
  { opcode: 19, name: 'UPDATE_RUNWEIGHT', size: 2 },
  { opcode: 20, name: 'SET_ACTIVE_WORLD_V2', size: 3 },
  { opcode: 21, name: 'VARCLAN', size: -1 },
  { opcode: 22, name: 'IF_SETPLAYERHEAD', size: 4 },
  { opcode: 23, name: 'UPDATE_INV_PARTIAL', size: -2 },
  { opcode: 24, name: 'UPDATE_FRIENDLIST', size: -2 },
  { opcode: 25, name: 'VARCLAN_DISABLE', size: 0 },
  { opcode: 26, name: 'LOGOUT_TRANSFER', size: -1 },
  { opcode: 27, name: 'MESSAGE_PRIVATE_ECHO', size: -2 },
  { opcode: 28, name: 'IF_SETCOLOUR', size: 6 },
  { opcode: 29, name: 'UPDATE_TRADINGPOST', size: -2 },
  { opcode: 30, name: 'IF_RESYNC_V2', size: -2 },
  { opcode: 31, name: 'MIDI_SWAP', size: 8 },
  { opcode: 32, name: 'CAM_MODE', size: 1 },
  { opcode: 33, name: 'CAM_ROTATETO', size: 7 },
  { opcode: 34, name: 'CAM_SMOOTHRESET', size: 4 },
  { opcode: 35, name: 'IF_OPENTOP', size: 2 },
  { opcode: 36, name: 'MESSAGE_PRIVATE', size: -2 },
  { opcode: 37, name: 'LOGOUT', size: 0 },
  { opcode: 38, name: 'LOC_ADD_CHANGE_V2', size: -2 },
  { opcode: 39, name: 'REBUILD_NORMAL_V2', size: -2 },
  { opcode: 40, name: 'MIDI_JINGLE', size: 5 },
  { opcode: 41, name: 'LOC_DEL', size: 2 },
  { opcode: 42, name: 'IF_SETPLAYERMODEL_BASECOLOUR', size: 6 },
  { opcode: 43, name: 'MESSAGE_CLANCHANNEL', size: -1 },
  { opcode: 44, name: 'UNKNOWN_STRING', size: -1 },
  { opcode: 45, name: 'IF_OPENSUB', size: 7 },
  { opcode: 46, name: 'CLANCHANNEL_DELTA', size: -2 },
  { opcode: 47, name: 'MIDI_SONG_WITHSECONDARY', size: 12 },
  { opcode: 48, name: 'LOC_MERGE', size: 14 },
  { opcode: 49, name: 'UPDATE_ZONE_PARTIAL_ENCLOSED', size: -2 },
  { opcode: 50, name: 'IF_SETPLAYERMODEL_OBJ', size: 8 },
  { opcode: 51, name: 'IF_MOVESUB', size: 8 },
  { opcode: 52, name: 'OBJ_CUSTOMISE_SPECIFIC', size: 20 },
  { opcode: 53, name: 'SITE_SETTINGS', size: -1 },
  { opcode: 54, name: 'IF_SETHIDE', size: 5 },
  { opcode: 55, name: 'HIDELOCOPS', size: 1 },
  { opcode: 56, name: 'LOGOUT_WITHREASON', size: 1 },
  { opcode: 57, name: 'PACKET_GROUP_START', size: 2 },
  { opcode: 58, name: 'RESET_ANIMS', size: 0 },
  { opcode: 59, name: 'IF_SETANIM', size: 6 },
  { opcode: 60, name: 'IF_CLEARINV', size: 4 },
  { opcode: 61, name: 'IF_SETNPCHEAD', size: 6 },
  { opcode: 62, name: 'IF_SETPLAYERMODEL_SELF', size: 5 },
  { opcode: 63, name: 'UPDATE_STAT_V2', size: 7 },
  { opcode: 64, name: 'IF_SETPLAYERMODEL_BODYTYPE', size: 5 },
  { opcode: 65, name: 'OCULUS_SYNC', size: 4 },
  { opcode: 66, name: 'UPDATE_REBOOT_TIMER_V2', size: -1 },
  { opcode: 67, name: 'IF_SETNPCHEAD_ACTIVE', size: 6 },
  { opcode: 68, name: 'VARP_RESET', size: 0 },
  { opcode: 69, name: 'HISCORE_REPLY', size: -2 },
  { opcode: 70, name: 'FRIENDLIST_LOADED', size: 0 },
  { opcode: 71, name: 'CAM_TARGET_V3', size: 5 },
  { opcode: 72, name: 'PROJANIM_SPECIFIC_V4', size: 27 },
  { opcode: 73, name: 'MESSAGE_GAME', size: -1 },
  { opcode: 74, name: 'UPDATE_INV_FULL', size: -2 },
  { opcode: 75, name: 'REBUILD_WORLDENTITY_V4', size: -2 },
  { opcode: 76, name: 'CHAT_FILTER_SETTINGS_PRIVATECHAT', size: 1 },
  { opcode: 77, name: 'TRIGGER_ONDIALOGABORT', size: 0 },
  { opcode: 78, name: 'IF_SETSCROLLPOS', size: 6 },
  { opcode: 79, name: 'MESSAGE_CLANCHANNEL_SYSTEM', size: -1 },
  { opcode: 80, name: 'WORLDENTITY_INFO_V7', size: -2 },
  { opcode: 81, name: 'MIDI_SONG_V2', size: 10 },
  { opcode: 82, name: 'ACCOUNT_FLAGS', size: 8 },
  { opcode: 83, name: 'PLAYER_SPOTANIM_SPECIFIC', size: 9 },
  { opcode: 84, name: 'LOC_ANIM_SPECIFIC', size: 6 },
  { opcode: 85, name: 'SET_PLAYER_OP', size: -1 },
  { opcode: 86, name: 'OBJ_DEL_SPECIFIC', size: 10 },
  { opcode: 87, name: 'OBJ_ENABLED_OPS_SPECIFIC', size: 7 },
  { opcode: 88, name: 'UPDATE_FRIENDCHAT_CHANNEL_FULL_V2', size: -2 },
  { opcode: 89, name: 'OBJ_UNCUSTOMISE_SPECIFIC', size: 10 },
  { opcode: 90, name: 'MAP_ANIM_SPECIFIC', size: 8 },
  { opcode: 91, name: 'PLAYER_INFO', size: -2 },
  { opcode: 92, name: 'SERVER_TICK_END', size: 0 },
  { opcode: 93, name: 'NPC_INFO_LARGE_V5', size: -2 },
  { opcode: 94, name: 'VARP_LARGE', size: 6 },
  { opcode: 95, name: 'CAM_ROTATEBY', size: 7 },
  { opcode: 96, name: 'NPC_HEADICON_SPECIFIC', size: 9 },
  { opcode: 97, name: 'CLANSETTINGS_FULL', size: -2 },
  { opcode: 98, name: 'SYNTH_SOUND', size: 5 },
  { opcode: 99, name: 'UPDATE_UID192', size: 28 },
  { opcode: 100, name: 'VARP_SYNC', size: 0 },
  { opcode: 101, name: 'NPC_SPOTANIM_SPECIFIC', size: 9 },
  { opcode: 102, name: 'ANIM_SPECIFIC', size: 3 },
  { opcode: 103, name: 'UPDATE_STOCKMARKET_SLOT', size: 20 },
  { opcode: 104, name: 'VARCLAN_ENABLE', size: 0 },
  { opcode: 105, name: 'IF_SETROTATESPEED', size: 8 },
  { opcode: 106, name: 'IF_SETEVENTS_V2', size: 16 },
  { opcode: 107, name: 'URL_OPEN', size: -2 },
  { opcode: 108, name: 'IF_SETPOSITION', size: 8 },
  { opcode: 109, name: 'UPDATE_FRIENDCHAT_CHANNEL_SINGLEUSER', size: -1 },
  { opcode: 110, name: 'HIDENPCOPS', size: 1 },
  { opcode: 111, name: 'SET_NPC_UPDATE_ORIGIN', size: 2 },
  { opcode: 112, name: 'HIDEOBJOPS', size: 1 },
  { opcode: 113, name: 'CAM_SHAKE', size: 4 },
  { opcode: 114, name: 'OBJ_ADD_SPECIFIC', size: 17 },
  { opcode: 115, name: 'SEND_PING', size: 8 },
  { opcode: 116, name: 'IF_CLOSESUB', size: 4 },
  { opcode: 117, name: 'NPC_ANIM_SPECIFIC', size: 5 },
  { opcode: 118, name: 'UPDATE_ZONE_PARTIAL_FOLLOWS', size: 3 },
  { opcode: 119, name: 'NPC_INFO_SMALL_V5', size: -2 },
  { opcode: 120, name: 'UPDATE_RUNENERGY', size: 2 },
  { opcode: 121, name: 'RESET_INTERACTION_MODE', size: 2 },
  { opcode: 122, name: 'MINIMAP_TOGGLE', size: 1 },
  { opcode: 123, name: 'LOC_ANIM', size: 4 },
  { opcode: 124, name: 'OBJ_COUNT_SPECIFIC', size: 14 },
  { opcode: 125, name: 'REFLECTION_CHECKER', size: -2 },
  { opcode: 126, name: 'UPDATE_ZONE_FULL_FOLLOWS', size: 3 },
  { opcode: 127, name: 'VARP_SMALL', size: 3 },
  { opcode: 128, name: 'CAM_ROTATETO_COORDINATE_V3', size: 11 },
  undefined, // 129: UNHANDLED
  { opcode: 130, name: 'CAM_MOVETO_CYCLES_V3', size: 11 },
  { opcode: 131, name: 'CAM_MOVETO_ARC_V3', size: 15 },
  { opcode: 132, name: 'IF_SETMODEL_V2', size: 8 },
  { opcode: 133, name: 'CAM_ROTATETO_COORDINATE_V2', size: 9 },
  { opcode: 134, name: 'CAM_MOVETO_V3', size: 9 },
  { opcode: 135, name: 'AMBIENTSOUND_START', size: 3 },
  { opcode: 136, name: 'SET_MAP_FLAG_V2', size: 4 },
  { opcode: 137, name: 'GROUP_VAR_LONG', size: 13 },
  { opcode: 138, name: 'AMBIENTSOUND_STOP', size: 1 },
  { opcode: 139, name: 'GROUP_FULL', size: -2 },
  { opcode: 140, name: 'CAM_SKYBOX', size: 4 },
  { opcode: 141, name: 'NPC_INFO_LARGE_V6', size: -2 },
  { opcode: 142, name: 'GROUP_VAR', size: -2 },
  { opcode: 143, name: 'CAM_MOVETO_ARC_V2', size: 14 },
  { opcode: 144, name: 'GROUP_VAR_INT', size: 9 },
  { opcode: 145, name: 'CAM_LOOKAT_CYCLES', size: 10 },
  { opcode: 146, name: 'CAM_LOOKAT_V2', size: 8 },
  { opcode: 147, name: 'CAM_MOVETO_CYCLES_V2', size: 10 },
  { opcode: 148, name: 'CAM_LOOKAT_V3', size: 9 },
  { opcode: 149, name: 'CAM_UNLOCK', size: 1 },
  { opcode: 150, name: 'NPC_INFO_SMALL_V6', size: -2 },
  { opcode: 151, name: 'CAM_MOVETO_V2', size: 8 },
];

export function getServerPacketSpec(opcode: number): ServerPacketSpec {
  const spec = SPECS[opcode];
  if (!spec) {
    throw new RangeError('Unknown rev-240 server packet opcode ' + opcode + '.');
  }
  return spec;
}

export function tryGetServerPacketSpec(
  opcode: number,
): ServerPacketSpec | undefined {
  return SPECS[opcode];
}
