
[gamevals.queue]
crafting_make = 57
crafting_cape_teleport = 60

[gamevals.synth]
crafting_pottery_wheel_craft = 2588
glassblowing = 2724

sand_bucket = 2584
attach_orb = 2585
chisel = 2586
loom_weave = 2587
smash_gem = 2589
spinning = 2590
stiching = 2591
stringing = 2593

[gamevals.content]
sandpit = 54
crafting_spinning_wheel = 55
crafting_loom = 56
crafting_pottery_wheel = 57
crafting_pottery_oven = 58

[gamevals.enum]
kourend_diary_tiers=65471

[gamevals.varp]
crafting_state=65480

[gamevals.varbit]
crafting_thread_uses=65452
crafting_tanner_prices=65451

[gamevals.dbtable]
crafting_facilities=65506
crafting_hand=65505
crafting_tanning=65504
crafting_silver=65503
crafting_gold=65502

[gamevals.dbrow]
crafting_spin_ball_of_wool=64130
crafting_spin_bow_string=64129
crafting_spin_crossbow_string=64128
crafting_spin_crossbow_string_roots=64127
crafting_spin_magic_string=64126
crafting_spin_rope=64125
crafting_spin_linen_yarn=64124
crafting_spin_hemp_yarn=64123
crafting_spin_cotton_yarn=64122
crafting_weave_strip_of_cloth=64121
crafting_weave_bolt_of_linen=64120
crafting_weave_empty_sack=64119
crafting_weave_drift_net=64118
crafting_weave_basket=64117
crafting_weave_bolt_of_canvas=64116
crafting_weave_bolt_of_cotton=64115
crafting_shape_pot=64114
crafting_shape_cup=64113
crafting_shape_pie_dish=64112
crafting_shape_bowl=64111
crafting_shape_plant_pot=64110
crafting_shape_pot_lid=64109
crafting_fire_pot=64108
crafting_fire_cup=64107
crafting_fire_pie_dish=64106
crafting_fire_bowl=64105
crafting_fire_plant_pot=64104
crafting_fire_pot_lid=64103
crafting_leather_gloves=64102
crafting_leather_boots=64101
crafting_leather_cowl=64100
crafting_leather_vambraces=64099
crafting_leather_body=64098
crafting_leather_chaps=64097
crafting_hardleather_body=64096
crafting_coif=64095
crafting_studded_body=64094
crafting_studded_chaps=64093
crafting_spiky_vambraces=64092
crafting_green_dhide_vambraces=64091
crafting_green_dhide_chaps=64090
crafting_green_dhide_body=64089
crafting_blue_dhide_vambraces=64088
crafting_blue_dhide_chaps=64087
crafting_blue_dhide_body=64086
crafting_red_dhide_vambraces=64085
crafting_red_dhide_chaps=64084
crafting_red_dhide_body=64083
crafting_black_dhide_vambraces=64082
crafting_black_dhide_chaps=64081
crafting_black_dhide_body=64080
crafting_snakeskin_boots=64079
crafting_snakeskin_vambraces=64078
crafting_snakeskin_bandana=64077
crafting_snakeskin_chaps=64076
crafting_snakeskin_body=64075
crafting_yak_legs=64074
crafting_yak_top=64073
crafting_xerician_hat=64072
crafting_xerician_robe=64071
crafting_xerician_top=64070
crafting_splitbark_gauntlets=64069
crafting_splitbark_boots=64068
crafting_splitbark_helm=64067
crafting_splitbark_legs=64066
crafting_splitbark_body=64065
crafting_hueycoatl_vambraces=64064
crafting_hueycoatl_coif=64063
crafting_hueycoatl_chaps=64062
crafting_hueycoatl_body=64061
crafting_mixed_hide_cape=64060
crafting_mixed_hide_boots=64059
crafting_mixed_hide_legs=64058
crafting_mixed_hide_top=64057
crafting_hard_leather_shield=64056
crafting_snakeskin_shield=64055
crafting_green_dhide_shield=64054
crafting_blue_dhide_shield=64053
crafting_red_dhide_shield=64052
crafting_black_dhide_shield=64051
crafting_broodoo_shield_blue=64050
crafting_broodoo_shield_green=64049
crafting_broodoo_shield_orange=64048
crafting_crab_helmet=64047
crafting_crab_claw=64046
crafting_cut_opal=64045
crafting_cut_jade=64044
crafting_cut_red_topaz=64043
crafting_cut_sapphire=64042
crafting_cut_emerald=64041
crafting_cut_ruby=64040
crafting_cut_diamond=64039
crafting_cut_dragonstone=64038
crafting_cut_onyx=64037
crafting_cut_zenyte=64036
crafting_amethyst_bolt_tips=64035
crafting_amethyst_arrowtips=64034
crafting_amethyst_javelin_heads=64033
crafting_amethyst_dart_tips=64032
crafting_molten_glass=64031
crafting_glass_beer_glass=64030
crafting_glass_candle_lantern=64029
crafting_glass_oil_lamp=64028
crafting_glass_vial=64027
crafting_glass_fishbowl=64026
crafting_glass_unpowered_orb=64025
crafting_glass_lantern_lens=64024
crafting_glass_light_orb=64023
crafting_unstrung_symbol=64022
crafting_unstrung_emblem=64021
crafting_silver_sickle=64020
crafting_silver_bolts=64019
crafting_tiara=64018
crafting_gold_ring=64017
crafting_gold_necklace=64016
crafting_gold_bracelet=64015
crafting_gold_amulet=64014
crafting_water_battlestaff=64013
crafting_earth_battlestaff=64012
crafting_fire_battlestaff=64011
crafting_air_battlestaff=64010
crafting_tan_soft_leather=64009
crafting_tan_hard_leather=64008
crafting_tan_snakeskin=64007
crafting_tan_snakeskin_swamp=64006
crafting_tan_green_dhide=64005
crafting_tan_blue_dhide=64004
crafting_tan_red_dhide=64003
crafting_tan_black_dhide=64002
crafting_cure_yak_hide=64001
crafting_snelm_red_pointed=64000
crafting_snelm_red_round=63999
crafting_snelm_bark=63998
crafting_snelm_blue_pointed=63997
crafting_snelm_blue_round=63996
crafting_snelm_myre_pointed=63995
crafting_snelm_myre_round=63994
crafting_snelm_ochre_pointed=63993
crafting_snelm_ochre_round=63992
crafting_opal_ring=63991
crafting_opal_necklace=63990
crafting_opal_bracelet=63989
crafting_opal_amulet=63988
crafting_jade_ring=63987
crafting_jade_necklace=63986
crafting_jade_bracelet=63985
crafting_jade_amulet=63984
crafting_topaz_ring=63983
crafting_topaz_necklace=63982
crafting_topaz_bracelet=63981
crafting_topaz_amulet=63980
crafting_sapphire_ring=63979
crafting_sapphire_necklace=63978
crafting_sapphire_bracelet=63977
crafting_sapphire_amulet=63976
crafting_emerald_ring=63975
crafting_emerald_necklace=63974
crafting_emerald_bracelet=63973
crafting_emerald_amulet=63972
crafting_perfect_ring=63164
crafting_perfect_necklace=63163
crafting_ruby_ring=63971
crafting_ruby_necklace=63970
crafting_ruby_bracelet=63969
crafting_ruby_amulet=63968
crafting_diamond_ring=63967
crafting_diamond_necklace=63966
crafting_diamond_bracelet=63965
crafting_diamond_amulet=63964
crafting_dragonstone_ring=63963
crafting_dragonstone_necklace=63962
crafting_dragonstone_bracelet=63961
crafting_dragonstone_amulet=63960
crafting_onyx_ring=63959
crafting_onyx_necklace=63958
crafting_onyx_bracelet=63957
crafting_onyx_amulet=63956
crafting_zenyte_ring=63955
crafting_zenyte_necklace=63954
crafting_zenyte_bracelet=63953
crafting_zenyte_amulet=63952
crafting_limestone_brick=63951
crafting_string_gold_amulet=63950
crafting_string_sapphire_amulet=63949
crafting_string_emerald_amulet=63948
crafting_string_ruby_amulet=63947
crafting_string_diamond_amulet=63946
crafting_string_dragonstone_amulet=63945
crafting_string_onyx_amulet=63944
crafting_string_zenyte_amulet=63943
crafting_string_opal_amulet=63942
crafting_string_jade_amulet=63941
crafting_string_topaz_amulet=63940
crafting_string_emblem=63939
crafting_string_symbol=63938
crafting_slayer_ring=63937
crafting_slayer_ring_eternal=63936
crafting_conductor=63935
crafting_silvthrill_rod=63934
crafting_demonic_sigil=63933
crafting_slayer_helm=63932
crafting_noxious_halberd=63931
crafting_toxic_staff_of_the_dead=63930
crafting_trident_of_the_swamp=63929
crafting_bone_staff=63928
crafting_accursed_sceptre=63927
crafting_strung_rabbit_foot=63926
crafting_birdhouse_normal=63925
crafting_birdhouse_oak=63924
crafting_birdhouse_willow=63923
crafting_birdhouse_teak=63922
crafting_birdhouse_maple=63921
crafting_birdhouse_mahogany=63920
crafting_birdhouse_yew=63919
crafting_birdhouse_magic=63918
crafting_birdhouse_redwood=63917
crafting_soft_clay_bucket_water=63916
crafting_soft_clay_jug_water=63915
crafting_soft_clay_bowl_water=63914
crafting_soft_clay_cup_water=63913
crafting_fill_bucket_sand=63912
crafting_serpentine_helm=63911
crafting_pheasant_boots=63910
crafting_pheasant_hat=63909
crafting_pheasant_legs=63908
crafting_pheasant_cape=63907
crafting_break_armadyl_chestplate=63906
crafting_break_armadyl_skirt=63905
crafting_break_armadyl_helmet=63904
crafting_fortify_masori_body=63903
crafting_fortify_masori_chaps=63902
crafting_fortify_masori_mask=63901
crafting_dramen_staff=63900
crafting_sinew=63899
crafting_light_orb=63898
crafting_slayer_helm_goggles=63897
crafting_amulet_of_rancour=63896
crafting_confliction_gauntlets=63895
crafting_necklace_of_rupture=63894