/*
BSD 2-Clause License

Copyright (c) 2022-2026, dennisdev, xrsps
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
// Generated by scripts/adapt-player-config.mjs from pinned TSPS b9ca431.
import {ByteBuffer} from './cache-reader.mjs';
const ObjStackability={SOMETIMES:0,ALWAYS:1,NEVER:2};
class Type {
    constructor(id){this.id=id;this.cacheInfo={game:'oldschool',revision:240};this.cacheType='dat2';}
    readString(buffer){return buffer.readString();}
    static readParamsMap(b,params=new Map()){
        for(let n=b.readUnsignedByte();n>0;n--){const string=b.readUnsignedByte(),key=b.readMedium();params.set(key,string?b.readString():b.readInt());}return params;
    }
    decode(bytes){
        const b=new ByteBuffer(bytes);
        for(let n=0;n<4096;n++){const op=b.readUnsignedByte();if(!op){if(b.offset!==b.length)throw new Error('Trailing player config data');return this;}this.decodeOpcode(op,b);}
        throw new Error('Player config opcode limit exceeded');
    }
}

// Identity Kit
export class IdkType extends Type {
    bodyPartyId        ;

    modelIds           ;

    recolorFrom           ;
    recolorTo           ;

    retextureFrom           ;
    retextureTo           ;

    ifModelIds          ;

    nonSelectable         ;

    constructor(id        , cacheInfo           ) {
        super(id, cacheInfo);
        this.bodyPartyId = -1;
        this.ifModelIds = [-1, -1, -1, -1, -1];
        this.nonSelectable = false;
    }

             decodeOpcode(opcode        , buffer            )       {
        if (opcode === 1) {
            this.bodyPartyId = buffer.readUnsignedByte();
        } else if (opcode === 2) {
            const modelCount = buffer.readUnsignedByte();
            this.modelIds = new Array        (modelCount);
            for (let i = 0; i < modelCount; i++) {
                this.modelIds[i] = buffer.readUnsignedShort();
            }
        } else if (opcode === 3) {
            this.nonSelectable = true;
        } else if (opcode === 5) {
            const modelCount = buffer.readUnsignedByte();
            this.modelIds = new Array        (modelCount);
            for (let i = 0; i < modelCount; i++) {
                this.modelIds[i] = buffer.readInt();
            }
        } else if (opcode === 40) {
            const count = buffer.readUnsignedByte();
            this.recolorFrom = new Array        (count);
            this.recolorTo = new Array        (count);
            for (let i = 0; i < count; i++) {
                this.recolorFrom[i] = buffer.readUnsignedShort();
                this.recolorTo[i] = buffer.readUnsignedShort();
            }
        } else if (opcode === 41) {
            const count = buffer.readUnsignedByte();
            this.retextureFrom = new Array        (count);
            this.retextureTo = new Array        (count);
            for (let i = 0; i < count; i++) {
                this.retextureFrom[i] = buffer.readUnsignedShort();
                this.retextureTo[i] = buffer.readUnsignedShort();
            }
        } else if (opcode >= 60 && opcode < 70) {
            this.ifModelIds[opcode - 60] = buffer.readUnsignedShort();
        } else if (opcode >= 70 && opcode < 80) {
            this.ifModelIds[opcode - 70] = buffer.readInt();
        } else { throw new Error('Unsupported identity kit opcode '+opcode); }
    }
}
export class ObjType extends Type {
    model         ;

    name        ;
    examine         ;

    recolorFrom           ;
    recolorTo           ;

    retextureFrom           ;
    retextureTo           ;

    zoom2d        ;
    xan2d        ;
    yan2d        ;
    zan2d        ;

    offsetX2d        ;
    offsetY2d        ;

    op9         ;

    stackability                 ;

    price        ;

    wearPos        ;

    wearPos2        ;

    isMembers         ;

    groundActions                   ;
    inventoryActions                   ;
    // subops[opIndex][subIndex] = nested "Choose Option" submenu text per inventory op
    subops                                     ;
    shiftClickIndex        ;

    maleModel        ;
    maleModel1        ;
    maleOffset        ;

    femaleModel        ;
    femaleModel1        ;
    femaleOffset        ;

    maleModel2        ;
    femaleModel2        ;

    maleHeadModel        ;
    maleHeadModel2        ;

    femaleHeadModel        ;
    femaleHeadModel2        ;

    countObj           ;
    countCo           ;

    wearPos3        ;

    note        ;
    noteTemplate        ;

    resizeX        ;
    resizeY        ;
    resizeZ        ;

    ambient        ;
    contrast        ;

    team        ;

    isTradable         ;
    /** Rev 241 opcode 251: the obj can be unlocked (the cache's `unlockable=yes`). */
    isUnlockable         ;
    /** Opcode 94: the obj's category (oc_category), -1 when unset. */
    category         = -1;

    weight        ;

    unnotedId        ;
    notedId        ;

    placeholder        ;
    placeholderTemplate        ;

    params            ;

    // Wear offsets (applied to wearable models on the actor)
    manwearXOff        ;
    manwearYOff        ;
    manwearZOff        ;
    womanwearXOff        ;
    womanwearYOff        ;
    womanwearZOff        ;

    constructor(id        , cacheInfo           ) {
        super(id, cacheInfo);
        this.name = "null";
        this.zoom2d = 2000;
        this.xan2d = 0;
        this.yan2d = 0;
        this.zan2d = 0;
        this.offsetX2d = 0;
        this.offsetY2d = 0;
        this.stackability = ObjStackability.SOMETIMES;
        this.price = 1;
        this.wearPos = -1;
        this.wearPos2 = -1;
        this.isMembers = false;
        this.groundActions = [null, null, "Take", null, null];
        this.inventoryActions = [null, null, null, null, "Drop"];
        this.subops = null;
        this.shiftClickIndex = -2;
        this.maleModel = -1;
        this.maleModel1 = -1;
        this.maleOffset = 0;
        this.femaleModel = -1;
        this.femaleModel1 = -1;
        this.femaleOffset = 0;
        this.maleModel2 = -1;
        this.femaleModel2 = -1;
        this.maleHeadModel = -1;
        this.maleHeadModel2 = -1;
        this.femaleHeadModel = -1;
        this.femaleHeadModel2 = -1;
        this.wearPos3 = -1;
        this.note = -1;
        this.noteTemplate = -1;
        this.resizeX = 128;
        this.resizeY = 128;
        this.resizeZ = 128;
        this.ambient = 0;
        this.contrast = 0;
        this.team = 0;
        this.isTradable = false;
        this.isUnlockable = false;
        this.weight = 0;
        this.unnotedId = -1;
        this.notedId = -1;
        this.placeholder = -1;
        this.placeholderTemplate = -1;

        this.model = 0;

        this.manwearXOff = 0;
        this.manwearYOff = 0;
        this.manwearZOff = 0;
        this.womanwearXOff = 0;
        this.womanwearYOff = 0;
        this.womanwearZOff = 0;
    }

    isLargeModelId()          {
        return this.cacheInfo.game === "runescape" && this.cacheInfo.revision >= 670;
    }

    readModelId(buffer            )         {
        return this.isLargeModelId() ? buffer.readBigSmart() : buffer.readUnsignedShort();
    }

             decodeOpcode(opcode        , buffer            )       {
        if (opcode === 1) {
            this.model = this.readModelId(buffer);
        } else if (opcode === 2) {
            this.name = this.readString(buffer);
        } else if (opcode === 3) {
            this.examine = this.readString(buffer);
        } else if (opcode === 4) {
            this.zoom2d = buffer.readUnsignedShort();
        } else if (opcode === 5) {
            this.xan2d = buffer.readUnsignedShort();
        } else if (opcode === 6) {
            this.yan2d = buffer.readUnsignedShort();
        } else if (opcode === 7) {
            this.offsetX2d = buffer.readUnsignedShort();
            if (this.offsetX2d > 32767) {
                this.offsetX2d -= 65536;
            }
        } else if (opcode === 8) {
            this.offsetY2d = buffer.readUnsignedShort();
            if (this.offsetY2d > 32767) {
                this.offsetY2d -= 65536;
            }
        } else if (opcode === 9) {
            this.op9 = this.readString(buffer);
        } else if (opcode === 10) {
            buffer.readUnsignedShort();
        } else if (opcode === 11) {
            this.stackability = ObjStackability.ALWAYS;
        } else if (opcode === 12) {
            this.price = buffer.readInt();
        } else if (opcode === 13) {
            this.wearPos = buffer.readUnsignedByte();
        } else if (opcode === 14) {
            this.wearPos2 = buffer.readUnsignedByte();
        } else if (opcode === 15) {
            // Rev 241: explicitly not tradeable (`tradeable=no`).
            this.isTradable = false;
        } else if (opcode === 16) {
            this.isMembers = true;
        } else if (opcode === 23) {
            this.maleModel = this.readModelId(buffer);
            this.maleOffset = buffer.readUnsignedByte();
        } else if (opcode === 24) {
            this.maleModel1 = this.readModelId(buffer);
        } else if (opcode === 25) {
            this.femaleModel = this.readModelId(buffer);
            this.femaleOffset = buffer.readUnsignedByte();
        } else if (opcode === 26) {
            this.femaleModel1 = this.readModelId(buffer);
        } else if (opcode === 27) {
            this.wearPos3 = buffer.readUnsignedByte();
        } else if (opcode >= 30 && opcode < 35) {
            this.groundActions[opcode - 30] = this.readString(buffer);
            if (this.groundActions[opcode - 30]?.toLowerCase() === "hidden") {
                this.groundActions[opcode - 30] = null;
            }
        } else if (opcode >= 35 && opcode < 40) {
            const index = opcode - 35;
            const action = this.readString(buffer);
            if (
                index === 4 &&
                action.toLowerCase() === "revert" &&
                this.inventoryActions[4]?.toLowerCase() === "drop"
            ) {
                const spare = this.inventoryActions.slice(0, 4).lastIndexOf(null);
                if (spare >= 0) {
                    this.inventoryActions[spare] = action;
                } else {
                    this.inventoryActions[index] = action;
                }
            } else {
                this.inventoryActions[index] = action;
            }
        } else if (opcode === 40) {
            const count = buffer.readUnsignedByte();
            this.recolorFrom = new Array(count);
            this.recolorTo = new Array(count);

            for (let i = 0; i < count; i++) {
                this.recolorFrom[i] = buffer.readUnsignedShort();
                this.recolorTo[i] = buffer.readUnsignedShort();
            }
        } else if (opcode === 41) {
            const count = buffer.readUnsignedByte();
            this.retextureFrom = new Array(count);
            this.retextureTo = new Array(count);

            for (let i = 0; i < count; i++) {
                this.retextureFrom[i] = buffer.readUnsignedShort();
                this.retextureTo[i] = buffer.readUnsignedShort();
            }
        } else if (opcode === 42) {
            this.shiftClickIndex = buffer.readByte();
        } else if (opcode === 43) {
            const opId = buffer.readUnsignedByte();
            if (!this.subops) {
                this.subops = new Array(5).fill(null);
            }
            const validOp = opId >= 0 && opId < 5;
            if (validOp && !this.subops[opId]) {
                this.subops[opId] = new Array(20).fill(null);
            }
            while (true) {
                const subopId = buffer.readUnsignedByte() - 1;
                if (subopId === -1) {
                    break;
                }
                const text = this.readString(buffer);
                if (validOp && subopId >= 0 && subopId < 20) {
                    this.subops[opId] [subopId] = text;
                }
            }
        } else if (opcode === 44) {
            this.model = buffer.readInt();
        } else if (opcode === 45) {
            this.maleModel = buffer.readInt();
            this.maleOffset = buffer.readUnsignedByte();
        } else if (opcode === 46) {
            this.maleModel1 = buffer.readInt();
        } else if (opcode === 47) {
            this.maleModel2 = buffer.readInt();
        } else if (opcode === 48) {
            this.femaleModel = buffer.readInt();
            this.femaleOffset = buffer.readUnsignedByte();
        } else if (opcode === 49) {
            this.femaleModel1 = buffer.readInt();
        } else if (opcode === 50) {
            this.femaleModel2 = buffer.readInt();
        } else if (opcode === 51) {
            this.maleHeadModel = buffer.readInt();
        } else if (opcode === 52) {
            this.maleHeadModel2 = buffer.readInt();
        } else if (opcode === 53) {
            this.femaleHeadModel = buffer.readInt();
        } else if (opcode === 54) {
            this.femaleHeadModel2 = buffer.readInt();
        } else if (opcode === 65) {
            this.isTradable = true;
        } else if (opcode === 160) {
            // Rev 241: `stackable=never`.
            this.stackability = ObjStackability.NEVER;
        } else if (opcode === 161) {
            // Rev 241: a list of ids (unused by the 241 cache).
            const count = buffer.readUnsignedShort();
            for (let i = 0; i < count; i++) buffer.readUnsignedShort();
        } else if (opcode === 251) {
            this.isUnlockable = true;
        } else if (opcode === 69) {
            // OSRS newer: small flag; consume a byte to maintain alignment.
            buffer.readUnsignedByte();
        } else if (opcode === 68) {
            // OSRS newer: short value placeholder (e.g., map icon or similar metadata)
            // Consume to keep stream alignment.
            buffer.readUnsignedShort();
        } else if (opcode === 66) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 72) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 80) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 81) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 82) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 83) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 84) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 85) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 86) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 87) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 70) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 71) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 76) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 77) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 67) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 116) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 117) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 118) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 119) {
            // OSRS newer: short value placeholder
            buffer.readUnsignedShort();
        } else if (opcode === 88) {
            // OSRS newer: small flag; consume a byte to maintain alignment.
            buffer.readUnsignedByte();
        } else if (opcode === 74) {
            // OSRS newer: small flag; consume a byte to maintain alignment.
            buffer.readUnsignedByte();
        } else if (opcode === 99) {
            // Rev 241 recolall: one colour for the whole model (unused by the 241 cache).
            buffer.readUnsignedShort();
        } else if (opcode === 75) {
            this.weight = buffer.readShort();
        } else if (opcode === 78) {
            this.maleModel2 = this.readModelId(buffer);
        } else if (opcode === 79) {
            this.femaleModel2 = this.readModelId(buffer);
        } else if (opcode === 90) {
            this.maleHeadModel = this.readModelId(buffer);
        } else if (opcode === 91) {
            this.femaleHeadModel = this.readModelId(buffer);
        } else if (opcode === 92) {
            this.maleHeadModel2 = this.readModelId(buffer);
        } else if (opcode === 93) {
            this.femaleHeadModel2 = this.readModelId(buffer);
        } else if (opcode === 94) {
            this.category = buffer.readUnsignedShort();
        } else if (opcode === 95) {
            this.zan2d = buffer.readUnsignedShort();
        } else if (opcode === 96) {
            const dummy = buffer.readUnsignedByte();
        } else if (opcode === 97) {
            this.note = buffer.readUnsignedShort();
        } else if (opcode === 98) {
            this.noteTemplate = buffer.readUnsignedShort();
        } else if (opcode >= 100 && opcode < 110) {
            if (!this.countObj) {
                this.countObj = new Array(10);
                this.countCo = new Array(10);
            }

            this.countObj[opcode - 100] = buffer.readUnsignedShort();
            this.countCo[opcode - 100] = buffer.readUnsignedShort();
        } else if (opcode === 110) {
            const raw = buffer.readUnsignedShort();
            this.resizeX = this.normalizeResize(raw);
        } else if (opcode === 111) {
            const raw = buffer.readUnsignedShort();
            this.resizeY = this.normalizeResize(raw);
        } else if (opcode === 112) {
            const raw = buffer.readUnsignedShort();
            this.resizeZ = this.normalizeResize(raw);
        } else if (opcode === 113) {
            this.ambient = buffer.readByte();
        } else if (opcode === 114) {
            this.contrast = buffer.readByte() * 5;
        } else if (opcode === 115) {
            this.team = buffer.readUnsignedByte();
        } else if (opcode === 121) {
            const lentId = buffer.readUnsignedShort();
        } else if (opcode === 122) {
            const lentTemplate = buffer.readUnsignedShort();
        } else if (opcode === 125) {
            this.manwearXOff = buffer.readByte();
            this.manwearYOff = buffer.readByte();
            this.manwearZOff = buffer.readByte();
        } else if (opcode === 126) {
            this.womanwearXOff = buffer.readByte();
            this.womanwearYOff = buffer.readByte();
            this.womanwearZOff = buffer.readByte();
        } else if (opcode === 127) {
            const cursor1op = buffer.readUnsignedByte();
            const cursor1 = buffer.readUnsignedShort();
        } else if (opcode === 128) {
            const cursor2op = buffer.readUnsignedByte();
            const cursor2 = buffer.readUnsignedShort();
        } else if (opcode === 129) {
            const cursor1iop = buffer.readUnsignedByte();
            const icursor1 = buffer.readUnsignedShort();
        } else if (opcode === 130) {
            const cursor2iop = buffer.readUnsignedByte();
            const icursor2 = buffer.readUnsignedShort();
        } else if (opcode === 132) {
            const count = buffer.readUnsignedByte();
            for (let i = 0; i < count; i++) {
                buffer.readUnsignedShort();
            }
        } else if (opcode === 139) {
            this.unnotedId = buffer.readUnsignedShort();
        } else if (opcode === 140) {
            this.notedId = buffer.readUnsignedShort();
        } else if (opcode >= 142 && opcode < 147) {
            buffer.readUnsignedShort();
        } else if (opcode === 148) {
            this.placeholder = buffer.readUnsignedShort();
        } else if (opcode === 149) {
            this.placeholderTemplate = buffer.readUnsignedShort();
        } else if (opcode >= 150 && opcode < 155) {
            buffer.readUnsignedShort();
        } else if (opcode === 200) {
            const index = buffer.readUnsignedByte();
            const subId = buffer.readUnsignedByte();
            this.readString(buffer);
        } else if (opcode === 201) {
            const index = buffer.readUnsignedByte();
            const varp = buffer.readUnsignedShort();
            const varb = buffer.readUnsignedShort();
            const min = buffer.readInt();
            const max = buffer.readInt();
            this.readString(buffer);
        } else if (opcode === 202) {
            const index = buffer.readUnsignedByte();
            const subId = buffer.readUnsignedShort();
            const varp = buffer.readUnsignedShort();
            const varb = buffer.readUnsignedShort();
            const min = buffer.readInt();
            const max = buffer.readInt();
            this.readString(buffer);
        } else if (opcode === 249) {
            this.params = Type.readParamsMap(buffer, this.params);
        } else {
            throw new Error("ObjType: Opcode " + opcode + " not implemented.");
        }
    }

            normalizeResize(raw        )         {
        // Some newer cache revisions appear to emit garbage resize values when the
        // object decoder encounters unknown opcodes.  Legitimate resize factors in
        // the live client stay within a small multiple of the default 128.  If we
        // see anything wildly outside that range, fall back to the vanilla scale
        // so that wearable models do not explode to thousands of units.
        if (raw <= 0 || raw > 1024) {
            return 128;
        }
        return raw;
    }

}
