package dev.openrune.gamevals

import java.io.DataInputStream
import java.io.File
import java.io.FileInputStream

/**
 * Snapshot of the highest OSRS cache gameval ID per table.
 *
 * IDs in `0..maxId` (inclusive) are reserved for the official cache. Custom gamevals must use
 * IDs strictly greater than the table's max.
 *
 * Written by [GamevalDumper] during `freshCache`; committed so PR CI can detect conflicts without
 * the binary `.dat` dumps.
 */
object GameValMaxIdManifest {
    const val RELATIVE_PATH = ".data/gamevals-binary/max-ids.toml"

    data class Manifest(
        val revision: Int?,
        val maxIds: Map<String, Int>,
    )

    fun path(rootDir: File): File = File(rootDir, RELATIVE_PATH)

    fun write(
        rootDir: File,
        maxIds: Map<String, Int>,
        revision: Int? = null,
    ) {
        val file = path(rootDir).apply { parentFile?.mkdirs() }
        val body =
            buildString {
                appendLine("# OSRS cache gameval max IDs per table.")
                appendLine("# IDs 0..=max are reserved; custom gamevals must be > max.")
                appendLine("# Generated by freshCache / GamevalDumper - do not hand-edit.")
                appendLine("# dbcol is omitted (auto-generated from table/column defs).")
                appendLine()
                if (revision != null) {
                    appendLine("revision = $revision")
                    appendLine()
                }
                appendLine("[max_ids]")
                maxIds.toSortedMap().forEach { (table, maxId) ->
                    appendLine("$table = $maxId")
                }
            }
        file.writeText(body)
    }

    fun load(rootDir: File): Manifest {
        val file = path(rootDir)
        require(file.isFile) {
            "Missing gameval max-id manifesto at ${file.invariantSeparatorsPath}. " +
                "Run :or-cache:freshCache to generate it."
        }
        return parse(file.readText())
    }

    fun parse(text: String): Manifest {
        var revision: Int? = null
        val maxIds = linkedMapOf<String, Int>()
        var inMaxIds = false

        text.lineSequence().forEach { raw ->
            val line = raw.trim()
            if (line.isEmpty() || line.startsWith("#")) return@forEach
            when {
                line == "[max_ids]" -> inMaxIds = true
                line.startsWith("[") -> inMaxIds = false
                line.startsWith("revision") && '=' in line && !inMaxIds -> {
                    revision = line.substringAfter('=').trim().toIntOrNull()
                }
                inMaxIds && '=' in line -> {
                    val key = line.substringBefore('=').trim()
                    val value =
                        line.substringAfter('=').trim().toIntOrNull()
                            ?: error("Invalid max id for '$key': $line")
                    maxIds[key] = value
                }
            }
        }

        require(maxIds.isNotEmpty()) { "Gameval max-id manifesto has no [max_ids] entries." }
        return Manifest(revision, maxIds)
    }

    /** Decode max IDs from `gamevals.dat` only (`dbcol` / columns dat is auto-generated). */
    fun readMaxIdsFromDats(binaryDir: File): Map<String, Int> {
        val maxIds = linkedMapOf<String, Int>()
        val dat = File(binaryDir, "gamevals.dat")
        require(dat.isFile) { "Missing gamevals.dat under ${binaryDir.invariantSeparatorsPath}" }
        mergeMaxIdsFromDat(dat, maxIds)
        maxIds.remove("dbcol")
        return maxIds
    }

    fun writeFromDats(
        rootDir: File,
        revision: Int? = null,
    ) {
        val binaryDir = File(rootDir, ".data/gamevals-binary")
        write(rootDir, readMaxIdsFromDats(binaryDir), revision)
    }

    private fun mergeMaxIdsFromDat(
        datFile: File,
        maxIds: MutableMap<String, Int>,
    ) {
        DataInputStream(FileInputStream(datFile)).use { input ->
            val tableCount = input.readInt()
            repeat(tableCount) {
                val nameLength = input.readShort().toInt()
                val nameBytes = ByteArray(nameLength)
                input.readFully(nameBytes)
                val tableName = String(nameBytes, Charsets.UTF_8)

                val itemCount = input.readInt()
                var max = maxIds[tableName] ?: -1
                repeat(itemCount) {
                    val itemLength = input.readShort().toInt()
                    val itemBytes = ByteArray(itemLength)
                    input.readFully(itemBytes)
                    val itemString = String(itemBytes, Charsets.UTF_8)
                    val id =
                        itemString.substringAfterLast('=').trim().toIntOrNull()
                            ?: return@repeat
                    if (id > max) max = id
                }
                maxIds[tableName] = max
            }
        }
    }
}
