[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_11_50"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_13_27"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_13_42"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_16_50"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_18_42"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_19_18"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_21_23"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_34_21"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_35_46"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_37_43"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_38_29"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_40_51"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_44_26"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_44_47"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_46_18"

[[spawn]]
npc = "npc.mm_warehouse_spider"
coords = "0_42_143_9_19"

