[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_11_4"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_12_60"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_13_50"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_14_15"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_2_49"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_30_4"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_36_4"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_37_12"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_3_12"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_41_2"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_42_59"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_48_60"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_49_58"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_4_5"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_59_54"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_5_53"

[[spawn]]
npc = "npc.agilityarena_non_combat_bat"
coords = "3_43_149_6_16"

