[[spawn]]
npc = "npc.chaos_temple_monk_wilderness"
coords = "0_47_161_12_51"

[[spawn]]
npc = "npc.chaos_temple_monk_wilderness"
coords = "0_47_161_52_29"

[[spawn]]
npc = "npc.dwarf_chaos"
coords = "0_47_161_21_9"

[[spawn]]
npc = "npc.dwarf_chaos"
coords = "0_47_161_22_4"

[[spawn]]
npc = "npc.dwarf_chaos"
coords = "0_47_161_26_6"

[[spawn]]
npc = "npc.dwarf_chaos"
coords = "0_47_161_28_7"

[[spawn]]
npc = "npc.firegiant"
coords = "0_47_161_38_37"

[[spawn]]
npc = "npc.firegiant"
coords = "0_47_161_44_43"

[[spawn]]
npc = "npc.firegiant2"
coords = "0_47_161_39_40"

[[spawn]]
npc = "npc.firegiant2"
coords = "0_47_161_45_34"

[[spawn]]
npc = "npc.firegiant3"
coords = "0_47_161_41_34"

[[spawn]]
npc = "npc.giant"
coords = "0_47_161_37_17"

[[spawn]]
npc = "npc.giant2"
coords = "0_47_161_34_13"

[[spawn]]
npc = "npc.giant3"
coords = "0_47_161_38_11"

[[spawn]]
npc = "npc.giant4"
coords = "0_47_161_37_7"

[[spawn]]
npc = "npc.giant5"
coords = "0_47_161_36_2"

[[spawn]]
npc = "npc.giant6"
coords = "0_47_161_37_4"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_11_9"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_12_18"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_12_25"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_17_26"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_18_35"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_20_23"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_21_30"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_22_42"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_24_38"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_31_39"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_7_14"

[[spawn]]
npc = "npc.shadow_spider"
coords = "0_47_161_8_19"

