[[spawn]]
npc = "npc.varlamore_cockatrice_moon01"
coords = "0_21_151_10_33"

[[spawn]]
npc = "npc.varlamore_cockatrice_moon01"
coords = "0_21_151_11_19"

[[spawn]]
npc = "npc.varlamore_cockatrice_moon01"
coords = "0_21_151_12_13"

[[spawn]]
npc = "npc.varlamore_cockatrice_moon01"
coords = "0_21_151_14_17"

[[spawn]]
npc = "npc.varlamore_cockatrice_moon01"
coords = "0_21_151_14_36"

[[spawn]]
npc = "npc.varlamore_cockatrice_moon01"
coords = "0_21_151_15_23"

[[spawn]]
npc = "npc.varlamore_cockatrice_moon01"
coords = "0_21_151_15_30"

[[spawn]]
npc = "npc.varlamore_cockatrice_moon01"
coords = "0_21_151_8_16"

## Streambound Cavern Roof Lights Larger

[[spawn]]
npc = "npc.varlamore_cockatrice_moon01"
coords = "0_21_151_11_28"

## Streambound Cavern Roof Lights Larger End

