[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_10_15"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_10_44"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_10_45"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_11_16"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_11_20"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_11_26"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_11_59"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_11_9"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_12_23"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_13_11"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_13_14"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_14_12"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_15_38"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_15_55"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_16_50"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_17_41"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_18_48"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_18_54"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_19_50"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_2_24"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_2_47"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_3_43"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_4_18"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_4_20"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_4_29"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_4_39"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_4_44"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_4_46"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_4_58"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_5_25"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_5_35"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_5_44"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_5_50"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_6_22"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_6_52"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_6_59"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_7_13"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_7_14"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_7_21"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_7_25"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_7_33"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_8_24"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_8_44"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_8_50"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_8_54"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_9_10"

[[spawn]]
npc = "npc.elem1_qip_earth_elemental_rock_version_rock"
coords = "0_42_154_9_59"

[[spawn]]
npc = "npc.elemental_air"
coords = "0_42_154_45_31"

[[spawn]]
npc = "npc.elemental_air"
coords = "0_42_154_45_38"

[[spawn]]
npc = "npc.elemental_air"
coords = "0_42_154_46_35"

[[spawn]]
npc = "npc.elemental_air"
coords = "0_42_154_47_37"

[[spawn]]
npc = "npc.elemental_air"
coords = "0_42_154_48_35"

[[spawn]]
npc = "npc.elemental_air"
coords = "0_42_154_50_33"

[[spawn]]
npc = "npc.elemental_air"
coords = "0_42_154_50_38"

[[spawn]]
npc = "npc.elemental_earth"
coords = "0_42_154_11_12"

[[spawn]]
npc = "npc.elemental_earth"
coords = "0_42_154_11_55"

[[spawn]]
npc = "npc.elemental_earth"
coords = "0_42_154_12_19"

[[spawn]]
npc = "npc.elemental_earth"
coords = "0_42_154_13_45"

[[spawn]]
npc = "npc.elemental_earth"
coords = "0_42_154_13_49"

[[spawn]]
npc = "npc.elemental_earth"
coords = "0_42_154_5_23"

[[spawn]]
npc = "npc.elemental_earth"
coords = "0_42_154_5_48"

[[spawn]]
npc = "npc.elemental_earth"
coords = "0_42_154_6_16"

[[spawn]]
npc = "npc.elemental_earth"
coords = "0_42_154_7_11"

[[spawn]]
npc = "npc.elemental_earth"
coords = "0_42_154_8_52"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_42_154_23_21"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_42_154_26_19"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_42_154_28_22"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_42_154_29_18"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_42_154_31_22"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_42_154_32_19"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_42_154_35_21"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_42_154_36_23"

[[spawn]]
npc = "npc.elemental_water"
coords = "0_42_154_25_48"

[[spawn]]
npc = "npc.elemental_water"
coords = "0_42_154_27_50"

[[spawn]]
npc = "npc.elemental_water"
coords = "0_42_154_30_46"

[[spawn]]
npc = "npc.elemental_water"
coords = "0_42_154_30_48"

[[spawn]]
npc = "npc.elemental_water"
coords = "0_42_154_34_47"

[[spawn]]
npc = "npc.elemental_water"
coords = "0_42_154_38_48"

[[spawn]]
npc = "npc.elemental_water"
coords = "0_42_154_41_48"

