[[spawn]]
npc = "npc.0_43_51_saltfish"
coords = "0_43_51_37_9"

[[spawn]]
npc = "npc.0_43_51_saltfish"
coords = "0_43_51_38_9"

[[spawn]]
npc = "npc.0_43_51_saltfish"
coords = "0_43_51_42_19"

[[spawn]]
npc = "npc.0_43_51_saltfish"
coords = "0_43_51_43_15"

[[spawn]]
npc = "npc.bailey"
coords = "0_43_51_13_12"

[[spawn]]
npc = "npc.fishplatform1"
coords = "0_43_51_22_9"

[[spawn]]
npc = "npc.fishplatform1"
coords = "0_43_51_23_20"

[[spawn]]
npc = "npc.fishplatform1"
coords = "1_43_51_29_26"

[[spawn]]
npc = "npc.fishplatform1"
coords = "1_43_51_33_20"

[[spawn]]
npc = "npc.fishplatform2"
coords = "0_43_51_18_20"

[[spawn]]
npc = "npc.fishplatform2"
coords = "0_43_51_42_15"

[[spawn]]
npc = "npc.fishplatform2"
coords = "1_43_51_16_21"

[[spawn]]
npc = "npc.fishplatform2"
coords = "1_43_51_32_13"

[[spawn]]
npc = "npc.fishplatform3"
coords = "0_43_51_26_27"

[[spawn]]
npc = "npc.fishplatform3"
coords = "1_43_51_21_18"

[[spawn]]
npc = "npc.fishplatform3"
coords = "1_43_51_35_16"

[[spawn]]
npc = "npc.kennith"
coords = "1_43_51_14_24"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_11_20"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_16_10"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_16_24"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_18_13"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_18_26"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_19_15"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_22_27"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_26_21"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_29_14"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_29_21"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_31_11"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_32_15"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_33_12"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_33_23"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_36_10"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_41_11"

[[spawn]]
npc = "npc.seaslug"
coords = "0_43_51_41_16"

[[spawn]]
npc = "npc.seaslug"
coords = "1_43_51_16_18"

[[spawn]]
npc = "npc.seaslug"
coords = "1_43_51_18_18"

[[spawn]]
npc = "npc.seaslug"
coords = "1_43_51_21_27"

[[spawn]]
npc = "npc.seaslug"
coords = "1_43_51_28_19"

[[spawn]]
npc = "npc.seaslug"
coords = "1_43_51_28_26"

[[spawn]]
npc = "npc.seaslug"
coords = "1_43_51_31_22"

[[spawn]]
npc = "npc.seaslug"
coords = "1_43_51_32_15"

[[spawn]]
npc = "npc.seaslug"
coords = "1_43_51_33_18"

[[spawn]]
npc = "npc.slug2_holgart_jeb"
coords = "0_43_51_30_12"

[[spawn]]
npc = "npc.slug2_invisi_lobster"
coords = "0_43_51_16_22"

[[spawn]]
npc = "npc.slug2_invisi_lobster"
coords = "0_43_51_25_14"

[[spawn]]
npc = "npc.slug2_invisi_lobster"
coords = "0_43_51_31_25"

[[spawn]]
npc = "npc.slug2_invisi_lobster"
coords = "0_43_51_32_13"

[[spawn]]
npc = "npc.slug2_invisi_lobster"
coords = "1_43_51_16_25"

[[spawn]]
npc = "npc.slug2_invisi_lobster"
coords = "1_43_51_28_24"

