[[spawn]]
npc = "npc.mole_baby_01"
coords = "0_27_80_11_57"

[[spawn]]
npc = "npc.mole_baby_01"
coords = "0_27_80_28_44"

[[spawn]]
npc = "npc.mole_baby_01"
coords = "0_27_80_33_41"

[[spawn]]
npc = "npc.mole_baby_01"
coords = "0_27_80_37_58"

[[spawn]]
npc = "npc.mole_baby_01"
coords = "0_27_80_9_36"

[[spawn]]
npc = "npc.mole_baby_01"
coords = "0_27_81_13_4"

[[spawn]]
npc = "npc.mole_baby_01"
coords = "0_27_81_44_16"

[[spawn]]
npc = "npc.mole_baby_01"
coords = "0_27_81_48_57"

[[spawn]]
npc = "npc.mole_baby_01"
coords = "0_27_81_8_43"

[[spawn]]
npc = "npc.mole_baby_02"
coords = "0_27_80_28_61"

[[spawn]]
npc = "npc.mole_baby_02"
coords = "0_27_80_32_32"

[[spawn]]
npc = "npc.mole_baby_02"
coords = "0_27_80_51_45"

[[spawn]]
npc = "npc.mole_baby_02"
coords = "0_27_80_52_60"

[[spawn]]
npc = "npc.mole_baby_02"
coords = "0_27_80_53_32"

[[spawn]]
npc = "npc.mole_baby_02"
coords = "0_27_81_18_37"

[[spawn]]
npc = "npc.mole_baby_02"
coords = "0_27_81_27_15"

[[spawn]]
npc = "npc.mole_baby_02"
coords = "0_27_81_42_42"

[[spawn]]
npc = "npc.mole_baby_02"
coords = "0_27_81_55_7"

[[spawn]]
npc = "npc.mole_baby_02"
coords = "0_27_81_6_18"

[[spawn]]
npc = "npc.mole_baby_03"
coords = "0_27_80_14_43"

[[spawn]]
npc = "npc.mole_baby_03"
coords = "0_27_80_18_32"

[[spawn]]
npc = "npc.mole_baby_03"
coords = "0_27_80_18_51"

[[spawn]]
npc = "npc.mole_baby_03"
coords = "0_27_80_34_62"

[[spawn]]
npc = "npc.mole_baby_03"
coords = "0_27_80_36_44"

[[spawn]]
npc = "npc.mole_baby_03"
coords = "0_27_80_42_54"

[[spawn]]
npc = "npc.mole_baby_03"
coords = "0_27_81_32_31"

[[spawn]]
npc = "npc.mole_baby_03"
coords = "0_27_81_35_12"

[[spawn]]
npc = "npc.mole_baby_03"
coords = "0_27_81_50_48"

[[spawn]]
npc = "npc.mole_baby_03"
coords = "0_27_81_51_26"

[[spawn]]
npc = "npc.mole_baby_03"
coords = "0_27_81_9_25"

[[spawn]]
npc = "npc.mole_giant"
coords = "0_27_81_31_5"

