[[spawn]]
npc = "npc.fairytale2_gorak"
coords = "0_47_83_15_27"

[[spawn]]
npc = "npc.fairytale2_gorak"
coords = "0_47_83_15_38"

[[spawn]]
npc = "npc.fairytale2_gorak"
coords = "0_47_83_25_31"

[[spawn]]
npc = "npc.fairytale2_gorak"
coords = "0_47_83_27_38"

[[spawn]]
npc = "npc.fairytale2_gorak"
coords = "0_47_83_29_18"

[[spawn]]
npc = "npc.fairytale2_gorak"
coords = "0_47_83_30_32"

[[spawn]]
npc = "npc.fairytale2_gorak"
coords = "0_47_83_30_49"

[[spawn]]
npc = "npc.fairytale2_gorak"
coords = "0_47_83_32_39"

[[spawn]]
npc = "npc.fairytale2_gorak"
coords = "0_47_83_34_35"

[[spawn]]
npc = "npc.fairytale2_gorak"
coords = "0_47_83_44_32"

[[spawn]]
npc = "npc.fairytale2_gorak"
coords = "0_47_83_44_41"

