[[spawn]]
npc = "npc.bat"
coords = "0_38_154_11_6"

[[spawn]]
npc = "npc.bat"
coords = "0_38_154_19_4"

[[spawn]]
npc = "npc.bat"
coords = "0_38_154_28_4"

[[spawn]]
npc = "npc.bat"
coords = "0_38_154_37_7"

[[spawn]]
npc = "npc.giantrat"
coords = "0_38_154_18_47"

[[spawn]]
npc = "npc.giantrat"
coords = "0_38_154_18_56"

[[spawn]]
npc = "npc.giantrat"
coords = "0_38_154_24_54"

[[spawn]]
npc = "npc.giantrat"
coords = "0_38_154_32_52"

[[spawn]]
npc = "npc.giantrat"
coords = "0_38_154_34_25"

[[spawn]]
npc = "npc.giantrat"
coords = "0_38_154_45_40"

[[spawn]]
npc = "npc.giantrat"
coords = "0_38_154_50_58"

[[spawn]]
npc = "npc.giantrat"
coords = "0_38_154_51_32"

[[spawn]]
npc = "npc.giantrat"
coords = "0_38_154_56_56"

[[spawn]]
npc = "npc.gnomekingsguard"
coords = "0_38_154_29_39"

[[spawn]]
npc = "npc.gnomekingsguard"
coords = "0_38_154_33_38"

[[spawn]]
npc = "npc.gnomekingsguard"
coords = "0_38_154_33_43"

[[spawn]]
npc = "npc.grandtree_narnode"
coords = "0_38_154_32_41"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_10_35"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_11_26"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_15_35"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_19_26"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_20_22"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_21_34"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_24_16"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_24_2"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_24_27"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_26_21"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_28_7"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_30_34"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_35_4"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_38_32"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_43_10"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_44_31"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_49_13"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_50_9"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_56_5"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_57_10"

[[spawn]]
npc = "npc.rat"
coords = "0_38_154_6_29"

