[[spawn]]
npc = "npc.frost_dragon"
coords = "0_44_163_35_23"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_44_163_35_39"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_44_163_37_30"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_44_163_44_34"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_44_163_46_17"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_44_163_46_26"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_44_163_48_41"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_44_163_56_31"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_44_163_57_19"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_44_163_58_39"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_45_163_10_22"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_45_163_14_29"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_45_163_15_35"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_45_163_18_24"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_45_163_18_41"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_45_163_20_33"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_45_163_25_27"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_45_163_31_26"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_45_163_33_33"

[[spawn]]
npc = "npc.frost_dragon"
coords = "0_45_163_9_34"

[[spawn]]
npc = "npc.jelly_tapoyauik"
coords = "0_45_163_18_16"

[[spawn]]
npc = "npc.jelly_tapoyauik"
coords = "0_45_163_20_13"

[[spawn]]
npc = "npc.jelly_tapoyauik"
coords = "0_45_163_22_17"

[[spawn]]
npc = "npc.jelly_tapoyauik"
coords = "0_45_163_23_12"

[[spawn]]
npc = "npc.jelly_tapoyauik"
coords = "0_45_163_25_14"

[[spawn]]
npc = "npc.jelly_tapoyauik"
coords = "0_45_163_37_46"

[[spawn]]
npc = "npc.jelly_tapoyauik"
coords = "0_45_163_39_44"

[[spawn]]
npc = "npc.jelly_tapoyauik"
coords = "0_45_163_39_49"

[[spawn]]
npc = "npc.jelly_tapoyauik"
coords = "0_45_163_41_48"

[[spawn]]
npc = "npc.jelly_tapoyauik"
coords = "0_45_163_42_45"

