[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_35_93_11_33"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_35_93_15_40"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_35_93_16_20"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_35_93_22_54"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_35_93_33_42"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_35_93_41_13"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_35_93_50_55"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_35_93_52_34"

