[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "1_39_93_35_13"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "1_39_93_3_19"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "1_39_93_3_41"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "1_39_93_41_38"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_39_93_15_25"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_39_93_24_14"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_39_93_34_2"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_39_93_41_46"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_39_93_4_49"

[[spawn]]
npc = "npc.hallowed_bat_01"
coords = "2_39_93_56_40"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "1_39_93_38_46"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "1_39_93_50_12"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "1_39_93_51_39"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "1_39_93_7_26"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "1_39_93_7_48"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "2_39_93_21_40"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "2_39_93_23_3"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "2_39_93_39_14"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "2_39_93_3_41"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "2_39_93_41_39"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "2_39_93_52_47"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "2_39_93_52_9"

[[spawn]]
npc = "npc.hallowed_bat_02"
coords = "2_39_93_8_28"

[[spawn]]
npc = "npc.hallowed_spider_01"
coords = "1_39_93_59_32"

[[spawn]]
npc = "npc.hallowed_spider_01"
coords = "2_39_93_15_38"

[[spawn]]
npc = "npc.hallowed_spider_01"
coords = "2_39_93_30_63"

[[spawn]]
npc = "npc.hallowed_spider_01"
coords = "2_39_93_59_18"

[[spawn]]
npc = "npc.hallowed_spider_02"
coords = "1_39_93_59_48"

[[spawn]]
npc = "npc.hallowed_spider_02"
coords = "2_39_93_3_11"

[[spawn]]
npc = "npc.hallowed_spider_02"
coords = "2_39_93_42_8"

[[spawn]]
npc = "npc.hallowed_spider_02"
coords = "2_39_93_50_56"

