[[spawn]]
npc = "npc.kalphite_larva"
coords = "0_51_148_32_25"

[[spawn]]
npc = "npc.kalphite_larva"
coords = "0_51_148_32_28"

[[spawn]]
npc = "npc.kalphite_larva"
coords = "0_51_148_32_34"

[[spawn]]
npc = "npc.kalphite_larva"
coords = "0_51_148_33_37"

[[spawn]]
npc = "npc.kalphite_larva"
coords = "0_51_148_34_23"

[[spawn]]
npc = "npc.kalphite_larva"
coords = "0_51_148_35_32"

[[spawn]]
npc = "npc.kalphite_larva"
coords = "0_51_148_36_28"

[[spawn]]
npc = "npc.kalphite_larva"
coords = "0_51_148_36_35"

[[spawn]]
npc = "npc.kalphite_larva"
coords = "0_51_148_37_25"

[[spawn]]
npc = "npc.kalphite_lord_strongholdcave"
coords = "0_51_148_11_6"

[[spawn]]
npc = "npc.kalphite_lord_strongholdcave"
coords = "0_51_148_13_20"

[[spawn]]
npc = "npc.kalphite_lord_strongholdcave"
coords = "0_51_148_14_13"

[[spawn]]
npc = "npc.kalphite_lord_strongholdcave"
coords = "0_51_148_20_9"

[[spawn]]
npc = "npc.kalphite_lord_strongholdcave"
coords = "0_51_148_4_10"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_35_60"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_37_56"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_41_44"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_41_50"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_45_57"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_45_8"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_47_49"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_51_56"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_51_9"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_53_4"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_53_50"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_54_14"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_58_11"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_58_6"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_148_63_10"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_149_39_1"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_51_149_45_1"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_52_148_1_15"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_52_148_5_18"

[[spawn]]
npc = "npc.kalphite_soldier_strongholdcave"
coords = "0_52_148_8_22"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_13_40"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_13_50"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_14_45"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_17_49"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_17_54"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_18_44"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_20_52"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_51_30"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_54_24"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_55_35"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_58_30"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_59_23"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_60_38"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_63_28"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_63_34"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_8_42"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_51_148_9_47"

[[spawn]]
npc = "npc.kalphite_worker_strongholdcave"
coords = "0_52_148_3_29"

[[spawn]]
npc = "npc.slayer_cave_entomologist"
coords = "0_51_148_43_34"

