[[spawn]]
npc = "npc.farming_tools_leprechaun"
coords = "0_40_50_59_21"

## Ardougne Monastery

[[spawn]]
npc = "npc.brother_omad"
coords = "0_40_50_44_9"

[[spawn]]
npc = "npc.monk_ardougne"
coords = "0_40_50_46_17"

[[spawn]]
npc = "npc.monk_ardougne"
coords = "0_40_50_48_9"

## Kandarin Monastery Wings

[[spawn]]
npc = "npc.monk_ardougne"
coords = "0_40_50_58_9"

[[spawn]]
npc = "npc.monk_ardougne"
coords = "1_40_50_35_10"

## Kandarin Monastery Wings End

