[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_10_57"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_12_57"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_14_56"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_14_57"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_16_57"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_16_61"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_17_52"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_18_55"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_18_59"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_19_51"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_20_53"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_21_47"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_22_49"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_25_50"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_26_48"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_28_51"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_29_50"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_31_52"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_33_54"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_35_52"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_35_56"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_37_51"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_39_55"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_39_57"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_42_56"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_44_56"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_45_59"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_52_60"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_54_62"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_57_60"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_57_63"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_7_59"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_142_8_62"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_23_1"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_27_4"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_28_14"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_29_13"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_29_5"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_30_9"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_32_13"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_32_20"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_33_15"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_35_21"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_36_15"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_38_13"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_39_26"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_40_15"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_40_24"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_42_14"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_42_28"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_43_11"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_46_28"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_48_27"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_49_11"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_51_28"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_52_29"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_52_5"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_53_4"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_53_9"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_54_1"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_54_6"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_56_28"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_57_31"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_61_1"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_61_32"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_143_63_3"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_33_16"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_34_23"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_34_31"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_35_14"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_36_15"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_36_17"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_36_21"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_36_27"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_36_33"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_37_20"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_37_36"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_38_12"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_40_36"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_43_37"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_44_11"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_46_13"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_46_37"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_48_14"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_48_36"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_49_12"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_50_16"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_51_13"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_51_16"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_51_19"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_51_39"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_53_22"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_53_25"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_53_36"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_54_28"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_54_32"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_54_41"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_55_25"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_55_34"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_56_36"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_56_40"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_57_33"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_57_38"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_59_41"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_36_144_61_45"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_10_24"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_16_19"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_18_17"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_24_17"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_24_21"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_27_12"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_28_23"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_30_10"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_31_25"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_32_11"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_34_23"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_35_9"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_36_25"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_39_11"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_3_31"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_40_13"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_40_24"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_43_26"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_44_12"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_45_26"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_47_11"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_49_27"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_4_5"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_51_26"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_52_7"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_53_25"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_55_22"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_55_24"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_56_7"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_57_21"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_59_20"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_59_37"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_59_6"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_59_8"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_60_34"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_62_22"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_62_8"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_63_20"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_8_28"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_8_4"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_143_9_7"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_12_55"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_15_56"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_17_57"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_20_57"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_21_56"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_24_54"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_26_56"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_2_50"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_30_55"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_30_57"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_34_54"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_37_57"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_38_55"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_41_59"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_43_57"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_47_55"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_49_56"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_4_52"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_37_144_9_57"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_10_15"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_10_21"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_10_27"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_10_6"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_11_11"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_11_18"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_11_24"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_12_13"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_12_5"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_12_8"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_13_17"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_13_19"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_15_12"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_15_15"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_15_6"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_16_6"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_17_12"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_17_18"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_17_8"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_1_32"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_20_10"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_20_13"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_20_14"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_3_32"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_4_12"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_4_30"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_5_33"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_5_8"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_6_16"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_6_27"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_6_29"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_7_18"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_7_31"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_7_5"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_8_14"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_8_28"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_8_32"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_9_25"

[[spawn]]
npc = "npc.mm2_maniacal_monkey_maze"
coords = "1_38_143_9_9"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_10_58"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_12_61"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_19_54"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_20_48"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_22_41"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_27_44"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_31_41"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_34_40"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_38_56"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_38_60"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_39_47"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_41_58"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_43_45"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_44_41"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_143_47_44"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_10_16"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_10_19"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_10_2"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_10_35"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_12_29"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_12_41"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_14_7"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_17_12"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_17_44"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_17_6"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_19_21"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_21_19"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_23_7"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_25_25"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_25_32"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_26_43"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_26_9"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_28_14"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_28_30"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_29_20"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_29_41"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_31_18"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_32_6"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_35_46"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_36_6"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_37_31"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_38_29"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_39_2"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_41_1"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_41_17"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_41_42"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_43_44"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_45_16"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_45_21"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_46_25"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_47_38"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_48_40"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_51_29"

[[spawn]]
npc = "npc.mm2_monkey_archer_maze"
coords = "1_37_144_52_34"

