[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_22_34"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_23_39"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_23_47"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_24_43"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_25_29"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_25_35"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_25_49"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_27_32"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_27_37"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_27_41"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_28_26"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_29_29"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_29_44"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_30_36"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_31_24"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_32_33"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_32_39"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_32_49"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_33_35"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_34_24"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_34_29"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_34_42"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_35_45"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_36_35"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_36_40"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_37_27"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_39_30"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_39_37"

[[spawn]]
npc = "npc.hunting_monkey"
coords = "0_45_142_40_46"

[[spawn]]
npc = "npc.mm2_tortured_gorilla_small"
coords = "0_45_142_21_34"

[[spawn]]
npc = "npc.mm2_tortured_gorilla_small"
coords = "0_45_142_21_38"

[[spawn]]
npc = "npc.mm2_tortured_gorilla_small"
coords = "0_45_142_30_55"

[[spawn]]
npc = "npc.mm2_tortured_gorilla_small"
coords = "0_45_142_34_55"

[[spawn]]
npc = "npc.mm2_tortured_gorilla_small"
coords = "0_45_142_36_55"

[[spawn]]
npc = "npc.mm2_tortured_gorilla_small"
coords = "0_45_142_41_35"

[[spawn]]
npc = "npc.mm2_tortured_gorilla_small"
coords = "0_45_142_41_39"

