[[spawn]]
npc = "npc.bat"
coords = "0_42_152_15_6"

[[spawn]]
npc = "npc.bat"
coords = "0_42_152_42_41"

[[spawn]]
npc = "npc.bat"
coords = "0_42_152_43_35"

[[spawn]]
npc = "npc.bat"
coords = "0_42_152_43_46"

[[spawn]]
npc = "npc.bat"
coords = "0_42_152_46_42"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_12_42"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_12_46"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_12_49"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_13_53"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_15_42"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_15_46"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_15_51"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_17_29"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_17_32"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_17_38"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_18_25"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_18_35"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_18_44"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_19_28"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_19_33"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_20_30"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_5_48"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_9_45"

[[spawn]]
npc = "npc.shadow_warrior"
coords = "0_42_152_9_51"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_22_25"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_23_18"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_24_13"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_24_21"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_24_26"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_25_14"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_27_21"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_28_16"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_30_23"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_32_14"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_32_31"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_33_18"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_33_26"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_35_10"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_35_16"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_36_21"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_37_30"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_39_13"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_39_19"

[[spawn]]
npc = "npc.smallscorpion"
coords = "0_42_152_40_16"

