[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_11_27"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_14_20"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_14_37"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_15_14"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_15_31"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_28_21"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_28_27"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_31_24"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_34_21"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_34_27"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_6_22"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_7_38"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_8_16"

[[spawn]]
npc = "npc.pmoon_sulphur_nagua"
coords = "0_21_149_8_32"

