[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_27_27"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_30_22"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_34_21"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_38_22"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_40_40"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_43_28"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_43_37"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_44_31"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_45_20"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_47_22"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_48_37"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_49_30"

[[spawn]]
npc = "npc.crab_2"
coords = "0_56_43_51_27"

