[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_16_20"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_17_14"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_17_17"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_19_9"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_22_22"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_22_25"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_23_12"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_24_18"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_24_8"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_27_22"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_29_16"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_30_9"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_32_12"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_32_23"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_39_145_33_20"

