[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_11_10"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_12_32"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_15_6"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_18_28"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_18_57"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_22_11"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_24_49"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_32_32"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_33_16"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_34_9"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_36_25"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_37_36"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_39_19"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_45_49"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_45_8"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_52_39"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_53_24"

[[spawn]]
npc = "npc.contact_insectoid_mage"
coords = "0_37_66_9_47"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_10_46"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_10_7"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_16_24"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_16_35"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_20_31"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_26_16"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_27_46"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_31_35"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_32_13"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_35_28"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_38_16"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_40_36"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_42_7"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_44_46"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_46_21"

[[spawn]]
npc = "npc.contact_locust_bow"
coords = "0_37_66_9_35"

[[spawn]]
npc = "npc.contact_locust_lance"
coords = "0_37_66_12_19"

[[spawn]]
npc = "npc.contact_locust_lance"
coords = "0_37_66_19_27"

[[spawn]]
npc = "npc.contact_locust_lance"
coords = "0_37_66_20_36"

[[spawn]]
npc = "npc.contact_locust_lance"
coords = "0_37_66_23_52"

[[spawn]]
npc = "npc.contact_locust_lance"
coords = "0_37_66_30_17"

[[spawn]]
npc = "npc.contact_locust_lance"
coords = "0_37_66_32_45"

[[spawn]]
npc = "npc.contact_locust_lance"
coords = "0_37_66_35_38"

[[spawn]]
npc = "npc.contact_locust_lance"
coords = "0_37_66_39_50"

[[spawn]]
npc = "npc.contact_locust_lance"
coords = "0_37_66_41_18"

[[spawn]]
npc = "npc.contact_locust_lance"
coords = "0_37_66_6_48"

[[spawn]]
npc = "npc.contact_locust_lance"
coords = "0_37_66_8_30"

