[[spawn]]
npc = "npc.butterfly_warlock"
coords = "0_24_43_21_57"

[[spawn]]
npc = "npc.butterfly_warlock"
coords = "0_24_43_24_55"

[[spawn]]
npc = "npc.butterfly_warlock"
coords = "0_24_43_28_22"

[[spawn]]
npc = "npc.butterfly_warlock"
coords = "0_24_43_39_18"

[[spawn]]
npc = "npc.butterfly_warlock"
coords = "0_24_43_43_14"

[[spawn]]
npc = "npc.butterfly_warlock"
coords = "0_24_43_47_40"

[[spawn]]
npc = "npc.butterfly_warlock"
coords = "0_24_43_4_53"

[[spawn]]
npc = "npc.butterfly_warlock"
coords = "0_24_43_50_9"

[[spawn]]
npc = "npc.butterfly_warlock"
coords = "0_24_43_55_20"

[[spawn]]
npc = "npc.butterfly_warlock"
coords = "0_24_43_59_15"

[[spawn]]
npc = "npc.multicoloured_bird"
coords = "0_24_43_36_46"

