[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_17_6"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_21_57"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_23_15"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_24_16"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_38_56"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_42_59"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_55_8"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_56_57"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_57_10"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_58_54"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_6_12"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_6_20"

[[spawn]]
npc = "npc.elemental_fire"
coords = "0_51_146_6_39"

[[spawn]]
npc = "npc.firegiant"
coords = "0_51_146_30_31"

[[spawn]]
npc = "npc.firegiant2"
coords = "0_51_146_42_56"

[[spawn]]
npc = "npc.slayer_dust_devil_guard"
coords = "0_49_146_55_20"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_43_18"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_44_22"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_46_15"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_47_20"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_47_38"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_48_17"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_48_24"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_49_34"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_51_20"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_51_23"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_51_37"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_52_34"

[[spawn]]
npc = "npc.slayer_dustdevil"
coords = "0_49_146_53_39"

[[spawn]]
npc = "npc.slayer_pyrefiend_1"
coords = "0_51_146_2_55"

[[spawn]]
npc = "npc.slayer_pyrefiend_1"
coords = "0_51_146_6_36"

[[spawn]]
npc = "npc.slayer_pyrefiend_1"
coords = "0_51_146_7_43"

[[spawn]]
npc = "npc.slayer_pyrefiend_2"
coords = "0_51_146_10_53"

[[spawn]]
npc = "npc.slayer_pyrefiend_2"
coords = "0_51_146_11_45"

[[spawn]]
npc = "npc.slayer_pyrefiend_2"
coords = "0_51_146_15_33"

[[spawn]]
npc = "npc.slayer_pyrefiend_2"
coords = "0_51_146_19_57"

[[spawn]]
npc = "npc.slayer_pyrefiend_2"
coords = "0_51_146_21_37"

[[spawn]]
npc = "npc.slayer_pyrefiend_2"
coords = "0_51_146_24_49"

[[spawn]]
npc = "npc.slayer_pyrefiend_3"
coords = "0_51_146_13_8"

[[spawn]]
npc = "npc.slayer_pyrefiend_3"
coords = "0_51_146_16_24"

[[spawn]]
npc = "npc.slayer_pyrefiend_3"
coords = "0_51_146_7_14"

[[spawn]]
npc = "npc.slayer_pyrefiend_3"
coords = "0_51_146_9_22"

[[spawn]]
npc = "npc.slayer_pyrefiend_4"
coords = "0_51_146_25_18"

[[spawn]]
npc = "npc.slayer_pyrefiend_4"
coords = "0_51_146_34_35"

[[spawn]]
npc = "npc.slayer_pyrefiend_4"
coords = "0_51_146_38_54"

[[spawn]]
npc = "npc.slayer_pyrefiend_4"
coords = "0_51_146_38_6"

[[spawn]]
npc = "npc.slayer_pyrefiend_4"
coords = "0_51_146_52_8"

[[spawn]]
npc = "npc.slayer_pyrefiend_4"
coords = "0_51_146_54_59"

