[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_28_42"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_29_18"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_29_47"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_30_25"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_33_35"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_34_31"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_37_9"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_38_6"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_40_28"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_42_4"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_43_12"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_44_7"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_47_4"

[[spawn]]
npc = "npc.baby_custodian_stalker"
coords = "0_20_152_48_9"

