[[spawn]]
npc = "npc.blue_crab"
coords = "0_50_38_51_0"

[[spawn]]
npc = "npc.blue_crab"
coords = "0_50_39_13_18"

[[spawn]]
npc = "npc.farming_gardener_calquat_3"
coords = "0_48_37_52_36"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_50_37_55_10"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_50_37_56_5"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_50_37_56_8"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_50_37_58_11"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_50_37_59_7"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_50_37_60_5"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_50_37_61_11"

[[spawn]]
npc = "npc.hunting_chinchompa_big"
coords = "0_50_37_61_8"

[[spawn]]
npc = "npc.kingscorpion"
coords = "0_50_36_36_54"

[[spawn]]
npc = "npc.kingscorpion"
coords = "0_50_36_43_62"

[[spawn]]
npc = "npc.kingscorpion"
coords = "0_50_36_53_57"

[[spawn]]
npc = "npc.kingscorpion"
coords = "0_50_36_58_50"

[[spawn]]
npc = "npc.little_frog_nodrops"
coords = "0_49_37_52_62"

[[spawn]]
npc = "npc.little_frog_nodrops"
coords = "0_49_38_51_3"

[[spawn]]
npc = "npc.little_frog_nodrops"
coords = "0_49_38_53_9"

[[spawn]]
npc = "npc.little_frog_nodrops"
coords = "0_49_38_59_7"

[[spawn]]
npc = "npc.little_frog_nodrops"
coords = "0_50_37_10_62"

[[spawn]]
npc = "npc.little_frog_nodrops"
coords = "0_50_38_1_9"

[[spawn]]
npc = "npc.little_frog_nodrops"
coords = "0_50_38_6_3"

[[spawn]]
npc = "npc.multicoloured_bird"
coords = "0_49_38_0_52"

[[spawn]]
npc = "npc.multicoloured_bird"
coords = "0_49_38_11_57"

[[spawn]]
npc = "npc.multicoloured_bird"
coords = "0_49_38_14_51"

[[spawn]]
npc = "npc.multicoloured_bird"
coords = "0_49_38_2_48"

[[spawn]]
npc = "npc.multicoloured_bird"
coords = "0_49_38_2_59"

[[spawn]]
npc = "npc.multicoloured_bird"
coords = "0_49_38_5_55"

[[spawn]]
npc = "npc.multicoloured_bird"
coords = "0_49_38_7_44"

[[spawn]]
npc = "npc.multicoloured_bird"
coords = "0_49_38_7_52"

[[spawn]]
npc = "npc.multicoloured_bird"
coords = "0_49_38_9_48"

[[spawn]]
npc = "npc.salamander_orange"
coords = "0_48_39_47_30"

[[spawn]]
npc = "npc.salamander_orange"
coords = "0_48_39_48_34"

[[spawn]]
npc = "npc.salamander_orange"
coords = "0_48_39_50_32"

[[spawn]]
npc = "npc.salamander_orange"
coords = "0_48_39_51_34"

[[spawn]]
npc = "npc.salamander_orange"
coords = "0_48_39_51_37"

[[spawn]]
npc = "npc.salamander_orange"
coords = "0_48_39_52_30"

[[spawn]]
npc = "npc.salamander_orange"
coords = "0_48_39_53_34"

[[spawn]]
npc = "npc.salamander_orange"
coords = "0_48_39_53_38"

[[spawn]]
npc = "npc.tortugan_leff"
coords = "0_49_37_39_20"

[[spawn]]
npc = "npc.tt_raley_conch"
coords = "0_49_37_51_36"

