[[spawn]]
npc = "npc.soulbane_conf_beast"
coords = "0_51_153_38_14"

[[spawn]]
npc = "npc.soulbane_conf_beast"
coords = "0_51_153_38_24"

[[spawn]]
npc = "npc.soulbane_conf_beast"
coords = "0_51_153_40_9"

[[spawn]]
npc = "npc.soulbane_conf_beast"
coords = "0_51_153_46_4"

[[spawn]]
npc = "npc.soulbane_conf_beast"
coords = "0_51_153_48_19"

[[spawn]]
npc = "npc.soulbane_conf_beast"
coords = "0_51_153_49_13"

[[spawn]]
npc = "npc.soulbane_conf_beast"
coords = "0_51_153_49_25"

[[spawn]]
npc = "npc.soulbane_conf_beast"
coords = "0_51_153_50_5"

[[spawn]]
npc = "npc.soulbane_conf_beast"
coords = "0_51_153_55_14"

[[spawn]]
npc = "npc.soulbane_conf_beast"
coords = "0_51_153_55_8"

[[spawn]]
npc = "npc.soulbane_conf_beast"
coords = "0_51_153_57_19"

