[[spawn]]
npc = "npc.soulbane_fear_beast"
coords = "0_51_153_41_40"

[[spawn]]
npc = "npc.soulbane_fear_beast"
coords = "0_51_153_41_51"

[[spawn]]
npc = "npc.soulbane_fear_beast"
coords = "0_51_153_47_58"

[[spawn]]
npc = "npc.soulbane_fear_beast"
coords = "0_51_153_48_53"

[[spawn]]
npc = "npc.soulbane_fear_beast"
coords = "0_51_153_49_35"

[[spawn]]
npc = "npc.soulbane_fear_beast"
coords = "0_51_153_51_45"

[[spawn]]
npc = "npc.soulbane_fear_beast"
coords = "0_51_153_55_40"

[[spawn]]
npc = "npc.soulbane_fear_beast"
coords = "0_51_153_55_57"

[[spawn]]
npc = "npc.soulbane_fear_beast"
coords = "0_51_153_59_50"

[[spawn]]
npc = "npc.soulbane_less_beast3"
coords = "0_51_153_11_25"

[[spawn]]
npc = "npc.soulbane_less_beast3"
coords = "0_51_153_12_17"

[[spawn]]
npc = "npc.soulbane_less_beast3"
coords = "0_51_153_16_11"

[[spawn]]
npc = "npc.soulbane_less_beast3"
coords = "0_51_153_18_5"

[[spawn]]
npc = "npc.soulbane_less_beast3"
coords = "0_51_153_21_20"

[[spawn]]
npc = "npc.soulbane_less_beast3"
coords = "0_51_153_24_27"

[[spawn]]
npc = "npc.soulbane_less_beast3"
coords = "0_51_153_25_17"

[[spawn]]
npc = "npc.soulbane_less_beast3"
coords = "0_51_153_26_5"

[[spawn]]
npc = "npc.soulbane_less_beast3"
coords = "0_51_153_5_14"

[[spawn]]
npc = "npc.soulbane_less_beast3"
coords = "0_51_153_5_22"

[[spawn]]
npc = "npc.soulbane_less_beast3"
coords = "0_51_153_5_6"

