[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_17_29"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_18_27"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_18_33"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_19_35"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_20_20"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_20_22"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_21_40"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_22_42"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_23_17"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_25_16"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_27_44"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_29_14"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_29_45"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_31_14"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_35_44"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_36_15"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_37_17"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_37_43"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_41_20"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_41_22"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_41_37"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_42_35"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_44_28"

[[spawn]]
npc = "npc.wrath_skeleton"
coords = "0_36_75_44_30"

