group=org.rsmod
version=0.0.1-SNAPSHOT

kotlin.code.style=official
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.daemon.jvmargs=-Xmx2048m

org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx4096m -XX:MaxMetaspaceSize=1g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
