[[area]]
name = "Isle of Souls Dungeon"
area_id = "area.isle_of_souls_dungeon"
levels = [0, 1, 2, 3]

[[area.polygons]]
vertices = [
    [2112, 9280],
    [2175, 9280],
    [2175, 9343],
    [2112, 9343],
]
