package org.rsmod.content.skills.hunter.traps

enum class TrapFamily {
    Laid,
    Net,
    Deadfall,
}

enum class TrapKind(
    val family: TrapFamily,
    val trapName: String,
    val levelReq: Int,
    val setLoc: String,
    val failingLoc: String?,
    val failedLoc: String?,
    val catchRange: Int,
    val item: String? = null,
    val baseLoc: String? = null,
    val settingLoc: String? = null,
    val netLoc: String? = null,
    val maxTraps: Int? = null,
    val hunts: Boolean = true,
) {
    BirdSnare(
        family = TrapFamily.Laid,
        trapName = "bird snare",
        levelReq = 1,
        item = "obj.hunting_ojibway_bird_snare",
        setLoc = "loc.hunting_ojibway_trap",
        failingLoc = "loc.hunting_ojibway_trap_failing",
        failedLoc = "loc.hunting_ojibway_trap_broken",
        catchRange = 0,
    ),
    BoxTrap(
        family = TrapFamily.Laid,
        trapName = "box trap",
        levelReq = 27,
        item = "obj.hunting_box_trap",
        setLoc = "loc.hunting_boxtrap_empty",
        failingLoc = "loc.hunting_boxtrap_failing",
        failedLoc = "loc.hunting_boxtrap_failed",
        catchRange = 1,
    ),
    RabbitSnare(
        family = TrapFamily.Laid,
        trapName = "rabbit snare",
        levelReq = 27,
        item = "obj.hunting_snare",
        setLoc = "loc.hunting_snare",
        failingLoc = null,
        failedLoc = "loc.hunting_snare_failed",
        catchRange = 0,
        hunts = false,
    ),
    NetSwamp(
        family = TrapFamily.Net,
        trapName = "net trap",
        levelReq = 29,
        baseLoc = "loc.hunting_sapling_up_swamp",
        settingLoc = "loc.hunting_sapling_setting_swamp",
        setLoc = "loc.hunting_sapling_set_swamp",
        netLoc = "loc.hunting_sapling_net_set_swamp",
        failingLoc = "loc.hunting_sapling_failing_swamp",
        failedLoc = "loc.hunting_sapling_failed_swamp",
        catchRange = 0,
    ),
    NetOrange(
        family = TrapFamily.Net,
        trapName = "net trap",
        levelReq = 47,
        baseLoc = "loc.hunting_sapling_up_orange",
        settingLoc = "loc.hunting_sapling_setting_orange",
        setLoc = "loc.hunting_sapling_set_orange",
        netLoc = "loc.hunting_sapling_net_set_orange",
        failingLoc = "loc.hunting_sapling_failing_orange",
        failedLoc = "loc.hunting_sapling_failed_orange",
        catchRange = 0,
    ),
    NetRed(
        family = TrapFamily.Net,
        trapName = "net trap",
        levelReq = 59,
        baseLoc = "loc.hunting_sapling_up_red",
        settingLoc = "loc.hunting_sapling_setting_red",
        setLoc = "loc.hunting_sapling_set_red",
        netLoc = "loc.hunting_sapling_net_set_red",
        failingLoc = "loc.hunting_sapling_failing_red",
        failedLoc = "loc.hunting_sapling_failed_red",
        catchRange = 0,
    ),
    NetBlack(
        family = TrapFamily.Net,
        trapName = "net trap",
        levelReq = 67,
        baseLoc = "loc.hunting_sapling_up_black",
        settingLoc = "loc.hunting_sapling_setting_black",
        setLoc = "loc.hunting_sapling_set_black",
        netLoc = "loc.hunting_sapling_net_set_black",
        failingLoc = "loc.hunting_sapling_failing_black",
        failedLoc = "loc.hunting_sapling_failed_black",
        catchRange = 0,
    ),
    NetMountain(
        family = TrapFamily.Net,
        trapName = "net trap",
        levelReq = 79,
        baseLoc = "loc.hunting_sapling_up_mountain",
        settingLoc = "loc.hunting_sapling_setting_mountain",
        setLoc = "loc.hunting_sapling_set_mountain",
        netLoc = "loc.hunting_sapling_net_set_mountain",
        failingLoc = "loc.hunting_sapling_failing_mountain",
        failedLoc = "loc.hunting_sapling_failed_mountain",
        catchRange = 0,
    ),
    Deadfall(
        family = TrapFamily.Deadfall,
        trapName = "deadfall",
        levelReq = 23,
        baseLoc = "loc.hunting_deadfall_boulder",
        settingLoc = "loc.hunting_deadfall_setting",
        setLoc = "loc.hunting_deadfall_trap",
        failingLoc = "loc.hunting_deadfall_failing",
        failedLoc = null,
        catchRange = 1,
        maxTraps = 2,
    ),
    ;

    companion object {
        val laid: List<TrapKind> = entries.filter { it.family == TrapFamily.Laid }

        val placed: List<TrapKind> = entries.filter { it.baseLoc != null }
    }
}
