[gamevals.dbtable]
collection_log_categories=65507

[gamevals.dbrow]
collection_log_category_abyssal_sire=60123
collection_log_category_alchemical_hydra=60122
collection_log_category_amoxliatl=60121
collection_log_category_araxxor=60120
collection_log_category_barrows_chests=60119
collection_log_category_brutus=60118
collection_log_category_bryophyta=60117
collection_log_category_callisto_and_artio=60116
collection_log_category_cerberus=60115
collection_log_category_chaos_elemental=60114
collection_log_category_chaos_fanatic=60113
collection_log_category_commander_zilyana=60112
collection_log_category_corporeal_beast=60111
collection_log_category_crazy_archaeologist=60110
collection_log_category_dagannoth_kings=60109
collection_log_category_deranged_archaeologist=60108
collection_log_category_doom_of_mokhaiotl=60107
collection_log_category_duke_sucellus=60106
collection_log_category_the_fight_caves=60105
collection_log_category_fortis_colosseum=60104
collection_log_category_the_gauntlet=60103
collection_log_category_general_graardor=60102
collection_log_category_giant_mole=60101
collection_log_category_grotesque_guardians=60100
collection_log_category_hespori=60099
collection_log_category_the_hueycoatl=60098
collection_log_category_the_inferno=60097
collection_log_category_kalphite_queen=60096
collection_log_category_king_black_dragon=60095
collection_log_category_kraken=60094
collection_log_category_kree_arra=60093
collection_log_category_k_ril_tsutsaroth=60092
collection_log_category_the_leviathan=60091
collection_log_category_the_mad_angel=60090
collection_log_category_maggot_king=60089
collection_log_category_moons_of_peril=60088
collection_log_category_nex=60087
collection_log_category_the_nightmare=60086
collection_log_category_obor=60085
collection_log_category_phantom_muspah=60084
collection_log_category_royal_titans=60083
collection_log_category_sarachnis=60082
collection_log_category_scorpia=60081
collection_log_category_scurrius=60080
collection_log_category_shellbane_gryphon=60079
collection_log_category_skotizo=60078
collection_log_category_tempoross=60077
collection_log_category_thermonuclear_smoke_devil=60076
collection_log_category_vardorvis=60075
collection_log_category_venenatis_and_spindel=60074
collection_log_category_vet_ion_and_calvar_ion=60073
collection_log_category_vorkath=60072
collection_log_category_the_whisperer=60071
collection_log_category_wintertodt=60070
collection_log_category_yama=60069
collection_log_category_zalcano=60068
collection_log_category_zulrah=60067
collection_log_category_chambers_of_xeric=60066
collection_log_category_theatre_of_blood=60065
collection_log_category_tombs_of_amascut=60064
collection_log_category_beginner_treasure_trails=60063
collection_log_category_easy_treasure_trails=60062
collection_log_category_medium_treasure_trails=60061
collection_log_category_hard_treasure_trails=60060
collection_log_category_elite_treasure_trails=60059
collection_log_category_master_treasure_trails=60058
collection_log_category_hard_treasure_trails_rare=60057
collection_log_category_elite_treasure_trails_rare=60056
collection_log_category_master_treasure_trails_rare=60055
collection_log_category_shared_treasure_trail_rewards=60054
collection_log_category_scroll_cases=60053
collection_log_category_barbarian_assault=60052
collection_log_category_barracuda_trials=60051
collection_log_category_brimhaven_agility_arena=60050
collection_log_category_castle_wars=60049
collection_log_category_fishing_trawler=60048
collection_log_category_giants_foundry=60047
collection_log_category_gnome_restaurant=60046
collection_log_category_guardians_of_the_rift=60045
collection_log_category_hallowed_sepulchre=60044
collection_log_category_last_man_standing=60043
collection_log_category_magic_training_arena=60042
collection_log_category_mahogany_homes=60041
collection_log_category_mastering_mixology=60040
collection_log_category_pest_control=60039
collection_log_category_rogues_den=60038
collection_log_category_shades_of_mort_ton=60037
collection_log_category_soul_wars=60036
collection_log_category_temple_trekking=60035
collection_log_category_tithe_farm=60034
collection_log_category_trouble_brewing=60033
collection_log_category_vale_totems=60032
collection_log_category_volcanic_mine=60031
collection_log_category_aerial_fishing=60030
collection_log_category_all_pets=60029
collection_log_category_boat_paints=60028
collection_log_category_camdozaal=60027
collection_log_category_champion_s_challenge=60026
collection_log_category_chompy_bird_hunting=60025
collection_log_category_colossal_wyrm_agility=60024
collection_log_category_creature_creation=60023
collection_log_category_cyclopes=60022
collection_log_category_elder_chaos_druids=60021
collection_log_category_forestry=60020
collection_log_category_fossil_island_notes=60019
collection_log_category_glough_s_experiments=60018
collection_log_category_hunter_guild=60017
collection_log_category_lost_schematics=60016
collection_log_category_monkey_backpacks=60015
collection_log_category_motherlode_mine=60014
collection_log_category_my_notes=60013
collection_log_category_ocean_encounters=60012
collection_log_category_random_events=60011
collection_log_category_revenants=60010
collection_log_category_rooftop_agility=60009
collection_log_category_sailing_miscellaneous=60008
collection_log_category_sea_treasures=60007
collection_log_category_shayzien_armour=60006
collection_log_category_shooting_stars=60005
collection_log_category_skilling_pets=60004
collection_log_category_slayer=60003
collection_log_category_tormented_demons=60002
collection_log_category_tzhaar=60001
collection_log_category_miscellaneous=60000
