package org.rsmod.content.skills.fletching

/*
 * Levels, experience, materials and tick timings come from the OSRS wiki recipe data
 * (Bucket "recipe", uses_skill = Fletching). Coloured feather variants are handled through
 * [FEATHERS] instead of separate rows.
 */
/** Ogre fletching stays a mystery until Rantz explains it in Big Chompy Bird Hunting. */
private const val CHOMPY_UNLOCK = "varbit.chompy_quest_started"
private const val CHOMPY_LOCKED = "You're not sure what you would make with these."

internal val FLETCHING_RECIPES: List<FletchingRecipe> = listOf(
    FletchingRecipe(
        output = "obj.arrow_shaft",
        outputCount = 15,
        inputs = listOf(input("obj.logs")),
        level = 1,
        xp = 5.0,
        ticks = 2,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.bronze_arrow",
        outputCount = 15,
        inputs = listOf(input("obj.headless_arrow"), input("obj.bronze_arrowheads")),
        batch = true,
        level = 1,
        xp = 19.5,
        ticks = 2,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach arrow heads to {count} arrow shafts.",
    ),
    FletchingRecipe(
        output = "obj.headless_arrow",
        outputCount = 15,
        inputs = listOf(input("obj.arrow_shaft"), input("obj.feather")),
        batch = true,
        level = 1,
        xp = 15.0,
        ticks = 2,
        anim = "seq.human_fletching_add_feather",
        sound = "synth.fletching_feathers",
        message = "You attach feathers to {count} shafts.",
    ),
    FletchingRecipe(
        output = "obj.bronze_javelin",
        outputCount = 15,
        inputs = listOf(input("obj.bronze_javelin_head"), input("obj.javelin_shaft")),
        batch = true,
        level = 3,
        xp = 15.0,
        ticks = 1,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach javelin heads to {count} javelin shafts.",
    ),
    FletchingRecipe(
        output = "obj.javelin_shaft",
        outputCount = 15,
        inputs = listOf(input("obj.logs")),
        level = 3,
        xp = 5.0,
        ticks = 2,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.ogre_headless_arrow",
        outputCount = 6,
        inputs = listOf(input("obj.ogre_arrow_shaft"), input("obj.feather", 4)),
        batch = true,
        level = 5,
        xp = 5.4,
        ticks = 2,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_feathers",
        message = "You attach feathers to {count} ogre arrow shafts.",
        unlockVarbit = CHOMPY_UNLOCK,
        lockedMessage = CHOMPY_LOCKED,
    ),
    FletchingRecipe(
        output = "obj.ogre_arrow",
        outputCount = 6,
        inputs = listOf(input("obj.ogre_headless_arrow"), input("obj.wolfbone_arrowheads")),
        batch = true,
        level = 5,
        xp = 6.0,
        ticks = 2,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_attach",
        message = "You make {count} {plural}.",
        unlockVarbit = CHOMPY_UNLOCK,
        lockedMessage = CHOMPY_LOCKED,
        completionVarbit = "varbit.chompy_made_arrows",
    ),
    FletchingRecipe(
        output = "obj.ogre_arrow_shaft",
        outputCount = 4,
        inputs = listOf(input("obj.achey_tree_logs")),
        level = 5,
        xp = 6.4,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
        unlockVarbit = CHOMPY_UNLOCK,
        lockedMessage = "You're not sure what you would make with these logs.",
    ),
    FletchingRecipe(
        output = "obj.shortbow",
        inputs = listOf(input("obj.unstrung_shortbow"), input("obj.bow_string")),
        level = 5,
        xp = 5.0,
        ticks = 2,
        anim = "seq.stringing_shortbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_shortbow",
        inputs = listOf(input("obj.logs")),
        level = 5,
        xp = 5.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.wolfbone_arrowheads",
        outputCount = 4,
        inputs = listOf(input("obj.wolf_bones")),
        level = 5,
        xp = 10.0,
        ticks = 2,
        tool = CHISEL,
        anim = "seq.human_fletching_huntingbolts_chisel",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} {plural}.",
        unlockVarbit = CHOMPY_UNLOCK,
        lockedMessage = CHOMPY_LOCKED,
    ),
    FletchingRecipe(
        output = "obj.zogre_brutal_bronze",
        outputCount = 6,
        inputs = listOf(input("obj.ogre_headless_arrow"), input("obj.nails_bronze")),
        batch = true,
        level = 7,
        xp = 8.4,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_attach",
        message = "You make {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.bolt",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_bronze_unfeathered"), input("obj.feather")),
        batch = true,
        level = 9,
        xp = 5.0,
        ticks = 0,
        anim = "seq.human_fletching_add_bolt_feathers_bronze",
        sound = "synth.fletching_feathers",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bronze",
        inputs = listOf(input("obj.xbows_crossbow_unstrung_bronze"), input("obj.xbows_crossbow_string")),
        level = 9,
        xp = 6.0,
        ticks = 2,
        anim = "seq.xbows_stringing_crossbow_bronze",
        sound = "synth.fletching_string_crossbow",
        message = "You add a string to the crossbow.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_unstrung_bronze",
        inputs = listOf(input("obj.xbows_crossbow_stock_wood"), input("obj.xbows_crossbow_limbs_bronze")),
        level = 9,
        xp = 12.0,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.xbows_fletching_wood_bronze",
        sound = "synth.fletching_attach_limbs",
        message = "You attach the metal limbs to the stock.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_stock_wood",
        inputs = listOf(input("obj.logs")),
        level = 9,
        xp = 6.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.bronze_dart",
        outputCount = 10,
        inputs = listOf(input("obj.bronze_dart_tip"), input("obj.feather")),
        batch = true,
        level = 10,
        xp = 18.0,
        ticks = 0,
        anim = "seq.human_fletching_add_dart_feathers_bronze",
        sound = "synth.fletching_feathers",
        message = "You finish making {count} darts.",
    ),
    FletchingRecipe(
        output = "obj.longbow",
        inputs = listOf(input("obj.unstrung_longbow"), input("obj.bow_string")),
        level = 10,
        xp = 10.0,
        ticks = 2,
        anim = "seq.stringing_longbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_longbow",
        inputs = listOf(input("obj.logs")),
        level = 10,
        xp = 10.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.opal_bolttips",
        outputCount = 12,
        inputs = listOf(input("obj.opal")),
        level = 11,
        xp = 1.5,
        ticks = 5,
        tool = CHISEL,
        anim = "seq.human_opalcutting",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} bolt tips.",
    ),
    FletchingRecipe(
        output = "obj.opal_bolt",
        outputCount = 10,
        inputs = listOf(input("obj.bolt"), input("obj.opal_bolttips")),
        batch = true,
        level = 11,
        xp = 16.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_bronze",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.arrow_shaft",
        outputCount = 30,
        inputs = listOf(input("obj.oak_logs")),
        level = 15,
        xp = 10.0,
        ticks = 2,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.iron_arrow",
        outputCount = 15,
        inputs = listOf(input("obj.headless_arrow"), input("obj.iron_arrowheads")),
        batch = true,
        level = 15,
        xp = 37.5,
        ticks = 2,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach arrow heads to {count} arrow shafts.",
    ),
    FletchingRecipe(
        output = "obj.iron_javelin",
        outputCount = 15,
        inputs = listOf(input("obj.iron_javelin_head"), input("obj.javelin_shaft")),
        batch = true,
        level = 17,
        xp = 30.0,
        ticks = 2,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach javelin heads to {count} javelin shafts.",
    ),
    FletchingRecipe(
        output = "obj.zogre_brutal_iron",
        outputCount = 6,
        inputs = listOf(input("obj.ogre_headless_arrow"), input("obj.nails_iron")),
        batch = true,
        level = 18,
        xp = 15.6,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_attach",
        message = "You make {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.oak_shortbow",
        inputs = listOf(input("obj.unstrung_oak_shortbow"), input("obj.bow_string")),
        level = 20,
        xp = 16.5,
        ticks = 2,
        anim = "seq.stringing_oak_shortbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_oak_shortbow",
        inputs = listOf(input("obj.oak_logs")),
        level = 20,
        xp = 16.5,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.iron_dart",
        outputCount = 10,
        inputs = listOf(input("obj.iron_dart_tip"), input("obj.feather")),
        batch = true,
        level = 22,
        xp = 38.0,
        ticks = 0,
        anim = "seq.human_fletching_add_dart_feathers_iron",
        sound = "synth.fletching_feathers",
        message = "You finish making {count} darts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_blurite",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_blurite_unfeathered"), input("obj.feather")),
        batch = true,
        level = 24,
        xp = 10.0,
        ticks = 0,
        anim = "seq.human_fletching_add_bolt_feathers_blurite",
        sound = "synth.fletching_feathers",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_blurite",
        inputs = listOf(input("obj.xbows_crossbow_unstrung_blurite"), input("obj.xbows_crossbow_string")),
        level = 24,
        xp = 16.0,
        ticks = 2,
        anim = "seq.xbows_stringing_crossbow_blurite",
        sound = "synth.fletching_string_crossbow",
        message = "You add a string to the crossbow.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_unstrung_blurite",
        inputs = listOf(input("obj.xbows_crossbow_stock_oak"), input("obj.xbows_crossbow_limbs_blurite")),
        level = 24,
        xp = 32.0,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.xbows_fletching_oak_blurite",
        sound = "synth.fletching_attach_limbs",
        message = "You attach the metal limbs to the stock.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_stock_oak",
        inputs = listOf(input("obj.oak_logs")),
        level = 24,
        xp = 16.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.oak_longbow",
        inputs = listOf(input("obj.unstrung_oak_longbow"), input("obj.bow_string")),
        level = 25,
        xp = 25.0,
        ticks = 2,
        anim = "seq.stringing_oak_longbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_oak_longbow",
        inputs = listOf(input("obj.oak_logs")),
        level = 25,
        xp = 25.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.xbows_bolt_tips_jade",
        outputCount = 12,
        inputs = listOf(input("obj.jade")),
        level = 26,
        xp = 2.0,
        ticks = 5,
        tool = CHISEL,
        anim = "seq.human_jadecutting",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} bolt tips.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_blurite_tipped_jade",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_blurite"), input("obj.xbows_bolt_tips_jade")),
        batch = true,
        level = 26,
        xp = 24.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_blurite",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.oak_shield",
        inputs = listOf(input("obj.oak_logs", 2)),
        level = 27,
        xp = 50.0,
        ticks = 7,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.arrow_shaft",
        outputCount = 45,
        inputs = listOf(input("obj.willow_logs")),
        level = 30,
        xp = 15.0,
        ticks = 2,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.zogre_bow",
        inputs = listOf(input("obj.unstrung_zogre_bow"), input("obj.bow_string")),
        level = 30,
        xp = 45.0,
        ticks = 2,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.steel_arrow",
        outputCount = 15,
        inputs = listOf(input("obj.headless_arrow"), input("obj.steel_arrowheads")),
        batch = true,
        level = 30,
        xp = 75.0,
        ticks = 2,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach arrow heads to {count} arrow shafts.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_zogre_bow",
        inputs = listOf(input("obj.achey_tree_logs"), input("obj.wolf_bones")),
        level = 30,
        xp = 45.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.huntingbow_bolts",
        outputCount = 12,
        inputs = listOf(input("obj.huntingbeast_spike")),
        level = 32,
        xp = 5.8,
        ticks = 3,
        tool = CHISEL,
        anim = "seq.human_fletching_huntingbolts_chisel",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.steel_javelin",
        outputCount = 15,
        inputs = listOf(input("obj.steel_javelin_head"), input("obj.javelin_shaft")),
        batch = true,
        level = 32,
        xp = 75.0,
        ticks = 1,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach javelin heads to {count} javelin shafts.",
    ),
    FletchingRecipe(
        output = "obj.zogre_brutal_steel",
        outputCount = 6,
        inputs = listOf(input("obj.ogre_headless_arrow"), input("obj.nails")),
        batch = true,
        level = 33,
        xp = 30.6,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_attach",
        message = "You make {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.willow_shortbow",
        inputs = listOf(input("obj.unstrung_willow_shortbow"), input("obj.bow_string")),
        level = 35,
        xp = 33.2,
        ticks = 2,
        anim = "seq.stringing_willow_shortbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_willow_shortbow",
        inputs = listOf(input("obj.willow_logs")),
        level = 35,
        xp = 33.3,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.steel_dart",
        outputCount = 10,
        inputs = listOf(input("obj.steel_dart_tip"), input("obj.feather")),
        batch = true,
        level = 37,
        xp = 75.0,
        ticks = 0,
        anim = "seq.human_fletching_add_dart_feathers_steel",
        sound = "synth.fletching_feathers",
        message = "You finish making {count} darts.",
    ),
    FletchingRecipe(
        output = "obj.zogre_brutal_black",
        outputCount = 6,
        inputs = listOf(input("obj.ogre_headless_arrow"), input("obj.nails_black")),
        batch = true,
        level = 38,
        xp = 39.0,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_attach",
        message = "You make {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_iron",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_iron_unfeathered"), input("obj.feather")),
        batch = true,
        level = 39,
        xp = 15.0,
        ticks = 0,
        anim = "seq.human_fletching_add_bolt_feathers_iron",
        sound = "synth.fletching_feathers",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_iron",
        inputs = listOf(input("obj.xbows_crossbow_unstrung_iron"), input("obj.xbows_crossbow_string")),
        level = 39,
        xp = 22.0,
        ticks = 2,
        anim = "seq.xbows_stringing_crossbow_iron",
        sound = "synth.fletching_string_crossbow",
        message = "You add a string to the crossbow.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_unstrung_iron",
        inputs = listOf(input("obj.xbows_crossbow_stock_willow"), input("obj.xbows_crossbow_limbs_iron")),
        level = 39,
        xp = 44.0,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.xbows_fletching_willow_iron",
        sound = "synth.fletching_attach_limbs",
        message = "You attach the metal limbs to the stock.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_stock_willow",
        inputs = listOf(input("obj.willow_logs")),
        level = 39,
        xp = 22.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.battlestaff",
        inputs = listOf(input("obj.celastrus_wood")),
        level = 40,
        xp = 80.0,
        ticks = 4,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.willow_longbow",
        inputs = listOf(input("obj.unstrung_willow_longbow"), input("obj.bow_string")),
        level = 40,
        xp = 41.5,
        ticks = 2,
        anim = "seq.stringing_willow_longbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_willow_longbow",
        inputs = listOf(input("obj.willow_logs")),
        level = 40,
        xp = 41.5,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.pearl_bolttips",
        outputCount = 6,
        inputs = listOf(input("obj.smalloysterpearls")),
        level = 41,
        xp = 3.2,
        ticks = 5,
        tool = CHISEL,
        anim = "seq.xbows_fletching_pearl",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} bolt tips.",
    ),
    FletchingRecipe(
        output = "obj.pearl_bolttips",
        outputCount = 24,
        inputs = listOf(input("obj.bigoysterpearls")),
        level = 41,
        xp = 3.2,
        ticks = 5,
        tool = CHISEL,
        anim = "seq.xbows_fletching_pearl",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} bolt tips.",
    ),
    FletchingRecipe(
        output = "obj.pearl_bolt",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_iron"), input("obj.pearl_bolttips")),
        batch = true,
        level = 41,
        xp = 32.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_iron",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.huntingbow_bigbolts",
        outputCount = 12,
        inputs = listOf(input("obj.huntingbeast_bigspike")),
        level = 42,
        xp = 7.9,
        ticks = 2,
        tool = CHISEL,
        anim = "seq.human_fletching_huntingbolts_chisel",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.willow_shield",
        inputs = listOf(input("obj.willow_logs", 2)),
        level = 42,
        xp = 83.0,
        ticks = 7,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_silver",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_silver_unfeathered"), input("obj.feather")),
        batch = true,
        level = 43,
        xp = 25.0,
        ticks = 0,
        anim = "seq.human_fletching_add_bolt_feathers_silver",
        sound = "synth.fletching_feathers",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.arrow_shaft",
        outputCount = 60,
        inputs = listOf(input("obj.maple_logs")),
        level = 45,
        xp = 20.0,
        ticks = 2,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.mithril_arrow",
        outputCount = 15,
        inputs = listOf(input("obj.headless_arrow"), input("obj.mithril_arrowheads")),
        batch = true,
        level = 45,
        xp = 112.5,
        ticks = 2,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach arrow heads to {count} arrow shafts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_steel",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_steel_unfeathered"), input("obj.feather")),
        batch = true,
        level = 46,
        xp = 35.0,
        ticks = 0,
        anim = "seq.human_fletching_add_bolt_feathers_steel",
        sound = "synth.fletching_feathers",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_steel",
        inputs = listOf(input("obj.xbows_crossbow_unstrung_steel"), input("obj.xbows_crossbow_string")),
        level = 46,
        xp = 27.0,
        ticks = 2,
        anim = "seq.xbows_stringing_crossbow_steel",
        sound = "synth.fletching_string_crossbow",
        message = "You add a string to the crossbow.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_unstrung_steel",
        inputs = listOf(input("obj.xbows_crossbow_stock_teak"), input("obj.xbows_crossbow_limbs_steel")),
        level = 46,
        xp = 54.0,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.xbows_fletching_teak_steel",
        sound = "synth.fletching_attach_limbs",
        message = "You attach the metal limbs to the stock.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_stock_teak",
        inputs = listOf(input("obj.teak_logs")),
        level = 46,
        xp = 27.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.ballista_incomplete_light",
        inputs = listOf(input("obj.ballista_frame_light"), input("obj.ballista_limbs")),
        level = 47,
        xp = 15.0,
        ticks = 2,
        tool = HAMMER,
        sound = "synth.fletching_attach_limbs",
        message = "You make {an}.",
    ),
    FletchingRecipe(
        output = "obj.light_ballista",
        inputs = listOf(input("obj.ballista_unstrung_light"), input("obj.ballista_rope")),
        level = 47,
        xp = 300.0,
        ticks = 2,
        tool = HAMMER,
        sound = "synth.fletching_attach_limbs",
        message = "You make {an}.",
    ),
    FletchingRecipe(
        output = "obj.mithril_javelin",
        outputCount = 15,
        inputs = listOf(input("obj.mithril_javelin_head"), input("obj.javelin_shaft")),
        batch = true,
        level = 47,
        xp = 120.0,
        ticks = 1,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach javelin heads to {count} javelin shafts.",
    ),
    FletchingRecipe(
        output = "obj.ballista_unstrung_light",
        inputs = listOf(input("obj.ballista_incomplete_light"), input("obj.ballista_spring")),
        level = 47,
        xp = 15.0,
        ticks = 2,
        tool = HAMMER,
        sound = "synth.fletching_attach_limbs",
        message = "You make {an}.",
    ),
    FletchingRecipe(
        output = "obj.xbows_bolt_tips_redtopaz",
        outputCount = 12,
        inputs = listOf(input("obj.red_topaz")),
        level = 48,
        xp = 3.9,
        ticks = 5,
        tool = CHISEL,
        anim = "seq.human_redtopazcutting",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} bolt tips.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_steel_tipped_redtopaz",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_steel"), input("obj.xbows_bolt_tips_redtopaz")),
        batch = true,
        level = 48,
        xp = 39.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_steel",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.zogre_brutal_mithril",
        outputCount = 6,
        inputs = listOf(input("obj.ogre_headless_arrow"), input("obj.nails_mithril")),
        batch = true,
        level = 49,
        xp = 45.0,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_attach",
        message = "You make {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.maple_shortbow",
        inputs = listOf(input("obj.unstrung_maple_shortbow"), input("obj.bow_string")),
        level = 50,
        xp = 50.0,
        ticks = 2,
        anim = "seq.stringing_maple_shortbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_maple_shortbow",
        inputs = listOf(input("obj.maple_logs")),
        level = 50,
        xp = 50.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.barbed_bolt",
        outputCount = 10,
        inputs = listOf(input("obj.bolt"), input("obj.barbed_bolttips")),
        batch = true,
        level = 51,
        xp = 95.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_bronze",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.slayer_broad_arrows",
        outputCount = 15,
        inputs = listOf(input("obj.headless_arrow"), input("obj.slayer_broad_arrowhead")),
        batch = true,
        level = 52,
        xp = 150.0,
        ticks = 2,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach arrow heads to {count} arrow shafts.",
        unlockVarbit = "varbit.slayer_ammo_unlocked",
    ),
    FletchingRecipe(
        output = "obj.mithril_dart",
        outputCount = 10,
        inputs = listOf(input("obj.mithril_dart_tip"), input("obj.feather")),
        batch = true,
        level = 52,
        xp = 112.0,
        ticks = 0,
        anim = "seq.human_fletching_add_dart_feathers_mithril",
        sound = "synth.fletching_feathers",
        message = "You finish making {count} darts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_stock_maple",
        inputs = listOf(input("obj.maple_logs")),
        level = 54,
        xp = 32.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_mithril",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_mithril_unfeathered"), input("obj.feather")),
        batch = true,
        level = 54,
        xp = 50.0,
        ticks = 0,
        anim = "seq.human_fletching_add_bolt_feathers_mithril",
        sound = "synth.fletching_feathers",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_mithril",
        inputs = listOf(input("obj.xbows_crossbow_unstrung_mithril"), input("obj.xbows_crossbow_string")),
        level = 54,
        xp = 32.0,
        ticks = 2,
        anim = "seq.xbows_stringing_crossbow_mithril",
        sound = "synth.fletching_string_crossbow",
        message = "You add a string to the crossbow.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_unstrung_mithril",
        inputs = listOf(input("obj.xbows_crossbow_stock_maple"), input("obj.xbows_crossbow_limbs_mithril")),
        level = 54,
        xp = 64.0,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.xbows_fletching_maple_mithril",
        sound = "synth.fletching_attach_limbs",
        message = "You attach the metal limbs to the stock.",
    ),
    FletchingRecipe(
        output = "obj.slayer_broad_bolt",
        outputCount = 10,
        inputs = listOf(input("obj.slayer_broad_bolt_unfinished"), input("obj.feather")),
        batch = true,
        level = 55,
        xp = 30.0,
        ticks = 0,
        anim = "seq.human_fletching_add_bolt_feathers_bronze",
        sound = "synth.fletching_feathers",
        message = "You fletch {count} bolts.",
        unlockVarbit = "varbit.slayer_ammo_unlocked",
    ),
    FletchingRecipe(
        output = "obj.maple_longbow",
        inputs = listOf(input("obj.unstrung_maple_longbow"), input("obj.bow_string")),
        level = 55,
        xp = 58.2,
        ticks = 2,
        anim = "seq.stringing_maple_longbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_maple_longbow",
        inputs = listOf(input("obj.maple_logs")),
        level = 55,
        xp = 58.3,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.xbows_bolt_tips_sapphire",
        outputCount = 12,
        inputs = listOf(input("obj.sapphire")),
        level = 56,
        xp = 4.0,
        ticks = 5,
        tool = CHISEL,
        anim = "seq.human_sapphirecutting",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} bolt tips.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_mithril_tipped_sapphire",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_mithril"), input("obj.xbows_bolt_tips_sapphire")),
        batch = true,
        level = 56,
        xp = 47.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_mithril",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.maple_shield",
        inputs = listOf(input("obj.maple_logs", 2)),
        level = 57,
        xp = 116.5,
        ticks = 7,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.xbows_bolt_tips_emerald",
        outputCount = 12,
        inputs = listOf(input("obj.emerald")),
        level = 58,
        xp = 5.5,
        ticks = 5,
        tool = CHISEL,
        anim = "seq.human_emeraldcutting",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} bolt tips.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_mithril_tipped_emerald",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_mithril"), input("obj.xbows_bolt_tips_emerald")),
        batch = true,
        level = 58,
        xp = 55.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_mithril",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_grapple_tip_bolt_mithril_rope",
        inputs = listOf(input("obj.xbows_grapple_tip_bolt_mithril"), input("obj.rope")),
        level = 59,
        xp = 0.0,
        ticks = 1,
        message = "You tie the rope to the grapple.",
    ),
    FletchingRecipe(
        output = "obj.xbows_grapple_tip_bolt_mithril",
        inputs = listOf(input("obj.xbows_grapple_tip_mithril"), input("obj.xbows_crossbow_bolts_mithril")),
        level = 59,
        xp = 11.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_mithril",
        sound = "synth.fletching_attach",
        message = "You attach the grapple tip to the bolt.",
    ),
    FletchingRecipe(
        output = "obj.adamant_arrow",
        outputCount = 15,
        inputs = listOf(input("obj.headless_arrow"), input("obj.adamant_arrowheads")),
        batch = true,
        level = 60,
        xp = 150.0,
        ticks = 2,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach arrow heads to {count} arrow shafts.",
    ),
    FletchingRecipe(
        output = "obj.arrow_shaft",
        outputCount = 75,
        inputs = listOf(input("obj.yew_logs")),
        level = 60,
        xp = 25.0,
        ticks = 2,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_adamantite",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_adamantite_unfeathered"), input("obj.feather")),
        batch = true,
        level = 61,
        xp = 70.0,
        ticks = 0,
        anim = "seq.human_fletching_add_bolt_feathers_adamant",
        sound = "synth.fletching_feathers",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_adamantite",
        inputs = listOf(input("obj.xbows_crossbow_unstrung_adamantite"), input("obj.xbows_crossbow_string")),
        level = 61,
        xp = 41.0,
        ticks = 2,
        anim = "seq.xbows_stringing_crossbow_adamantite",
        sound = "synth.fletching_string_crossbow",
        message = "You add a string to the crossbow.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_unstrung_adamantite",
        inputs = listOf(input("obj.xbows_crossbow_stock_mahogany"), input("obj.xbows_crossbow_limbs_adamantite")),
        level = 61,
        xp = 82.0,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.xbows_fletching_mahogany_adamantite",
        sound = "synth.fletching_attach_limbs",
        message = "You attach the metal limbs to the stock.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_stock_mahogany",
        inputs = listOf(input("obj.mahogany_logs")),
        level = 61,
        xp = 41.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.zogre_brutal_adamant",
        outputCount = 6,
        inputs = listOf(input("obj.ogre_headless_arrow"), input("obj.nails_adamant")),
        batch = true,
        level = 62,
        xp = 61.2,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_attach",
        message = "You make {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.adamant_javelin",
        outputCount = 15,
        inputs = listOf(input("obj.adamant_javelin_head"), input("obj.javelin_shaft")),
        batch = true,
        level = 62,
        xp = 150.0,
        ticks = 1,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach javelin heads to {count} javelin shafts.",
    ),
    FletchingRecipe(
        output = "obj.sunlight_antelope_bolt",
        outputCount = 12,
        inputs = listOf(input("obj.hunting_antelopesun_horn")),
        level = 62,
        xp = 10.0,
        ticks = 3,
        tool = CHISEL,
        anim = "seq.human_fletching_huntingbolts_chisel",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.xbows_bolt_tips_ruby",
        outputCount = 12,
        inputs = listOf(input("obj.ruby")),
        level = 63,
        xp = 6.3,
        ticks = 5,
        tool = CHISEL,
        anim = "seq.human_rubycutting",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} bolt tips.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_adamantite_tipped_ruby",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_adamantite"), input("obj.xbows_bolt_tips_ruby")),
        batch = true,
        level = 63,
        xp = 63.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_adamant",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_bolt_tips_diamond",
        outputCount = 12,
        inputs = listOf(input("obj.diamond")),
        level = 65,
        xp = 7.0,
        ticks = 5,
        tool = CHISEL,
        anim = "seq.human_diamondcutting",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} bolt tips.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_adamantite_tipped_diamond",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_adamantite"), input("obj.xbows_bolt_tips_diamond")),
        batch = true,
        level = 65,
        xp = 70.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_adamant",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.yew_shortbow",
        inputs = listOf(input("obj.unstrung_yew_shortbow"), input("obj.bow_string")),
        level = 65,
        xp = 67.5,
        ticks = 2,
        anim = "seq.stringing_yew_shortbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_yew_shortbow",
        inputs = listOf(input("obj.yew_logs")),
        level = 65,
        xp = 67.5,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.adamant_dart",
        outputCount = 10,
        inputs = listOf(input("obj.adamant_dart_tip"), input("obj.feather")),
        batch = true,
        level = 67,
        xp = 150.0,
        ticks = 0,
        anim = "seq.human_fletching_add_dart_feathers_adamant",
        sound = "synth.fletching_feathers",
        message = "You finish making {count} darts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_runite",
        inputs = listOf(input("obj.xbows_crossbow_unstrung_runite"), input("obj.xbows_crossbow_string")),
        level = 69,
        xp = 50.0,
        ticks = 2,
        anim = "seq.xbows_stringing_crossbow_runite",
        sound = "synth.fletching_string_crossbow",
        message = "You add a string to the crossbow.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_runite",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_runite_unfeathered"), input("obj.feather")),
        batch = true,
        level = 69,
        xp = 100.0,
        ticks = 0,
        anim = "seq.human_fletching_add_bolt_feathers_rune",
        sound = "synth.fletching_feathers",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_unstrung_runite",
        inputs = listOf(input("obj.xbows_crossbow_stock_yew"), input("obj.xbows_crossbow_limbs_runite")),
        level = 69,
        xp = 100.0,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.xbows_fletching_yew_runite",
        sound = "synth.fletching_attach_limbs",
        message = "You attach the metal limbs to the stock.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_stock_yew",
        inputs = listOf(input("obj.yew_logs")),
        level = 69,
        xp = 50.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.yew_longbow",
        inputs = listOf(input("obj.unstrung_yew_longbow"), input("obj.bow_string")),
        level = 70,
        xp = 75.0,
        ticks = 2,
        anim = "seq.stringing_yew_longbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_yew_longbow",
        inputs = listOf(input("obj.yew_logs")),
        level = 70,
        xp = 75.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.xbows_bolt_tips_dragonstone",
        outputCount = 12,
        inputs = listOf(input("obj.dragonstone")),
        level = 71,
        xp = 8.2,
        ticks = 5,
        tool = CHISEL,
        anim = "seq.human_dragonstonecutting",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} bolt tips.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_runite_tipped_dragonstone",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_runite"), input("obj.xbows_bolt_tips_dragonstone")),
        batch = true,
        level = 71,
        xp = 82.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_rune",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.heavy_ballista",
        inputs = listOf(input("obj.ballista_unstrung_heavy"), input("obj.ballista_rope")),
        level = 72,
        xp = 600.0,
        ticks = 2,
        tool = HAMMER,
        sound = "synth.fletching_attach_limbs",
        message = "You make {an}.",
    ),
    FletchingRecipe(
        output = "obj.ballista_incomplete_heavy",
        inputs = listOf(input("obj.ballista_frame_heavy"), input("obj.ballista_limbs")),
        level = 72,
        xp = 30.0,
        ticks = 2,
        tool = HAMMER,
        sound = "synth.fletching_attach_limbs",
        message = "You make {an}.",
    ),
    FletchingRecipe(
        output = "obj.moonlight_antelope_bolt",
        outputCount = 12,
        inputs = listOf(input("obj.hunting_antelopemoon_horn")),
        level = 72,
        xp = 12.1,
        ticks = 3,
        tool = CHISEL,
        anim = "seq.human_fletching_huntingbolts_chisel",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.ballista_unstrung_heavy",
        inputs = listOf(input("obj.ballista_incomplete_heavy"), input("obj.ballista_spring")),
        level = 72,
        xp = 30.0,
        ticks = 2,
        tool = HAMMER,
        sound = "synth.fletching_attach_limbs",
        message = "You make {an}.",
    ),
    FletchingRecipe(
        output = "obj.yew_shield",
        inputs = listOf(input("obj.yew_logs", 2)),
        level = 72,
        xp = 150.0,
        ticks = 7,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.xbows_bolt_tips_onyx",
        outputCount = 24,
        inputs = listOf(input("obj.onyx")),
        level = 73,
        xp = 9.4,
        ticks = 5,
        tool = CHISEL,
        anim = "seq.human_onyxcutting",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} bolt tips.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_bolts_runite_tipped_onyx",
        outputCount = 10,
        inputs = listOf(input("obj.xbows_crossbow_bolts_runite"), input("obj.xbows_bolt_tips_onyx")),
        batch = true,
        level = 73,
        xp = 94.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_rune",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.atlatl_dart",
        outputCount = 20,
        inputs = listOf(input("obj.headless_atlatl_dart"), input("obj.atlatl_dart_tips")),
        batch = true,
        level = 74,
        xp = 30.0,
        ticks = 2,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach tips to {count} atlatl darts.",
    ),
    FletchingRecipe(
        output = "obj.atlatl_dart_shaft",
        outputCount = 100,
        inputs = listOf(input("obj.ent_branch")),
        level = 74,
        xp = 30.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.atlatl_dart_tips",
        outputCount = 100,
        inputs = listOf(input("obj.custodian_broken_antler")),
        level = 74,
        xp = 10.0,
        ticks = 4,
        tool = CHISEL,
        anim = "seq.human_fletching_huntingbolts_chisel",
        sound = "synth.chisel",
        message = "You use your chisel to fletch {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.headless_atlatl_dart",
        outputCount = 20,
        inputs = listOf(input("obj.atlatl_dart_shaft"), input("obj.feather")),
        batch = true,
        level = 74,
        xp = 20.0,
        ticks = 2,
        anim = "seq.human_fletching_add_feather",
        sound = "synth.fletching_feathers",
        message = "You attach feathers to {count} shafts.",
    ),
    FletchingRecipe(
        output = "obj.arrow_shaft",
        outputCount = 90,
        inputs = listOf(input("obj.magic_logs")),
        level = 75,
        xp = 30.0,
        ticks = 2,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.rune_arrow",
        outputCount = 15,
        inputs = listOf(input("obj.headless_arrow"), input("obj.rune_arrowheads")),
        batch = true,
        level = 75,
        xp = 187.5,
        ticks = 2,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach arrow heads to {count} arrow shafts.",
    ),
    FletchingRecipe(
        output = "obj.slayer_broad_bolt_amethyst",
        outputCount = 10,
        inputs = listOf(input("obj.slayer_broad_bolt"), input("obj.xbows_bolt_tips_amethyst")),
        batch = true,
        level = 76,
        xp = 106.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_adamant",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
        unlockVarbit = "varbit.slayer_ammo_unlocked",
    ),
    FletchingRecipe(
        output = "obj.zogre_brutal_rune",
        outputCount = 6,
        inputs = listOf(input("obj.ogre_headless_arrow"), input("obj.nails_rune")),
        batch = true,
        level = 77,
        xp = 75.0,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.human_ogre_fletching",
        sound = "synth.fletching_attach",
        message = "You make {count} {plural}.",
    ),
    FletchingRecipe(
        output = "obj.rune_javelin",
        outputCount = 15,
        inputs = listOf(input("obj.rune_javelin_head"), input("obj.javelin_shaft")),
        batch = true,
        level = 77,
        xp = 187.5,
        ticks = 1,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach javelin heads to {count} javelin shafts.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_dragon",
        inputs = listOf(input("obj.xbows_crossbow_unstrung_dragon"), input("obj.xbows_crossbow_string")),
        level = 78,
        xp = 70.0,
        ticks = 2,
        anim = "seq.xbows_stringing_crossbow_dragon",
        sound = "synth.fletching_string_crossbow",
        message = "You add a string to the crossbow.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_unstrung_dragon",
        inputs = listOf(input("obj.xbows_crossbow_stock_magic"), input("obj.xbows_crossbow_limbs_dragon")),
        level = 78,
        xp = 135.0,
        ticks = 2,
        tool = HAMMER,
        anim = "seq.xbows_fletching_yew_dragon",
        sound = "synth.fletching_attach_limbs",
        message = "You attach the metal limbs to the stock.",
    ),
    FletchingRecipe(
        output = "obj.xbows_crossbow_stock_magic",
        inputs = listOf(input("obj.magic_logs")),
        level = 78,
        xp = 70.0,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.toxic_blowpipe",
        inputs = listOf(input("obj.blowpipe_fang")),
        level = 78,
        xp = 120.0,
        ticks = 0,
        tool = CHISEL,
        anim = "seq.human_fletching_huntingbolts_chisel_single",
        sound = "synth.chisel",
        message = "You carve the fang and turn it into a blowpipe.",
    ),
    FletchingRecipe(
        output = "obj.magic_shortbow",
        inputs = listOf(input("obj.unstrung_magic_shortbow"), input("obj.bow_string")),
        level = 80,
        xp = 83.3,
        ticks = 2,
        anim = "seq.stringing_magic_shortbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_magic_shortbow",
        inputs = listOf(input("obj.magic_logs")),
        level = 80,
        xp = 83.3,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.rune_dart",
        outputCount = 10,
        inputs = listOf(input("obj.rune_dart_tip"), input("obj.feather")),
        batch = true,
        level = 81,
        xp = 188.0,
        ticks = 0,
        anim = "seq.human_fletching_add_dart_feathers_rune",
        sound = "synth.fletching_feathers",
        message = "You finish making {count} darts.",
    ),
    FletchingRecipe(
        output = "obj.amethyst_arrow",
        outputCount = 15,
        inputs = listOf(input("obj.headless_arrow"), input("obj.amethyst_arrowheads")),
        batch = true,
        level = 82,
        xp = 202.5,
        ticks = 2,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach arrow heads to {count} arrow shafts.",
    ),
    FletchingRecipe(
        output = "obj.amethyst_javelin",
        outputCount = 15,
        inputs = listOf(input("obj.amethyst_javelin_head"), input("obj.javelin_shaft")),
        batch = true,
        level = 84,
        xp = 202.5,
        ticks = 1,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach javelin heads to {count} javelin shafts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_bolts_unenchanted_diamond",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_bolts"), input("obj.xbows_bolt_tips_diamond")),
        batch = true,
        level = 84,
        xp = 70.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_dragon",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_bolts",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_bolts_unfeathered"), input("obj.feather")),
        batch = true,
        level = 84,
        xp = 120.0,
        ticks = 0,
        anim = "seq.human_fletching_add_bolt_feathers_dragon",
        sound = "synth.fletching_feathers",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_bolts_unenchanted_dragonstone",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_bolts"), input("obj.xbows_bolt_tips_dragonstone")),
        batch = true,
        level = 84,
        xp = 82.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_dragon",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_bolts_unenchanted_emerald",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_bolts"), input("obj.xbows_bolt_tips_emerald")),
        batch = true,
        level = 84,
        xp = 55.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_dragon",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_bolts_unenchanted_jade",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_bolts"), input("obj.xbows_bolt_tips_jade")),
        batch = true,
        level = 84,
        xp = 24.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_dragon",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_bolts_unenchanted_onyx",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_bolts"), input("obj.xbows_bolt_tips_onyx")),
        batch = true,
        level = 84,
        xp = 94.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_dragon",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_bolts_unenchanted_opal",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_bolts"), input("obj.opal_bolttips")),
        batch = true,
        level = 84,
        xp = 16.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_dragon",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_bolts_unenchanted_pearl",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_bolts"), input("obj.pearl_bolttips")),
        batch = true,
        level = 84,
        xp = 32.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_dragon",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_bolts_unenchanted_ruby",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_bolts"), input("obj.xbows_bolt_tips_ruby")),
        batch = true,
        level = 84,
        xp = 63.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_dragon",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_bolts_unenchanted_sapphire",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_bolts"), input("obj.xbows_bolt_tips_sapphire")),
        batch = true,
        level = 84,
        xp = 47.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_dragon",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_bolts_unenchanted_topaz",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_bolts"), input("obj.xbows_bolt_tips_redtopaz")),
        batch = true,
        level = 84,
        xp = 39.0,
        ticks = 2,
        anim = "seq.human_fletching_add_bolt_tips_dragon",
        sound = "synth.fletching_attach",
        message = "You fletch {count} bolts.",
    ),
    FletchingRecipe(
        output = "obj.magic_longbow",
        inputs = listOf(input("obj.unstrung_magic_longbow"), input("obj.bow_string")),
        level = 85,
        xp = 91.5,
        ticks = 2,
        anim = "seq.stringing_magic_longbow",
        sound = "synth.fletching_string_bow",
        message = "You add a string to the bow.",
    ),
    FletchingRecipe(
        output = "obj.unstrung_magic_longbow",
        inputs = listOf(input("obj.magic_logs")),
        level = 85,
        xp = 91.5,
        ticks = 3,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.magic_shield",
        inputs = listOf(input("obj.magic_logs", 2)),
        level = 87,
        xp = 183.0,
        ticks = 7,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.amethyst_dart",
        outputCount = 10,
        inputs = listOf(input("obj.amethyst_dart_tip"), input("obj.feather")),
        batch = true,
        level = 90,
        xp = 210.0,
        ticks = 0,
        anim = "seq.human_fletching_add_dart_feathers_amethyst",
        sound = "synth.fletching_feathers",
        message = "You finish making {count} darts.",
    ),
    FletchingRecipe(
        output = "obj.arrow_shaft",
        outputCount = 105,
        inputs = listOf(input("obj.redwood_logs")),
        level = 90,
        xp = 35.0,
        ticks = 2,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.dragon_arrow",
        outputCount = 15,
        inputs = listOf(input("obj.headless_arrow"), input("obj.dragon_arrowheads")),
        batch = true,
        level = 90,
        xp = 225.0,
        ticks = 2,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach arrow heads to {count} arrow shafts.",
    ),
    FletchingRecipe(
        output = "obj.dragon_javelin",
        outputCount = 15,
        inputs = listOf(input("obj.dragon_javelin_head"), input("obj.javelin_shaft")),
        batch = true,
        level = 92,
        xp = 225.0,
        ticks = 1,
        anim = "seq.human_fletching_add_arrow_tips",
        sound = "synth.fletching_attach",
        message = "You attach javelin heads to {count} javelin shafts.",
    ),
    FletchingRecipe(
        output = "obj.redwood_shield",
        inputs = listOf(input("obj.redwood_logs", 2)),
        level = 92,
        xp = 216.0,
        ticks = 7,
        tool = KNIFE,
        anim = "seq.human_fletching",
        sound = "synth.fletching_cut",
        message = "You carefully cut the wood into {an}.",
    ),
    FletchingRecipe(
        output = "obj.dragon_dart",
        outputCount = 10,
        inputs = listOf(input("obj.dragon_dart_tip"), input("obj.feather")),
        batch = true,
        level = 95,
        xp = 250.0,
        ticks = 0,
        anim = "seq.human_fletching_add_dart_feathers_dragon",
        sound = "synth.fletching_feathers",
        message = "You finish making {count} darts.",
    ),
)
