package org.rsmod.api.combat.formulas.attributes

public enum class CombatNpcAttributes {
    SlayerTask,
    Wilderness,
    Revenant,
    Undead,
    Demon,
    Draconic,
    Kalphite,
    Golem,
    Leafy,
    Tanglefoot,
    Rat,
    DemonbaneResistance,
    Size2,
    Size3,
    Size4,
    Size5OrMore,
    Shade,
    Vampyre,
    TormentedDemonUnshielded,
    GuaranteedHit,
    TormentedDemonOverheadMelee,
    TormentedDemonOverheadRanged,
    TormentedDemonOverheadMagic,
    CorporealBeast,
    Xerician,
    Amascut,
    QuarterHealth,
    WindWeakness,
    WaterWeakness,
    EarthWeakness,
    FireWeakness,
}
