package org.rsmod.content.other.npccombatanims

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.dataformat.toml.TomlFactory
import com.fasterxml.jackson.module.kotlin.readValue
import com.fasterxml.jackson.module.kotlin.registerKotlinModule

/**
 * One npc's combat animation set as written by `tools/combat-anims`. Every field but [id] is
 * optional: only the fields present are applied.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
data class NpcCombatAnimEntry(
    val id: String,
    val source: String? = null,
    @JsonProperty("attack_anim") val attackAnim: String? = null,
    @JsonProperty("attack_type") val attackType: String? = null,
    @JsonProperty("attack_sound") val attackSound: Int? = null,
    @JsonProperty("defend_anim") val defendAnim: String? = null,
    @JsonProperty("defend_sound") val defendSound: Int? = null,
    @JsonProperty("death_anim") val deathAnim: String? = null,
    @JsonProperty("death_sound") val deathSound: Int? = null,
    @JsonProperty("proj_travel") val projTravel: String? = null,
    @JsonProperty("proj_type") val projType: String? = null,
    @JsonProperty("attack_range") val attackRange: Int? = null,
)

@JsonIgnoreProperties(ignoreUnknown = true)
data class NpcCombatAnimsFile(val npc: List<NpcCombatAnimEntry> = emptyList()) {
    companion object {
        /** Generated by `./gradlew :tools:combat-anims:dumpNpcCombatAnims`. */
        const val GENERATED_RESOURCE: String = "npc-combat-anims.toml"

        /** Hand-maintained corrections. Applied after the generated file and always win. */
        const val OVERRIDES_RESOURCE: String = "npc-combat-anims-overrides.toml"

        private val mapper: ObjectMapper = ObjectMapper(TomlFactory()).registerKotlinModule()

        fun loadResource(name: String): NpcCombatAnimsFile {
            val stream =
                NpcCombatAnimsFile::class.java.classLoader.getResourceAsStream(name)
                    ?: error("Missing resource: $name")
            return stream.use { parse(it.readBytes().decodeToString()) }
        }

        fun parse(toml: String): NpcCombatAnimsFile = mapper.readValue(toml)
    }
}
