[[inventory]]
isServerOnly = true
id = "inv.cam_torum_shop_baker"
name = "Yarnio's Baked Goods"

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 550
delta = 10

size = 7

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.bread"
count = 15
restockCycles = 100

[[inventory.stock]]
obj = "obj.cake"
count = 5
restockCycles = 800

[[inventory.stock]]
obj = "obj.redberry_pie"
count = 5
restockCycles = 150

[[inventory.stock]]
obj = "obj.meat_pie"
count = 5
restockCycles = 150

[[inventory.stock]]
obj = "obj.apple_pie"
count = 5
restockCycles = 150

[[inventory.stock]]
obj = "obj.garden_pie"
count = 5
restockCycles = 150

[[inventory.stock]]
obj = "obj.fish_pie"
count = 5
restockCycles = 150

