[[inventory]]
isServerOnly = true
id = "inv.kastorifarmingstore"
name = "Kastori Farming Supplies"

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 700
delta = 10

size = 17

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.rake"
count = 5
restockCycles = 10

[[inventory.stock]]
obj = "obj.dibber"
count = 5
restockCycles = 10

[[inventory.stock]]
obj = "obj.secateurs"
count = 5
restockCycles = 10

[[inventory.stock]]
obj = "obj.spade"
count = 5
restockCycles = 10

[[inventory.stock]]
obj = "obj.gardening_trowel"
count = 10
restockCycles = 20

[[inventory.stock]]
obj = "obj.watering_can_0"
count = 30
restockCycles = 5

[[inventory.stock]]
obj = "obj.plantpot_compost"
count = 100
restockCycles = 10

[[inventory.stock]]
obj = "obj.pack_plant_pot_compost"
count = 30
restockCycles = 5

[[inventory.stock]]
obj = "obj.bucket_compost"
count = 30
restockCycles = 10

[[inventory.stock]]
obj = "obj.pack_compost"
count = 30
restockCycles = 50

[[inventory.stock]]
obj = "obj.sack_empty"
count = 30
restockCycles = 2

[[inventory.stock]]
obj = "obj.pack_sack"
count = 30
restockCycles = 2

[[inventory.stock]]
obj = "obj.basket_empty"
count = 30
restockCycles = 2

[[inventory.stock]]
obj = "obj.pack_basket"
count = 30
restockCycles = 2

[[inventory.stock]]
obj = "obj.bucket_empty"
count = 30
restockCycles = 10

[[inventory.stock]]
obj = "obj.pack_bucket"
count = 30
restockCycles = 10

[[inventory.stock]]
obj = "obj.plant_cure"
count = 50
restockCycles = 5

