[[inventory]]
isServerOnly = true
id = "inv.mag_emelio_shop"
name = "Emelio's Kebab Shop"

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 500
delta = 0

size = 1

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.varlamorian_kebab"
count = 20
restockCycles = 20

