[[inventory]]
isServerOnly = true
id = "inv.mguild_oreshop"
name = "Hendor's Awesome Ores"

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 700
delta = 20

size = 7

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.copper_ore"
count = 0
restockCycles = 15000

[[inventory.stock]]
obj = "obj.tin_ore"
count = 0
restockCycles = 15000

[[inventory.stock]]
obj = "obj.iron_ore"
count = 0
restockCycles = 5000

[[inventory.stock]]
obj = "obj.mithril_ore"
count = 0
restockCycles = 2000

[[inventory.stock]]
obj = "obj.adamantite_ore"
count = 0
restockCycles = 800

[[inventory.stock]]
obj = "obj.runite_ore"
count = 0
restockCycles = 200

[[inventory.stock]]
obj = "obj.coal"
count = 0
restockCycles = 5000

