[[inventory]]
isServerOnly = true
id = "inv.pandemonium_fishmonger"
name = "Henderson's Catch of the Day"

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 700
delta = 10

size = 17

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.net"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.big_net"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.fishing_rod"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.fly_fishing_rod"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.harpoon"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.lobster_pot"
count = 5
restockCycles = 100

[[inventory.stock]]
obj = "obj.fishing_bait"
count = 2000
restockCycles = 1

[[inventory.stock]]
obj = "obj.pack_fishing_bait"
count = 100
restockCycles = 5

[[inventory.stock]]
obj = "obj.feather"
count = 1000
restockCycles = 1

[[inventory.stock]]
obj = "obj.pack_feather"
count = 100
restockCycles = 5

[[inventory.stock]]
obj = "obj.raw_shrimp"
count = 10
restockCycles = 150

[[inventory.stock]]
obj = "obj.raw_sardine"
count = 10
restockCycles = 150

[[inventory.stock]]
obj = "obj.raw_herring"
count = 10
restockCycles = 150

[[inventory.stock]]
obj = "obj.raw_anchovies"
count = 10
restockCycles = 150

[[inventory.stock]]
obj = "obj.raw_mackerel"
count = 6
restockCycles = 150

[[inventory.stock]]
obj = "obj.raw_cod"
count = 6
restockCycles = 150

[[inventory.stock]]
obj = "obj.raw_bass"
count = 4
restockCycles = 150

