[[inventory]]
isServerOnly = true
id = "inv.port_roberts_silver_trader"
name = "Port Roberts Silver Stall"

scope = "Shared"
stack = "Always"

sellMultiplier = 1000
buyMultiplier = 700
delta = 20

size = 3

protect = false
runWeight = false
restock = true
allStock = false
placeholders = false

[[inventory.stock]]
obj = "obj.silver_ore"
count = 10
restockCycles = 100

[[inventory.stock]]
obj = "obj.silver_bar"
count = 5
restockCycles = 1000

[[inventory.stock]]
obj = "obj.nostringstar"
count = 5
restockCycles = 100

