[[npc]]
id = "npc.gerrant"
inherit = "npc.gerrant"
moveRestrict = "Indoors"

[[npc]]
id = "npc.wydin"
inherit = "npc.wydin"
moveRestrict = "Indoors"

[[npc]]
id = "npc.grum"
inherit = "npc.grum"
moveRestrict = "Indoors"

[[npc]]
id = "npc.betty"
inherit = "npc.betty"
moveRestrict = "Indoors"

[[npc]]
id = "npc.brian"
inherit = "npc.brian"
moveRestrict = "Indoors"

[[npc]]
id = "npc.rustyanchor_bartender"
inherit = "npc.rustyanchor_bartender"
moveRestrict = "Indoors"

[[npc]]
id = "npc.sarim_pub_drinker_1"
inherit = "npc.sarim_pub_drinker_1"
moveRestrict = "Indoors"

[[npc]]
id = "npc.sarim_pub_drinker_2"
inherit = "npc.sarim_pub_drinker_2"
moveRestrict = "Indoors"

[[npc]]
id = "npc.sarim_pub_sitting_patron"
inherit = "npc.sarim_pub_sitting_patron"
moveRestrict = "NoMove"
wanderRange = 0
respawnDir = "South"

[[npc]]
id = "npc.jail_guard_sleeping"
inherit = "npc.jail_guard_sleeping"
moveRestrict = "NoMove"
wanderRange = 0
respawnDir = "SouthWest"

[[npc]]
id = "npc.sailing_intro_anne_sarim"
inherit = "npc.sailing_intro_anne_sarim"
moveRestrict = "NoMove"
wanderRange = 0
respawnDir = "South"

[[npc]]
id = "npc.sailing_intro_will_sarim"
inherit = "npc.sailing_intro_will_sarim"
moveRestrict = "NoMove"
wanderRange = 0
respawnDir = "East"

[[npc]]
id = "npc.port_task_master_port_sarim"
inherit = "npc.port_task_master_port_sarim"
wanderRange = 1
