plugins {
    id("base-conventions")
    id("game-cache-test-conventions")
}

dependencies {
    testImplementation(projects.api.invPlugin)
    testImplementation(projects.api.gameProcess)
    testImplementation(projects.api.invStorage)
    testImplementation(projects.api.registry)
    testImplementation(libs.fastutil)
    implementation(projects.api.pluginCommons)
    implementation(projects.api.scriptAdvanced)
    implementation(projects.api.attr)
    implementation(projects.api.instances)
    implementation(projects.api.music)
    implementation(projects.content.other.pets)
    implementation(projects.api.serverConfig)
    implementation(projects.content.generic.genericLocs)
    implementation(projects.api.bosses)
    implementation(projects.api.combat.combatFormulas)
    implementation(projects.api.spells)
    implementation(projects.content.interfaces.bank)
    implementation(projects.content.skills.magic.spellAttacks)
    implementation(libs.rsprot.api)
    implementation(projects.content.skills.slayer)
    implementation(projects.api.shops)
    implementation(projects.api.areaChecker)
    implementation(projects.api.death)
    implementation(projects.api.route)
    implementation(projects.api.combat.combatManager)
    implementation(projects.api.combat.combatCommons)
    implementation(projects.api.combat.combatWeapon)
    implementation(projects.api.weapons)
    implementation(projects.api.invWeight)
    implementation(projects.api.hunt)
    implementation(projects.content.interfaces.emotes)
}
