package org.rsmod.api.combatachievements

/** Boss ids from the monster filter of the task list, as the client resolves them. */
internal object CombatAchievementBosses {
    val killcountVarps: Map<Int, String> =
        mapOf(
            1 to "varp.total_abyssalsire_kills",
            2 to "varp.total_hydraboss_kills",
            3 to "varp.total_amoxliatl_kills",
            4 to "varp.total_araxxor_kills",
            5 to "varp.total_barrows_chests",
            6 to "varp.total_cowboss_kills",
            7 to "varp.total_bryophyta_kills",
            8 to "varp.total_callisto_kills",
            9 to "varp.total_cerberus_kills",
            10 to "varp.total_chaosele_kills",
            11 to "varp.total_chaosfanatic_kills",
            12 to "varp.total_crazyarchaeologist_kills",
            13 to "varp.total_completed_xericchambers",
            14 to "varp.total_completed_xericchambers_challenge",
            15 to "varp.total_corp_kills",
            16 to "varp.total_saradomin_kills",
            17 to "varp.total_completed_gauntlet",
            18 to "varp.total_completed_gauntlet_hm",
            19 to "varp.total_prime_kills",
            20 to "varp.total_rex_kills",
            21 to "varp.total_supreme_kills",
            22 to "varp.total_derangedarchaeologist_kills",
            23 to "varp.total_dom_levels",
            24 to "varp.total_duke_sucellus_kills",
            25 to "varp.total_sol_kills",
            26 to "varp.total_bandos_kills",
            27 to "varp.total_mole_kills",
            28 to "varp.total_gargboss_kills",
            29 to "varp.total_hespori_kills",
            30 to "varp.total_huey_kills",
            31 to "varp.total_kalphite_kills",
            32 to "varp.total_kbd_kills",
            33 to "varp.total_kraken_boss_kills",
            34 to "varp.total_armadyl_kills",
            35 to "varp.total_zamorak_kills",
            36 to "varp.total_leviathan_kills",
            37 to "varp.total_mad_angel_kills",
            38 to "varp.total_maggot_king_kills",
            39 to "varp.total_mimic_kills",
            40 to "varp.total_pmoon_chests",
            41 to "varp.total_nex_kills",
            42 to "varp.total_nightmare_kills",
            43 to "varp.total_nightmare_challenge_kills",
            44 to "varp.total_hillgiant_boss_kills",
            45 to "varp.total_muspah_kills",
            46 to "varp.total_royal_titan_kills",
            47 to "varp.total_rat_boss_kills",
            48 to "varp.total_sarachnis_kills",
            49 to "varp.total_scorpia_kills",
            50 to "varp.total_gryphon_boss_kills",
            51 to "varp.total_cata_boss_kills",
            52 to "varp.total_tempoross_kills",
            53 to "varp.total_completed_theatreofblood_story",
            54 to "varp.total_completed_theatreofblood",
            55 to "varp.total_completed_theatreofblood_hard",
            56 to "varp.total_thermy_kills",
            57 to "varp.total_completed_tombsofamascut_entry",
            58 to "varp.total_completed_tombsofamascut",
            59 to "varp.total_completed_tombsofamascut_expert",
            61 to "varp.total_zuk_kills",
            62 to "varp.total_jad_kills",
            63 to "varp.total_vardorvis_kills",
            64 to "varp.total_venenatis_kills",
            65 to "varp.total_vetion_kills",
            66 to "varp.total_vorkath_kills",
            67 to "varp.total_whisperer_kills",
            68 to "varp.total_wintertodt_kills",
            69 to "varp.total_yama_kills",
            70 to "varp.total_zalcano_kills",
            71 to "varp.total_snakeboss_kills",
        )

    val taskCountVarbits: Map<Int, String> =
        mapOf(
            1 to "varbit.ca_total_tasks_completed_abyssalsire",
            2 to "varbit.ca_total_tasks_completed_hydraboss",
            3 to "varbit.ca_total_tasks_completed_amoxliatl",
            4 to "varbit.ca_total_tasks_completed_araxxor",
            5 to "varbit.ca_total_tasks_completed_barrows",
            6 to "varbit.ca_total_tasks_completed_cowboss",
            7 to "varbit.ca_total_tasks_completed_bryophyta",
            8 to "varbit.ca_total_tasks_completed_callisto",
            9 to "varbit.ca_total_tasks_completed_cerberus",
            10 to "varbit.ca_total_tasks_completed_chaosele",
            11 to "varbit.ca_total_tasks_completed_chaosfanatic",
            12 to "varbit.ca_total_tasks_completed_crazyarchaeologist",
            13 to "varbit.ca_total_tasks_completed_xericchambers",
            14 to "varbit.ca_total_tasks_completed_xericchambers_challenge",
            15 to "varbit.ca_total_tasks_completed_corp",
            16 to "varbit.ca_total_tasks_completed_saradomin",
            17 to "varbit.ca_total_tasks_completed_gauntlet",
            18 to "varbit.ca_total_tasks_completed_gauntlet_hm",
            19 to "varbit.ca_total_tasks_completed_prime",
            20 to "varbit.ca_total_tasks_completed_rex",
            21 to "varbit.ca_total_tasks_completed_supreme",
            22 to "varbit.ca_total_tasks_completed_derangedarchaeologist",
            23 to "varbit.ca_total_tasks_completed_dom",
            24 to "varbit.ca_total_tasks_completed_dukesucellus",
            25 to "varbit.ca_total_tasks_completed_colosseum",
            26 to "varbit.ca_total_tasks_completed_bandos",
            27 to "varbit.ca_total_tasks_completed_mole",
            28 to "varbit.ca_total_tasks_completed_gargboss",
            29 to "varbit.ca_total_tasks_completed_hespori",
            30 to "varbit.ca_total_tasks_completed_hueycoatl",
            31 to "varbit.ca_total_tasks_completed_kalphite",
            32 to "varbit.ca_total_tasks_completed_kbd",
            33 to "varbit.ca_total_tasks_completed_kraken_boss",
            34 to "varbit.ca_total_tasks_completed_armadyl",
            35 to "varbit.ca_total_tasks_completed_zamorak",
            36 to "varbit.ca_total_tasks_completed_leviathan",
            37 to "varbit.ca_total_tasks_completed_mad_angel",
            38 to "varbit.ca_total_tasks_completed_maggotking",
            39 to "varbit.ca_total_tasks_completed_mimic",
            40 to "varbit.ca_total_tasks_completed_perilous_moons",
            41 to "varbit.ca_total_tasks_completed_nex",
            42 to "varbit.ca_total_tasks_completed_nightmare",
            43 to "varbit.ca_total_tasks_completed_phosanis",
            44 to "varbit.ca_total_tasks_completed_hillgiant_boss",
            45 to "varbit.ca_total_tasks_completed_muspah",
            46 to "varbit.ca_total_tasks_completed_royal_titans",
            47 to "varbit.ca_total_tasks_completed_rat_boss",
            48 to "varbit.ca_total_tasks_completed_sarachnis",
            49 to "varbit.ca_total_tasks_completed_scorpia",
            50 to "varbit.ca_total_tasks_completed_gryphon_boss",
            51 to "varbit.ca_total_tasks_completed_cata_boss",
            52 to "varbit.ca_total_tasks_completed_tempoross",
            53 to "varbit.ca_total_tasks_completed_theatreofblood_story",
            54 to "varbit.ca_total_tasks_completed_theatreofblood",
            55 to "varbit.ca_total_tasks_completed_theatreofblood_hard",
            56 to "varbit.ca_total_tasks_completed_thermy",
            57 to "varbit.ca_total_tasks_completed_tombsofamascut_entry",
            58 to "varbit.ca_total_tasks_completed_tombsofamascut",
            59 to "varbit.ca_total_tasks_completed_tombsofamascut_expert",
            60 to "varbit.ca_total_tasks_completed_tzhaarketrak",
            61 to "varbit.ca_total_tasks_completed_zuk",
            62 to "varbit.ca_total_tasks_completed_jad",
            63 to "varbit.ca_total_tasks_completed_vardorvis",
            64 to "varbit.ca_total_tasks_completed_venenatis",
            65 to "varbit.ca_total_tasks_completed_vetion",
            66 to "varbit.ca_total_tasks_completed_vorkath",
            67 to "varbit.ca_total_tasks_completed_whisperer",
            68 to "varbit.ca_total_tasks_completed_wintertodt",
            69 to "varbit.ca_total_tasks_completed_yama",
            70 to "varbit.ca_total_tasks_completed_zalcano",
            71 to "varbit.ca_total_tasks_completed_snakeboss",
        )

    val killcountTasks: List<KillcountTask> =
        listOf(
            KillcountTask(1, "varp.total_abyssalsire_kills", 20),
            KillcountTask(2, "varp.total_abyssalsire_kills", 50),
            KillcountTask(9, "varp.total_armadyl_kills", 50),
            KillcountTask(10, "varp.total_armadyl_kills", 100),
            KillcountTask(16, "varp.total_bandos_kills", 50),
            KillcountTask(17, "varp.total_bandos_kills", 100),
            KillcountTask(24, "varp.total_barrows_chests", 10),
            KillcountTask(25, "varp.total_barrows_chests", 25),
            KillcountTask(35, "varp.total_bryophyta_kills", 1),
            KillcountTask(36, "varp.total_bryophyta_kills", 5),
            KillcountTask(42, "varp.total_callisto_kills", 10),
            KillcountTask(43, "varp.total_callisto_kills", 20),
            KillcountTask(44, "varp.total_cata_boss_kills", 1),
            KillcountTask(45, "varp.total_cata_boss_kills", 5),
            KillcountTask(51, "varp.total_cerberus_kills", 75),
            KillcountTask(52, "varp.total_cerberus_kills", 150),
            KillcountTask(57, "varp.total_chaosele_kills", 10),
            KillcountTask(58, "varp.total_chaosele_kills", 25),
            KillcountTask(61, "varp.total_chaosfanatic_kills", 10),
            KillcountTask(62, "varp.total_chaosfanatic_kills", 25),
            KillcountTask(65, "varp.total_corp_kills", 25),
            KillcountTask(66, "varp.total_corp_kills", 50),
            KillcountTask(70, "varp.total_crazyarchaeologist_kills", 10),
            KillcountTask(71, "varp.total_crazyarchaeologist_kills", 25),
            KillcountTask(76, "varp.total_derangedarchaeologist_kills", 10),
            KillcountTask(77, "varp.total_derangedarchaeologist_kills", 25),
            KillcountTask(82, "varp.total_gargboss_kills", 25),
            KillcountTask(83, "varp.total_gargboss_kills", 50),
            KillcountTask(98, "varp.total_completed_gauntlet_hm", 5),
            KillcountTask(99, "varp.total_completed_gauntlet_hm", 10),
            KillcountTask(100, "varp.total_completed_gauntlet_hm", 50),
            KillcountTask(109, "varp.total_completed_gauntlet", 5),
            KillcountTask(110, "varp.total_completed_gauntlet", 20),
            KillcountTask(123, "varp.total_hespori_kills", 5),
            KillcountTask(129, "varp.total_hillgiant_boss_kills", 1),
            KillcountTask(130, "varp.total_hillgiant_boss_kills", 5),
            KillcountTask(135, "varp.total_hydraboss_kills", 75),
            KillcountTask(136, "varp.total_hydraboss_kills", 150),
            KillcountTask(147, "varp.total_jad_kills", 1),
            KillcountTask(148, "varp.total_jad_kills", 5),
            KillcountTask(157, "varp.total_kalphite_kills", 25),
            KillcountTask(158, "varp.total_kalphite_kills", 50),
            KillcountTask(162, "varp.total_kbd_kills", 10),
            KillcountTask(163, "varp.total_kbd_kills", 25),
            KillcountTask(168, "varp.total_kraken_boss_kills", 20),
            KillcountTask(176, "varp.total_mimic_kills", 1),
            KillcountTask(177, "varp.total_mole_kills", 10),
            KillcountTask(178, "varp.total_mole_kills", 25),
            KillcountTask(183, "varp.total_nightmare_kills", 1),
            KillcountTask(184, "varp.total_nightmare_kills", 25),
            KillcountTask(185, "varp.total_nightmare_kills", 50),
            KillcountTask(197, "varp.total_prime_kills", 10),
            KillcountTask(198, "varp.total_prime_kills", 25),
            KillcountTask(201, "varp.total_rex_kills", 10),
            KillcountTask(202, "varp.total_rex_kills", 25),
            KillcountTask(206, "varp.total_sarachnis_kills", 10),
            KillcountTask(207, "varp.total_sarachnis_kills", 25),
            KillcountTask(211, "varp.total_saradomin_kills", 50),
            KillcountTask(212, "varp.total_saradomin_kills", 100),
            KillcountTask(218, "varp.total_scorpia_kills", 10),
            KillcountTask(219, "varp.total_scorpia_kills", 25),
            KillcountTask(224, "varp.total_snakeboss_kills", 25),
            KillcountTask(225, "varp.total_snakeboss_kills", 75),
            KillcountTask(226, "varp.total_snakeboss_kills", 150),
            KillcountTask(233, "varp.total_supreme_kills", 10),
            KillcountTask(234, "varp.total_supreme_kills", 25),
            KillcountTask(237, "varp.total_completed_theatreofblood", 25),
            KillcountTask(238, "varp.total_completed_theatreofblood", 75),
            KillcountTask(239, "varp.total_completed_theatreofblood", 150),
            KillcountTask(261, "varp.total_thermy_kills", 20),
            KillcountTask(264, "varp.total_venenatis_kills", 10),
            KillcountTask(265, "varp.total_venenatis_kills", 20),
            KillcountTask(266, "varp.total_vetion_kills", 10),
            KillcountTask(267, "varp.total_vetion_kills", 20),
            KillcountTask(268, "varp.total_vorkath_kills", 50),
            KillcountTask(269, "varp.total_vorkath_kills", 100),
            KillcountTask(279, "varp.total_wintertodt_kills", 5),
            KillcountTask(280, "varp.total_wintertodt_kills", 10),
            KillcountTask(288, "varp.total_completed_xericchambers_challenge", 10),
            KillcountTask(289, "varp.total_completed_xericchambers_challenge", 25),
            KillcountTask(299, "varp.total_completed_xericchambers", 25),
            KillcountTask(300, "varp.total_completed_xericchambers", 75),
            KillcountTask(301, "varp.total_completed_xericchambers", 150),
            KillcountTask(328, "varp.total_zalcano_kills", 25),
            KillcountTask(332, "varp.total_zamorak_kills", 50),
            KillcountTask(333, "varp.total_zamorak_kills", 100),
            KillcountTask(342, "varp.total_zuk_kills", 5),
            KillcountTask(353, "varp.total_tempoross_kills", 5),
            KillcountTask(354, "varp.total_tempoross_kills", 10),
            KillcountTask(385, "varp.total_completed_theatreofblood_hard", 50),
            KillcountTask(397, "varp.total_completed_theatreofblood_story", 1),
            KillcountTask(400, "varp.total_nightmare_challenge_kills", 1),
            KillcountTask(401, "varp.total_nightmare_challenge_kills", 5),
            KillcountTask(402, "varp.total_nightmare_challenge_kills", 25),
            KillcountTask(410, "varp.total_nex_kills", 1),
            KillcountTask(411, "varp.total_nex_kills", 25),
            KillcountTask(461, "varp.total_completed_tombsofamascut_entry", 1),
            KillcountTask(462, "varp.total_completed_tombsofamascut_entry", 25),
            KillcountTask(463, "varp.total_completed_tombsofamascut_entry", 50),
            KillcountTask(466, "varp.total_completed_tombsofamascut", 25),
            KillcountTask(467, "varp.total_completed_tombsofamascut", 50),
            KillcountTask(468, "varp.total_completed_tombsofamascut", 1),
            KillcountTask(469, "varp.total_completed_tombsofamascut_expert", 1),
            KillcountTask(470, "varp.total_completed_tombsofamascut_expert", 25),
            KillcountTask(471, "varp.total_completed_tombsofamascut_expert", 50),
            KillcountTask(478, "varp.total_muspah_kills", 1),
            KillcountTask(479, "varp.total_muspah_kills", 25),
            KillcountTask(480, "varp.total_muspah_kills", 50),
            KillcountTask(488, "varp.total_vardorvis_kills", 1),
            KillcountTask(489, "varp.total_vardorvis_kills", 50),
            KillcountTask(490, "varp.total_vardorvis_awakened_kills", 1),
            KillcountTask(497, "varp.total_whisperer_kills", 1),
            KillcountTask(498, "varp.total_whisperer_kills", 50),
            KillcountTask(499, "varp.total_whisperer_awakened_kills", 1),
            KillcountTask(506, "varp.total_leviathan_kills", 1),
            KillcountTask(507, "varp.total_leviathan_kills", 50),
            KillcountTask(508, "varp.total_leviathan_awakened_kills", 1),
            KillcountTask(515, "varp.total_duke_sucellus_kills", 1),
            KillcountTask(516, "varp.total_duke_sucellus_kills", 50),
            KillcountTask(517, "varp.total_duke_sucellus_awakened_kills", 1),
            KillcountTask(521, "varp.total_rat_boss_kills", 1),
            KillcountTask(522, "varp.total_rat_boss_kills", 10),
            KillcountTask(529, "varp.total_pmoon_chests", 5),
            KillcountTask(530, "varp.total_pmoon_chests", 25),
            KillcountTask(538, "varp.total_sol_kills", 1),
            KillcountTask(539, "varp.total_sol_kills", 10),
            KillcountTask(556, "varp.total_araxxor_kills", 25),
            KillcountTask(557, "varp.total_araxxor_kills", 75),
            KillcountTask(568, "varp.total_huey_kills", 1),
            KillcountTask(569, "varp.total_huey_kills", 10),
            KillcountTask(570, "varp.total_huey_kills", 25),
            KillcountTask(579, "varp.total_amoxliatl_kills", 1),
            KillcountTask(580, "varp.total_amoxliatl_kills", 20),
            KillcountTask(589, "varp.total_royal_titan_kills", 10),
            KillcountTask(590, "varp.total_royal_titan_kills", 25),
            KillcountTask(599, "varp.total_yama_kills", 1),
            KillcountTask(600, "varp.total_yama_kills", 50),
            KillcountTask(625, "varp.total_gryphon_boss_kills", 25),
            KillcountTask(626, "varp.total_gryphon_boss_kills", 50),
            KillcountTask(632, "varp.total_cowboss_kills", 1),
            KillcountTask(633, "varp.total_cowboss_kills", 10),
            KillcountTask(637, "varp.total_maggot_king_kills", 1),
            KillcountTask(638, "varp.total_maggot_king_kills", 25),
            KillcountTask(646, "varp.total_mad_angel_kills", 25),
            KillcountTask(647, "varp.total_mad_angel_kills", 50),
        )

    /** Tasks completed by killing any npc with this name, such as a slayer monster. */
    val namedKillTasks: Map<Int, String> =
        mapOf(
            0 to "aberrant spectre",
            31 to "basilisk knight",
            32 to "black dragon",
            33 to "bloodveld",
            34 to "brutal black dragon",
            74 to "demonic gorilla",
            80 to "fire giant",
            97 to "gargoyle",
            120 to "greater demon",
            122 to "hellhound",
            173 to "kurask",
            174 to "lizardman shaman",
            223 to "skeletal wyvern",
            287 to "wyrm",
            551 to "tormented demon",
            341 to "jal-zek",
        )
}

internal data class KillcountTask(val id: Int, val varp: String, val count: Int)
